RedHatInsights/red-hat-ansible-automation-platform-documentation

LICENSE.txt, docinfo.xml, master.adoc, metadata.ini
reorganize content in the origin repo
=> move files

doc/assembly_Getting_started.adoc, doc/modules/proc_Approval_workflow.adoc, doc/modules/proc_Approve_deny_request.adoc, doc/modules/proc_Comment_on_request.adoc, doc/modules/proc_Creating_portfolios.adoc, doc/modules/proc_Editing_portfolios.adoc, doc/modules/proc_Sharing_portfolios.adoc
Remove all instances of "procedure" and replace with appropriate prescriptive statement based on that procedure.
=> Remove procedure

doc/assembly_Getting_started.adoc, doc/modules/con_Editing_portfolios.adoc
This PR adds a concept and procedure for editing portfolios.
=> Add Editing portfolios concept and procedure.

attributes/catalog.adoc, doc/modules/con_Approval.adoc, doc/modules/proc_Approval_workflow.adoc
This PR updates Approval documentation to reflect the change to a group-based approval workflow.
=> update approval workflows

doc/modules/con_Adding_products.adoc, doc/modules/proc_Add_products_from_platforms.adoc
Quick update here on adding a product from a platform to a portfolio.
=> Update workflow for adding products from platform to portfolio

downstream/assemblies/navigator/assembly-execute-playbook-navigator.adoc, downstream/modules/navigator/proc-execute-playbook-cli.adoc, downstream/modules/navigator/proc-execute-playbook-tui.adoc, downstream/modules/navigator/proc-review-artifact.adoc
Document how to run playbooks in navigator.
=> Run playbooks

downstream/assemblies/navigator/assembly-review-inventory-navigator.adoc, downstream/modules/navigator/proc-review-inventory-cli.adoc, downstream/modules/navigator/proc-review-inventory-tui.adoc
Documents how to review inventory from CLI or TUI
=> reviewing inventory in navigator

downstream/assemblies/navigator/assembly-browse-collections-navigator.adoc, downstream/modules/navigator/con-navigator-collections.adoc, downstream/modules/navigator/proc-browse-collections-tui.adoc
Implemented feedback on collections assembly that came after the merge PR #70
=> Collections feedback

release-notes/docinfo.xml, release-notes/master.adoc, release-notes/topics/bugfixes-022020.adoc, release-notes/topics/bugfixes-052020.adoc, release-notes/topics/bugfixes-102020.adoc, release-notes/topics/catalog-11-2020.adoc, release-notes/topics/changelog-022020.adoc, release-notes/topics/enhancements-052020.adoc, release-notes/topics/enhancements-102020.adoc, release-notes/topics/enhancements.adoc, release-notes/topics/hub-42.adoc, release-notes/topics/hub-421.adoc, release-notes/topics/hub-422.adoc, release-notes/topics/hub-423.adoc, release-notes/topics/introduction.adoc, release-notes/topics/new-features-feb-2020.adoc, release-notes/topics/new-features-may-2020.adoc, release-notes/topics/new-features-oct-2020.adoc, release-notes/topics/platform-installer-121.adoc, release-notes/topics/platform-intro.adoc, release-notes/topics/tower-intro-38.adoc, release-notes/topics/tower-intro-381.adoc, release-notes/topics/tower-intro-382.adoc, release-notes/topics/tower-intro-383.adoc, release-notes/topics/upgrading.adoc
This PR adds our release notes to the upstream repo
=> Add release notes

release-notes/master.adoc, release-notes/topics/insights-062021.adoc
Created release notes for 1.3 and added it to the master.adoc.
@cbudz please review for style and syntax (wanted to make sure I got the release notes syntax and organization right, since I haven't done these before). Thanks
=> Insights for AAP - 1.3 release notes

downstream/titles/analytics/automation-savings/docinfo.xml, downstream/titles/analytics/job-explorer/docinfo.xml, downstream/titles/analytics/user-access/docinfo.xml, downstream/titles/catalog/getting-started/docinfo.xml, downstream/titles/catalog/itsm-integration/docinfo.xml, downstream/titles/catalog/lifecycle/docinfo.xml, downstream/titles/catalog/managing-products/docinfo.xml, downstream/titles/catalog/support-matrix/docinfo.xml, downstream/titles/hub/configuring-galaxy-cli/master-docinfo.xml, downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml, downstream/titles/hub/getting-started/docinfo.xml, downstream/titles/hub/lifecycle/docinfo.xml, downstream/titles/hub/managing-user-access/docinfo.xml, downstream/titles/hub/obtaining-token/docinfo.xml, downstream/titles/hub/publishing-internal-content/docinfo.xml, downstream/titles/hub/uploading-collections/docinfo.xml
Updating version # in docinfo file for 2.0 branch.
=> Update for 2.0 version

README.adoc
Fixed link to mod-docs reference guide build.
=> README: Link to mod-docs guide build

downstream/titles/navigator-guide/master.adoc
=> move settings section

downstream/modules/navigator/con-about-ansible-navigator.adoc
=> remove controller integration bits

downstream/modules/navigator/proc-installing-navigator-rhel-pip.adoc, downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc, downstream/modules/navigator/proc-installing-navigator-rhel-tar.adoc
Based on testathon feedback, updated the install prerequisites.
=> update navigator install  prereqs

downstream/assemblies/hub/assembly-container-user-access.adoc, downstream/assemblies/hub/assembly-managing-container-registry.adoc
=> Fix attribute typo

downstream/modules/builder/con-building-definition-file.adoc, downstream/modules/builder/con-definition-dependencies.adoc, downstream/modules/builder/proc-customize-ee-image.adoc, downstream/modules/builder/ref-build-args-base-image.adoc
Jira issue link: https://issues.redhat.com/browse/AAP-416
=> AAP-416 Fix typos in Builder docs

downstream/modules/builder/con-building-definition-file.adoc, downstream/modules/builder/con-definition-dependencies.adoc, downstream/modules/builder/proc-customize-ee-image.adoc, downstream/modules/builder/ref-build-args-base-image.adoc
Jira issue link: https://issues.redhat.com/browse/AAP-416
=> AAP-416 Backport PR144 to 2.0-ea Fix typos in Builder docs

downstream/assemblies/navigator/assembly-installing-on-rhel.adoc, downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
(cherry picked from commit b0b85d735c856faf593b9099ec0543ccdb9b10ce)
=> [backport] remove mention of pip

downstream/assemblies/platform/assembly-installing-controller-operator-external-db.adoc, downstream/assemblies/platform/assembly-installing-controller-operator-local-db.adoc, downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc, downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc, downstream/assemblies/platform/assembly-operator-install-planning.adoc, downstream/attributes/attributes.adoc, downstream/titles/aap-operator-installation/attributes, downstream/titles/aap-operator-installation/docinfo.xml, downstream/titles/aap-operator-installation/master.adoc, downstream/titles/aap-operator-installation/platform
Opening this PR to track operator installation docs.
=> Operator installation

downstream/modules/catalog/proc-preparing-worker-installer.adoc
Backport PR #151 from master: fix catalog worker install doc in title/worker-install
=> Backport PR #151 from master: fix catalog worker install doc in title/worker-install

downstream/assemblies/platform/assembly-installing-controller-operator-external-db.adoc, downstream/assemblies/platform/assembly-installing-controller-operator-local-db.adoc, downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc, downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc, downstream/assemblies/platform/assembly-operator-install-planning.adoc, downstream/attributes/attributes.adoc, downstream/titles/aap-operator-installation/attributes, downstream/titles/aap-operator-installation/docinfo.xml, downstream/titles/aap-operator-installation/master.adoc, downstream/titles/aap-operator-installation/platform
Affects `/titles/aap-operator-installation/` Operator installation book.
Cherry-picked the following commits from master, in the order oldest to newest:
f34322a (upstream/master, origin/master, origin/HEAD, master) First draft of operator install procedures (#154) (Newest commit)
303b931 Merge pull request #153 from ariordan-redhat/operator-concept
6448458 (origin/operator-concept) Add operator names to attributes file
6d7193a Platform operator concept content - initial commit
f03f682 Merge pull request #95 from cbudz/hub-operator. (Oldest commit)
=> Backport commits to create platform operator title from master

downstream/assemblies/platform/assembly-operator-install-planning.adoc, downstream/attributes/attributes.adoc
Jira issue: https://issues.redhat.com/browse/AAP-516 - AAP Operator Installation guide
- Changed operator attribute values per updates in spreadsheet
- Added concept content
Preview here: http://file.emea.redhat.com/~ariordan/operator/operator-concept/build/tmp/en-US/html-single/
=> Add Platform operator concept content

downstream/titles/aap-operator-installation/docinfo.xml
Quick fix here so I can set-up preview for 2.0-ea docs set.
=> update product number in docinfo.xml

release-notes/master.adoc, release-notes/topics/hub-423.adoc, release-notes/topics/hub-424.adoc, release-notes/topics/hub-426.adoc, release-notes/topics/platform-intro-124.adoc, release-notes/topics/platform-intro-125.adoc, release-notes/topics/tower-intro-383.adoc, release-notes/topics/tower-intro-384.adoc
Adding recent 1.2.z updates to the release notes.
=> update release notes

release-notes/master.adoc, release-notes/topics/hub-423.adoc, release-notes/topics/hub-424.adoc, release-notes/topics/hub-426.adoc, release-notes/topics/platform-intro-124.adoc, release-notes/topics/platform-intro-125.adoc, release-notes/topics/tower-intro-383.adoc, release-notes/topics/tower-intro-384.adoc
=> Rel notes backport

downstream/assemblies/security/assembly-idps.adoc, downstream/modules/security/con-automate-idps-rules.adoc, downstream/modules/security/con-requirements.adoc, downstream/modules/security/proc-creating-idps-rule.adoc, downstream/modules/security/proc-verifying-idps-install.adoc, downstream/titles/security-guide/master.adoc
Changed all instances of "IDS" to "IDPS"
- Link to Jira: https://issues.redhat.com/browse/AAP-734
- Link to google doc: https://docs.google.com/document/d/1VU0BpbM8RUvchmYmjYdZslkgtvM1BJZV6ZT4Cbrklig/edit#
=> AAP-734: Change all IDS to IDPS

downstream/assemblies/security/assembly-idps.adoc, downstream/modules/security/con-automate-idps-rules.adoc, downstream/modules/security/con-requirements.adoc, downstream/modules/security/proc-creating-idps-rule.adoc, downstream/modules/security/proc-verifying-idps-install.adoc, downstream/titles/security-guide/master.adoc
Backport PR#170 AAP-734: Removed s in systems and changed IDS to IDPS
Affects Security Guide
=> Backport PR#170 AAP-734: Removed s in systems and changed IDS to IDPS

downstream/assemblies/analytics/assembly-insights-reports.adoc, downstream/modules/analytics/proc-review-reports.adoc, downstream/titles/analytics/reports/analytics, downstream/titles/analytics/reports/attributes, downstream/titles/analytics/reports/docinfo.xml, downstream/titles/analytics/reports/master.adoc
The following guide introduces the new reports feature on the AAP, including a basic procedure about how to access the report.
Preview link here: http://file.rdu.redhat.com/kevchin/analytics/reports/tmp/en-US/html-single/
@cbudz please review for any style/organizational changes. Thanks
=> Insights for AAP - Reports feature

downstream/assemblies/analytics/assembly-insights-reports.adoc, downstream/modules/analytics/proc-review-reports.adoc, downstream/titles/analytics/reports/analytics, downstream/titles/analytics/reports/attributes, downstream/titles/analytics/reports/docinfo.xml, downstream/titles/analytics/reports/master.adoc
Backport of reports feature to 1.2 branch.
=> [Backport] 1.2 Insights Reports feature 

release-notes/master.adoc, release-notes/topics/insights-102021.adoc, release-notes/topics/platform-intro.adoc
Added an october section to the AAP release notes and a section about the new insights reports feature. Also updated Automation Analytics to Insights for AAP in the intro.
=> Insights for AAP - October release notes update

downstream/attributes/attributes.adoc
=> update attributes file

downstream/assemblies/hub/assembly-user-access.adoc, downstream/modules/automation-hub/proc-create-super-users.adoc
Issue: https://issues.redhat.com/browse/AAH-507
Adds a module about creating a super user.
=> AAH-507 super user module

downstream/assemblies/hub/assembly-deploying-high-availability-hub.adoc, downstream/modules/automation-hub/con-network-storage-reqs.adoc, downstream/modules/automation-hub/con-required-changes-ha.adoc, downstream/modules/automation-hub/con-required-shared-filesystem.adoc, downstream/titles/hub/high-availability/attributes, downstream/titles/hub/high-availability/docinfo.xml, downstream/titles/hub/high-availability/hub, downstream/titles/hub/high-availability/master.adoc
Technical SME-reviewed draft of the high availity (HA) hub deployment guide.
Preview link: http://file.rdu.redhat.com/kevchin/hub/high-availability/tmp/en-US/html-single/
Relevant JIRA tickets: https://issues.redhat.com/browse/AAP-383, https://issues.redhat.com/browse/AAH-470
=> Hub: High Availability Deployment

downstream/assemblies/platform/assembly-deprovisioning-mesh.adoc, downstream/assemblies/platform/assembly-example-topologies.adoc, downstream/assemblies/platform/assembly-planning-mesh.adoc, downstream/attributes/attributes.adoc, downstream/modules/platform/con-about-automation-mesh.adoc, downstream/modules/platform/con-automation-mesh-node-types.adoc, downstream/modules/platform/proc-defining-node-types.adoc, downstream/modules/platform/proc-deprovision-group.adoc, downstream/modules/platform/proc-deprovisioning-mesh-nodes.adoc, downstream/modules/platform/ref-complex-mesh-topology.adoc, downstream/modules/platform/ref-control-plane-execution-nodes-fully-connected.adoc, downstream/modules/platform/ref-control-plane-execution-topo-hop-nodes.adoc, downstream/modules/platform/ref-control-plane-with-single-egress.adoc, downstream/modules/platform/ref-deprovision-node.adoc, downstream/modules/platform/ref-deprovisioned-nodes.adoc, downstream/modules/platform/ref-multiple-hybrid-nodes.adoc, downstream/modules/platform/ref-single-hybrid-node-only.adoc, downstream/modules/platform/ref-single-node-control-plane-single-execution-node.adoc, downstream/titles/automation-mesh/attributes, downstream/titles/automation-mesh/docinfo.xml, downstream/titles/automation-mesh/master.adoc, downstream/titles/automation-mesh/platform
This PR adds automation mesh content.
=> Adding mesh files

downstream/titles/aap-installation-guide/docinfo.xml, downstream/titles/aap-operator-installation/docinfo.xml, downstream/titles/analytics/automation-savings-planner/docinfo.xml, downstream/titles/analytics/automation-savings/docinfo.xml, downstream/titles/analytics/job-explorer/docinfo.xml, downstream/titles/analytics/reports/docinfo.xml, downstream/titles/analytics/user-access/docinfo.xml, downstream/titles/builder/docinfo.xml, downstream/titles/catalog/getting-started/docinfo.xml, downstream/titles/catalog/itsm-integration/docinfo.xml, downstream/titles/catalog/lifecycle/docinfo.xml, downstream/titles/catalog/managing-products/docinfo.xml, downstream/titles/catalog/support-matrix/docinfo.xml, downstream/titles/dev-guide/docinfo.xml, downstream/titles/hub/configuring-galaxy-cli/master-docinfo.xml, downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml, downstream/titles/hub/getting-started/docinfo.xml, downstream/titles/hub/install/docinfo.xml, downstream/titles/hub/lifecycle/docinfo.xml, downstream/titles/hub/manage-containers/docinfo.xml, downstream/titles/hub/managing-user-access/docinfo.xml, downstream/titles/hub/obtaining-token/docinfo.xml, downstream/titles/hub/publishing-internal-content/docinfo.xml, downstream/titles/hub/uploading-collections/docinfo.xml, downstream/titles/migration/docinfo.xml, downstream/titles/navigator-guide/docinfo.xml, downstream/titles/security-guide/docinfo.xml, downstream/titles/upgrade/docinfo.xml, downstream/titles/worker-install/docinfo.xml
Update all docinfo.xml files with 2.1 version number for publication.
=> Update AAP version in docinfo files

downstream/titles/builder/master.adoc
fixing the builder title in master
=> update builder title

downstream/modules/catalog/proc-preparing-worker-installer.adoc
Backport of changes from AAP-1222
=> fix typo in worker module

downstream/modules/builder/proc-customize-ee-image.adoc
Updated the Ansible Builder guide with some feedback based on AAP-396.
Preview: http://file.rdu.redhat.com/cbudzilo/builder/build/tmp/en-US/html-single/#proc-pull-protected-registry
=> Update doc with reporter feedback

downstream/modules/builder/proc-customize-ee-image.adoc
backporting updates to 2.1 branch
=> AAP-396 backport

downstream/modules/platform/ref-system-requirements.adoc
Updating system requirements for 2.1
http://file.rdu.redhat.com/cbudzilo/sysreqs/build/tmp/en-US/html-single/#red_hat_ansible_automation_platform_system_requirements
Preview:
=> update system reqs

release-notes/master.adoc
I made a mistake in my last PR and added another header in master.adoc.
=> extra header

release-notes/docinfo.xml
Updating version # in release notes docinfo file
=> update version number

downstream/assemblies/hub/assembly-deploying-high-availability-hub.adoc, downstream/modules/automation-hub/con-required-changes-ha.adoc, downstream/titles/hub/high-availability/master.adoc
Incorporated peer review edits. 
Preview: http://file.rdu.redhat.com/kevchin/hub/high-availability2/build/tmp/en-US/html-single/
=> Hub HA - peer review edits

release-notes/topics/platform-intro.adoc
Component numbers are incorrect in 2.1 release notes. This PR fixes the numbers and additionally adds corrected component names
=> Correct component version numbers

downstream/assemblies/controller/assembly-controller-temp.adoc, downstream/assemblies/controller/controller, downstream/modules/controller/con-controller-temp.adoc, downstream/titles/controller/attributes, downstream/titles/controller/controller, downstream/titles/controller/docinfo.xml, downstream/titles/controller/master.adoc
- Rename 'tower' directories to `controller`
- Create files and symbolic links in `/titles`
- Create a temporary skeleton module and assembly 
so that
We can work on documentation for Controller.
=> Controller guide setup

release-notes/master.adoc, release-notes/topics/controller-41.adoc, release-notes/topics/platform-intro-124.adoc
Jira issue: [AAP-1945](https://issues.redhat.com/browse/AAP-1945)
Capture the name change from Tower to Controller in the AAP 2.1 release notes.
=> aap-1945 Add controller info to AAP 2.1 release notes

downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc, downstream/assemblies/platform/assembly-multi-machine-install.adoc, downstream/assemblies/platform/assembly-platform-ext-database-install.adoc, downstream/assemblies/platform/assembly-platform-non-inst-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-non-inst-database-installation.adoc, downstream/assemblies/platform/assembly-upgrading-to-aap.adoc, downstream/modules/platform/con-cluster-platform-ext-database.adoc, downstream/modules/platform/con-upgrade-planning.adoc, downstream/modules/platform/proc-attaching-subscriptions.adoc, downstream/titles/aap-installation-guide/docinfo.xml, downstream/titles/hub/lifecycle/master.adoc, downstream/titles/upgrade/master.adoc, release-notes/master.adoc, release-notes/topics/controller-41.adoc, release-notes/topics/platform-intro-124.adoc
Backporting the following PRs:
- PR 236
- PR 238
- PR 239
- PR 240
- PR 241
- PR 242
=> Backport PRs #236, 238, 239, 240, 241, 242

downstream/titles/worker-install/docinfo.xml, downstream/titles/worker-install/master.adoc
Jira: https://issues.redhat.com/browse/AAP-1790
Removed version number to be version agnostic
=> AAP-1790 Fixed incorrect AAP version number in catalog worker docs

downstream/assemblies/hub/assembly-user-access.adoc, downstream/assemblies/hub/assembly-view-only-access.adoc, downstream/modules/automation-hub/con-enable-view-only.adoc, downstream/titles/hub/managing-user-access/docinfo.xml, downstream/titles/hub/managing-user-access/master.adoc
Backport [PR#251](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/251/commits) from master to the 2.1 release branch.
Jira issue: [AAH-920](https://issues.redhat.com/browse/AAH-920)
=> AAH-920 Create documentation for view-only Hub (#251)

downstream/modules/automation-hub/proc-push-container.adoc
Backport [PR#253](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/253/commits) from master to the 2.1 release branch.
Jira issue: [AAP-1799](https://issues.redhat.com/browse/AAP-1799)
=> AP-1799 Update podman push command when pushing registry images (#253)

downstream/assemblies/hub/assembly-container-user-access.adoc, downstream/assemblies/hub/assembly-delete-container.adoc, downstream/modules/automation-hub/proc-add-container-readme.adoc, downstream/modules/automation-hub/proc-add-group-to-container-repo.adoc, downstream/modules/automation-hub/proc-add-user-to-group.adoc, downstream/modules/automation-hub/proc-assigning-permissions.adoc, downstream/modules/automation-hub/proc-create-groups.adoc, downstream/modules/automation-hub/proc-delete-container.adoc, downstream/modules/automation-hub/proc-obtain-images.adoc, downstream/modules/automation-hub/proc-pull-image.adoc, downstream/modules/automation-hub/proc-push-container.adoc, downstream/modules/automation-hub/proc-tag-image.adoc, downstream/modules/automation-hub/proc-tag-pulled-image.adoc, downstream/modules/automation-hub/ref-container-permissions.adoc, downstream/titles/hub/manage-containers/docinfo.xml
Backport the following commits from 2.1:
```
5f7667a 3rd formatting fix
2f779ab another formatting fix for repleaceable text
3d24581 fixed formatting on replaceable text
8f901d2 peer feedback
04f1031 updated managing containers title to reflect UI changes
```
=> AAP-2054 Update procedures for managing containers in private hub (#257)

downstream/titles/hub/managing-user-access/master.adoc
AAP-2389 Delete image reference in master.adoc for _Managing User Access in Private Automation Hub_ guide
=> AAP-2389 Modify reference to image directory

downstream/titles/hub/managing-user-access/master.adoc
AAP-2389 Delete image reference in master.adoc for _Managing User Access in Private Automation Hub_ guide
=> AAP-2389 Modify reference to image directory (#266)

release-notes/master.adoc, release-notes/topics/aap-126.adoc, release-notes/topics/aap-211.adoc, release-notes/topics/controller-411.adoc, release-notes/topics/hub-441.adoc, release-notes/topics/upgrading.adoc
* added platform, hub, controller release notes
* fix build error
* added aap 1.2.6 release notes as january 2022
* update master.adoc
* incorporated sme's feedback
* Fix typo
Co-authored-by: Aine Riordan <44700011+ariordan-redhat@users.noreply.github.com>
=> AAP-1862 Release notes for AAP January and February 2022 release (#261)

downstream/modules/automation-hub/proc-delete-user.adoc, downstream/modules/controller/proc-controller-delete-user.adoc
* aap-2389 Add delete user module to controller
* aap-2389 Fix typos
=> aap-2389 Add delete user module to controller (#272)

downstream/assemblies/aap-on-azure/assembly-aap-azure-install.adoc
In PR#275 (backport Azure doc to 2.1), the review noted some errors. Copying these fixes to the master branch.
=> AAP-2657 Ansible on Azure doc fixes

downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc, downstream/assemblies/platform/assembly-installing-controller-operator-external-db.adoc, downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc, downstream/modules/platform/con-ocp-supported-install.adoc, downstream/modules/platform/proc-cli-get-controller-pwd.adoc, downstream/modules/platform/proc-install-cli-aap-operator.adoc, downstream/titles/aap-operator-installation/master.adoc
Backport PR#225 to 2.1
* aap-597 Change titles of assemblies to indicate use of web console
* aap-597 Edits per review comments
Co-authored-by: kevchin <kevchin@redhat.com>
=> AAP-597 Add procedure to install AAP operator on CLI  (#225)

downstream/titles/snippets/docinfo-feedback.xml
Backport boilerplate text for the docinfo.xml abstract (#277)
=> Boilerplate text for the docinfo.xml abstract (#277)

downstream/modules/platform/con-operator-additional-resources.adoc, downstream/modules/platform/proc-install-aap-operator.adoc
Backport PR#283 to 2.1.
Affects operator doc.
=> Fix operator modules (#283)

downstream/assemblies/platform/assembly-install-aap-operator.adoc, downstream/assemblies/platform/assembly-installing-controller-operator.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/platform/proc-install-aap-operator.adoc, downstream/modules/platform/proc-operator-external-db-controller.adoc, downstream/modules/platform/proc-operator-external-db-hub.adoc, downstream/titles/aap-operator-installation/master.adoc
Backport PR#288 to 2.1 
Title affected: `titles/aap-operator-installation`
=> AAP-2328 Configuring external database for hub/controller (#288)

downstream/assemblies/platform/assembly-multi-machine-install.adoc, downstream/assemblies/platform/assembly-platform-ext-database-install.adoc, downstream/assemblies/platform/assembly-platform-non-inst-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-non-inst-database-installation.adoc, downstream/assemblies/platform/assembly-standalone-hub-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-hub-non-inst-database.adoc
Jira: [](https://issues.redhat.com/browse/AAP-2029)https://issues.redhat.com/browse/AAP-2029
Added link to installer file in the "Prerequisites" sections so that users have everything they need before they get to the instructions.
Preview link: [](http://file.rdu.redhat.com/~lmodemal/aap-installation-guide-220330/master.html) http://file.rdu.redhat.com/~lmodemal/aap-installation-guide-220330/master.html
=> AAP-2029: Added link to installer file

downstream/assemblies/platform/assembly-multi-machine-install.adoc, downstream/assemblies/platform/assembly-platform-ext-database-install.adoc, downstream/assemblies/platform/assembly-platform-non-inst-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-non-inst-database-installation.adoc, downstream/assemblies/platform/assembly-standalone-hub-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-hub-non-inst-database.adoc
Backport [PR#290](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/290) to 2.1
Jira issue: [AAP-2029](https://issues.redhat.com/browse/AAP-2029) 
Added link to installer file in the "Prerequisites" sections so that users have everything they need before they get to the instructions.
=> AAP-2029: Fixed sentences

downstream/assemblies/platform/assembly-migrate-platform.adoc, downstream/assemblies/platform/assembly-multi-machine-install.adoc, downstream/assemblies/platform/assembly-planning-installation.adoc, downstream/assemblies/platform/assembly-platform-ext-database-install.adoc, downstream/assemblies/platform/assembly-platform-non-inst-database.adoc, downstream/assemblies/platform/assembly-platform-whats-next.adoc, downstream/assemblies/platform/assembly-standalone-controller-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-non-inst-database-installation.adoc, downstream/assemblies/platform/assembly-standalone-hub-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-hub-non-inst-database.adoc, downstream/attributes/attributes.adoc, downstream/modules/platform/con-why-automation-mesh.adoc, downstream/modules/platform/con-why-migrate-ansible-29.adoc, downstream/modules/platform/con-why-migrate-ansible-core-212.adoc, downstream/modules/platform/con-why-migrate-venvs-ee.adoc, downstream/modules/platform/proc-verify-controller-installation.adoc, downstream/modules/platform/proc-verify-hub-installation.adoc, downstream/modules/platform/ref-controller-configs.adoc, downstream/modules/platform/ref-hub-configs.adoc, downstream/modules/platform/ref-setup-script-args.adoc
Backport #293 and #294 to `2.1` branch. 
Title affected: `titles/aap-installation-guide`
=> Added AAP installation guide improvements (#293) and  {PlatformVers} Attribute (#294) 

downstream/modules/automation-hub/proc-set-community-remote.adoc
Jira: [AAP-2082](https://issues.redhat.com/browse/AAP-2082)
Modify community remote URL
=> AAP-2082 Modify community remote URL

downstream/modules/automation-hub/proc-set-community-remote.adoc
Backport #305 to 2.1
Jira: [AAP-2082](https://issues.redhat.com/browse/AAP-2082)
Modify community remote URL
=> AAP-2082 Modify community remote URL (#305)

downstream/assemblies/dev-guide/assembly-migrating-existing-content.adoc, downstream/assemblies/hub/assembly-faq.adoc, downstream/assemblies/platform/assembly-example-topologies.adoc, downstream/assemblies/platform/assembly-installing-automation-mesh.adoc, downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc, downstream/assemblies/platform/assembly-migrating-to-mesh.adoc, downstream/modules/aap-on-azure/proc-azure-provisioning-aap.adoc, downstream/modules/automation-hub/proc-delete-collection.adoc, downstream/modules/catalog/proc_Generate-ansible-token.adoc, downstream/modules/dev-guide/proc-select-custom-venv-export.adoc, downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc, downstream/modules/navigator/proc-review-inventory-tui.adoc, downstream/modules/navigator/ref-faq-navigator.adoc, downstream/titles/analytics/job-explorer/docinfo.xml, downstream/titles/catalog/itsm-integration/docinfo.xml, downstream/titles/catalog/itsm-integration/master.adoc
This PR fixes a few minor spelling issues.
=> minor spelling fixes

downstream/assemblies/dev-guide/assembly-migrating-existing-content.adoc, downstream/assemblies/hub/assembly-faq.adoc, downstream/assemblies/platform/assembly-example-topologies.adoc, downstream/assemblies/platform/assembly-installing-automation-mesh.adoc, downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc, downstream/assemblies/platform/assembly-migrating-to-mesh.adoc, downstream/modules/aap-on-azure/proc-azure-provisioning-aap.adoc, downstream/modules/catalog/proc_Generate-ansible-token.adoc, downstream/modules/dev-guide/proc-select-custom-venv-export.adoc, downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc, downstream/modules/navigator/proc-review-inventory-tui.adoc, downstream/modules/navigator/ref-faq-navigator.adoc, downstream/titles/analytics/job-explorer/docinfo.xml, downstream/titles/catalog/itsm-integration/docinfo.xml, downstream/titles/catalog/itsm-integration/master.adoc
=> [2.1] minor spelling fixes (#315)

release-notes/master.adoc, release-notes/topics/aap-22.adoc, release-notes/topics/catalog-05-2022.adoc, release-notes/topics/controller-420.adoc, release-notes/topics/hub-450.adoc
Recreating Release Notes PR because I forgot to squash and merge in previous PR. https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/309
Those changes were reverted in https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/319.
=> RN_May_2022 - Recreating RN updates

downstream/attributes/attributes.adoc, downstream/titles/aap-installation-guide/docinfo.xml, downstream/titles/aap-operator-installation/docinfo.xml, downstream/titles/analytics/automation-savings-planner/docinfo.xml, downstream/titles/analytics/automation-savings/docinfo.xml, downstream/titles/analytics/job-explorer/docinfo.xml, downstream/titles/analytics/reports/docinfo.xml, downstream/titles/automation-mesh/docinfo.xml, downstream/titles/builder/docinfo.xml, downstream/titles/catalog/getting-started/docinfo.xml, downstream/titles/catalog/itsm-integration/docinfo.xml, downstream/titles/catalog/support-matrix/docinfo.xml, downstream/titles/central-auth/docinfo.xml, downstream/titles/dev-guide/docinfo.xml, downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml, downstream/titles/hub/getting-started/docinfo.xml, downstream/titles/hub/high-availability/docinfo.xml, downstream/titles/hub/manage-containers/docinfo.xml, downstream/titles/hub/managing-user-access/docinfo.xml, downstream/titles/hub/publishing-internal-content/docinfo.xml, downstream/titles/hub/uploading-collections/docinfo.xml, downstream/titles/hub/uploading-internal-collections/docinfo.xml, downstream/titles/navigator-guide/docinfo.xml, downstream/titles/security-guide/docinfo.xml, downstream/titles/upgrade/docinfo.xml, downstream/titles/worker-install/docinfo.xml
Jira issue: [AAP-3819](https://issues.redhat.com/browse/AAP-3819)
=> aap-3819 Update release version before cutting 2.2 branch

release-notes/topics/platform-intro.adoc
Adding back the missed updates to the What's Included table:
Preview link (requires VPN) http://file.rdu.redhat.com/~ddacosta/Release_Notes052022/master.html
=> RNFix - Updated What's Included table per SME feedback

release-notes/topics/platform-intro.adoc
Backporting the Release Notes fix to the 2.2 branch.
=> RNFix - Updated What's Included table per SME feedback (#326)

release-notes/topics/platform-intro.adoc
Backporting changes from PR328 to the 2.2 branch.
* RNHubfix - updated available Hub version in table
* RNHubfix - removed .html file from folder
=> RNHubfix - updated available Hub version in table (#328)

downstream/assemblies/hub/assembly-deploying-high-availability-hub.adoc, downstream/modules/automation-hub/con-required-changes-ha.adoc, downstream/titles/hub/high-availability/master.adoc
Backporting an old PR (https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/205) before I continue work on the HA docs
=> [Backport PR#205] Peer feedback for HA Hub deployment 

downstream/modules/aap-on-azure/con-aap-azure-infrastructure-usage.adoc, downstream/modules/aap-on-azure/proc-azure-accessing-aap.adoc, downstream/modules/aap-on-azure/proc-azure-configure-ad-sso.adoc
Fix link to Microsoft Azure usage calculator
=> AAP-3543 Fix links (#336)

downstream/modules/aap-on-azure/con-aap-azure-infrastructure-usage.adoc
Jira link: [AAP-3543](https://issues.redhat.com/browse/AAP-3543)
Update the networking section of the Ansible on Azure doc, as the source information has been modified since publication.
Affects /titles/aap-on-azure/
Versions affected
AAP 2.1
=> aap-3543 Fix vnet shape value

downstream/modules/aap-on-azure/con-aap-azure-infrastructure-usage.adoc
Backport 
[PR#339](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/339)
[PR#340](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/340)
=> AAP-3543 Fix vnet shape value(#339)(#340)

downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc, downstream/modules/platform/ref-hub-system-requirements.adoc, downstream/modules/platform/ref-system-requirements.adoc, downstream/titles/hub/install/master.adoc
https://redhat-documentation.github.io/supplementary-style-guide/\#gb
=> Replace all Gb with GB for correctness and per style guide.

downstream/titles/aap-installation-guide/master.adoc, downstream/titles/aap-on-aws/master.adoc, downstream/titles/aap-on-azure/master.adoc, downstream/titles/aap-operator-installation/master.adoc, downstream/titles/analytics/automation-savings-planner/master.adoc, downstream/titles/analytics/automation-savings/master.adoc, downstream/titles/analytics/job-explorer/master.adoc, downstream/titles/analytics/reports/master.adoc, downstream/titles/analytics/user-access/master.adoc, downstream/titles/automation-mesh/master.adoc, downstream/titles/builder/master.adoc, downstream/titles/catalog/getting-started/master.adoc, downstream/titles/central-auth/master.adoc, downstream/titles/controller/master.adoc, downstream/titles/dev-guide/master.adoc, downstream/titles/navigator-guide/master.adoc, downstream/titles/security-guide/master.adoc, downstream/titles/upgrade/master.adoc, downstream/titles/worker-install/master.adoc
Fixes #366 by adding the inclusive language statement from aap-common to downstream titles.
=> resolves #366 inclusive language statement

downstream/modules/platform/con-aap-upgrade-prereq.adoc, downstream/modules/platform/con-why-ee.adoc, downstream/modules/platform/ref-system-requirements.adoc
Added Python requirement to Upgrade/migration guide and
Installation Guide
Add python requirements for AAP into docs
https://issues.redhat.com/browse/AAP-3385
=> Added Python requirement to AAP docs

downstream/modules/platform/con-aap-upgrade-prereq.adoc, downstream/modules/platform/con-why-ee.adoc, downstream/modules/platform/ref-system-requirements.adoc
* Added Python requirement to AAP docs
https://issues.redhat.com/browse/AAP-3385
=> Added Python requirement to AAP docs (#373)

downstream/assemblies/platform/assembly-install-aap-operator.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/attributes/attributes.adoc, downstream/modules/platform/con-storage-options-for-operator-installation-on-ocp.adoc, downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc, downstream/titles/aap-operator-installation/master.html
Backport https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/332 to 2.2
* AAP-2007 Add prereq to Installing Operator on OCP
* AAP-2007 New content about ReadWriteMany access
=> AAP-2007 AAP 2.1 on OCP Pre-Flight Check Documentation (#332)

downstream/modules/platform/proc-controller-route-options.adoc, downstream/modules/platform/proc-operator-external-db-controller.adoc, downstream/modules/platform/proc-operator-external-db-hub.adoc
Changes made for this PR include:
- Added quotes around secret values.
- Added note regarding unique database names in a single PostreSQL instance.
- Changed "Tower ingress type" to "Ingress type"
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/aap2033/master.html
=> AAP2033 - added quotes to secret values & other minor changes

downstream/assemblies/platform/assembly-install-aap-operator.adoc, downstream/modules/platform/proc-install-aap-operator.adoc
Fixes issue #https://issues.redhat.com/browse/AAP-1808
Changes proposed in this pull request:
- Added AWS Storage Class requirements for RWX.
Link to preview (requires VPN):  http://file.rdu.redhat.com/~ddacosta/aapoperator_1808/master.html
=> AAP1808 - Added information for AWS storage class prereq

downstream/modules/platform/proc-install-cli-aap-operator.adoc, downstream/modules/platform/proc-operator-external-db-controller.adoc, downstream/modules/platform/proc-operator-external-db-hub.adoc
* AAP-4426 Updated version #s from 2.1 to 2.2
* AAP-4426 Saved update to version in automation hub
* AAP-4426 Updated PostgreSQL version to 13
=> AAP-4426 Backport changes to 2.2 branch (#380)

downstream/assemblies/platform/assembly-install-aap-operator.adoc, downstream/modules/platform/proc-install-aap-operator.adoc
* AAP1808 - Added information for AWS storage class prereq
* AAP-1808 - minor edits
* AAP1808 - added peer review suggestions
=> AAP1808 - Backport to 2.1 branch (#354)

downstream/modules/platform/proc-controller-route-options.adoc, downstream/modules/platform/proc-operator-external-db-controller.adoc, downstream/modules/platform/proc-operator-external-db-hub.adoc
Backporting changes for PR#349 to the 2.1 branch.
=> AAP2033 - backport changes to 2.1 branch (#349)

downstream/modules/platform/proc-controller-route-options.adoc, downstream/modules/platform/proc-operator-external-db-controller.adoc, downstream/modules/platform/proc-operator-external-db-hub.adoc
Backport changes to the 2.2 branch.
=> AAP2033 - Backport changes to 2.2 branch (#349)

downstream/modules/platform/ref-system-requirements.adoc
Added disk space requirements for disk service node.
Also added requirement for 20 GB to be allocated to /home/awx.
As it was a note I've removed the note for Automation controller and made it
a heading. Less messy that way.
Disk space requirements for EE's not documented
https://issues.redhat.com/browse/AAP-4123
=> Added disk space requirements

downstream/modules/platform/ref-system-requirements.adoc
Backport #409 to `2.1`
[AAP-4123](https://issues.redhat.com/browse/AAP-4123)
=> 2.1 AAP-4123 Added disk space requirements (#409)

downstream/assemblies/platform/assembly-planning-installation.adoc, downstream/modules/platform/ref-access-control-requirements.adoc
Jira: [AAP-1439](https://issues.redhat.com/browse/AAP-1439) 
Preview link available: [1.2 Access control requirements](http://file.rdu.redhat.com/~lmodemal/aap-install-220107-2/master.html)
**Please review Jira issue before commenting on PR.**  
Created new section to include access control requirements for AAP2
Before you review…some background on the tables:
- I’ve implemented feedback from SMEs.
- There are empty cells because I don't have information to insert into that particular cell.
- All of the technical information has been verified by many SMEs.
- Donna helped me keep this table within Accessibility guidelines. Thanks, @dcdacosta!
=> AAP-1439: Add section for Access Control Requirements

downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
Changed title of Section 3.1.4 to reflect the actual content.
Removed AAP from the tile so as not to be too long.
Edited inventory file as per instructions in the ticket.
Typo in the title of 3.1.4 for AAP2  documentation
https://issues.redhat.com/browse/AAP-4678
=> Updated title and inventory file

downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
* Updated title and inventory file
Changed title of Section 3.1.4 to reflect the actual content.
Removed AAP from the tile so as not to be too long.
Edited inventory file as per instructions in the ticket.
Typo in the title of 3.1.4 for AAP2  documentation
https://issues.redhat.com/browse/AAP-4678
* Updated title and inventory file
Addressed comments
Typo in the title of 3.1.4 for AAP2 documentation
https://issues.redhat.com/browse/AAP-4678
=> 2.2 AAP-4678 Updated title and inventory file (#421)

downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
* Updated title and inventory file
Changed title of Section 3.1.4 to reflect the actual content.
Removed AAP from the tile so as not to be too long.
Edited inventory file as per instructions in the ticket.
Typo in the title of 3.1.4 for AAP2  documentation
https://issues.redhat.com/browse/AAP-4678
* Updated title and inventory file
Addressed comments
Typo in the title of 3.1.4 for AAP2 documentation
https://issues.redhat.com/browse/AAP-4678
=> 2.1 AAP-4678 Updated title and inventory file (#421)

downstream/modules/automation-hub/con-offline-token-active.adoc, downstream/titles/hub/getting-started/master.adoc
Created a subsection in AH Getting Started Guide - _1.2 Keeping your offline token active_
Jira issue: [AAP-1972](https://issues.redhat.com/browse/AAP-1972)
Preview link: [Keeping your offline token active](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/352)
=> AAP-1972: Add subsection on active offline token

downstream/modules/automation-hub/con-offline-token-active.adoc, downstream/titles/hub/getting-started/master.adoc
Created a subsection in AH Getting Started Guide - 1.2 Keeping your offline token active
Jira issue: [AAP-1972](https://issues.redhat.com/browse/AAP-1972)
=> 2.1 AAP-1972: Add subsection on active offline token (#352)

downstream/modules/automation-hub/proc-create-synclist.adoc, downstream/modules/platform/ref-system-requirements.adoc
Added list of allowlisted domains and other requirements
Add in the doc from config AAP the domains which need to be whitelisted
https://issues.redhat.com/browse/AAP-4122
=> Added allowlisted domains

downstream/attributes/attributes.adoc
Update attribute for latest OpenShift version to 4.10
Affects attributes file.
=> Update latest OpenShift version to 4.10

downstream/attributes/attributes.adoc
=> 2.2 Update latest OpenShift version to 4.10 (#435)

downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc, downstream/modules/platform/proc-create-a-user.adoc, downstream/modules/platform/proc-create-keycloak-client.adoc, downstream/modules/platform/proc-create-keycloak-instance.adoc, downstream/modules/platform/proc-create-keycloak-realm.adoc, downstream/modules/platform/proc-creating-a-secret.adoc, downstream/modules/platform/proc-determine-hub-route.adoc, downstream/modules/platform/proc-installing-hub-using-operator.adoc, downstream/modules/platform/proc-installing-the-ansible-platform-operator.adoc, downstream/modules/platform/proc-update-rhsso-client.adoc, downstream/titles/aap-operator-installation/master.adoc
Backport #418 to 2.2
Created chapter documenting SSO configuration steps.
AAP-2514
=> 2.2 AAP-2514 Created chapter documenting SSO configuration steps. (#418)

downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc, downstream/modules/platform/proc-create-a-user.adoc, downstream/modules/platform/proc-create-keycloak-client.adoc, downstream/modules/platform/proc-create-keycloak-instance.adoc, downstream/modules/platform/proc-create-keycloak-realm.adoc, downstream/modules/platform/proc-creating-a-secret.adoc, downstream/modules/platform/proc-determine-hub-route.adoc, downstream/modules/platform/proc-installing-hub-using-operator.adoc, downstream/modules/platform/proc-installing-the-ansible-platform-operator.adoc, downstream/modules/platform/proc-update-rhsso-client.adoc, downstream/titles/aap-operator-installation/master.adoc
* Created chapter documenting SSO configuration steps.
AAP-2514
=> 2.1 AAP-2514 Created chapter documenting SSO configuration steps. (#418)

downstream/modules/automation-hub/proc-create-synclist.adoc, downstream/modules/platform/ref-system-requirements.adoc, downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
* Added allowlisted domains
Added list of allowlisted domains and other requirements
Add in the doc from config AAP the domains which need to be whitelisted
https://issues.redhat.com/browse/AAP-4122
* Added allowlisted domains
Corrections and addressed comments
Add in the doc from config AAP the domains which need to be whitelisted
https://issues.redhat.com/browse/AAP-4122
=> 2.2 AAP-4122 Added allowlisted domains (#414)

downstream/attributes/attributes.adoc
Add an attribute for RHSSO to future-proof the AAP docs in case of product name changes.
AAP-4999
=> AAP-4999 Add attribute for RHSSO

downstream/attributes/attributes.adoc
Backports #439  to 2.1
- Add attribute for RHSSO
- Add attribute for RHSSO operator
=> 2.1 AAP-4999 Add attribute for RHSSO (#439)

downstream/attributes/attributes.adoc
Backports #439 to 2.2
* Add attribute for RHSSO
* Add attribute for RHSSO operator
=> 2.2 AAP-4999 Add attribute for RHSSO (#439)

downstream/modules/platform/ref-operator-ocp-version.adoc
Changed platform version to 2.2
Update OpenShift Container Platform version compatibility
https://issues.redhat.com/browse/AAP-4837
=> Update versions to AAP 2.2 and OCP 4.8

downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc, downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
Changed value to 'controller.acme.org'
Change value of automationhub_pg_host
https://issues.redhat.com/browse/AAP-4728
=> AAP-4728 Value of automationhub_pg_host changed

bin/sync_docs.sh, bin/sync_ocp_latest.sh
Fixes issue #448 for the 2.2 branch.
=> [2.2] Add bin folder with sync scripts

CODEOWNERS, bin/sync_common.sh
Fixes issue #448 for the AAP common branch.
=> [AAP common] Add bin folder with sync script

bin/sync_docs.sh
Fixes issue #448 for the 1.2 branch
=> [1.2] Add bin folder with sync scripts

bin/sync_docs.sh
Fixes issue #448 for the 2.0-ea branch
=> [2.0-ea] Add bin folder with sync scripts

bin/sync_docs.sh
Fixes issue #448 for the 2.0 branch
=> [2.0] Add bin folder with sync scripts

bin/sync_cloud_docs.sh, bin/sync_docs.sh, bin/sync_ocp_latest.sh
Fixes issue #448 for the 2.1 branch
=> [2.1] Add bin folder with sync scripts

bin/sync_cloud_docs.sh
Fixes issue #448 for downstream 2.2-cloud branch.
=> [2.2] Add bin folder with cloud content sync script

downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc, downstream/modules/platform/proc-create-a-user.adoc, downstream/modules/platform/proc-create-keycloak-client.adoc, downstream/modules/platform/proc-create-keycloak-instance.adoc, downstream/modules/platform/proc-create-keycloak-realm.adoc, downstream/modules/platform/proc-creating-a-secret.adoc, downstream/modules/platform/proc-determine-hub-route.adoc, downstream/modules/platform/proc-update-rhsso-client.adoc
Replace references to RH Single Sign-On with attribute.
https://issues.redhat.com/browse/AAP-5037
=> AAP-5037 Use attributes for SSO and SSO Operator

downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc, downstream/modules/platform/proc-create-a-user.adoc, downstream/modules/platform/proc-create-keycloak-client.adoc, downstream/modules/platform/proc-create-keycloak-instance.adoc, downstream/modules/platform/proc-create-keycloak-realm.adoc, downstream/modules/platform/proc-creating-a-secret.adoc, downstream/modules/platform/proc-determine-hub-route.adoc, downstream/modules/platform/proc-update-rhsso-client.adoc
Replace references to RH Single Sign-On with attribute.
https://issues.redhat.com/browse/AAP-5037
=> 2.2 AAP-5037 Use attributes for SSO and SSO Operator (#447)

downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc, downstream/modules/platform/proc-create-a-user.adoc, downstream/modules/platform/proc-create-keycloak-client.adoc, downstream/modules/platform/proc-create-keycloak-instance.adoc, downstream/modules/platform/proc-create-keycloak-realm.adoc, downstream/modules/platform/proc-creating-a-secret.adoc, downstream/modules/platform/proc-determine-hub-route.adoc, downstream/modules/platform/proc-update-rhsso-client.adoc
Replace references to RH Single Sign-On with attribute.
https://issues.redhat.com/browse/AAP-5037
=> 2.1 AAP-5037 Use attributes for SSO and SSO Operator (#447)

downstream/modules/automation-hub/proc-set-community-remote.adoc, downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
=> 2.2 Update broken hub link (#470)

downstream/modules/automation-hub/proc-set-community-remote.adoc, downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
=> 2.1 Update broken hub link (#470)

downstream/modules/platform/ref-access-control-requirements.adoc
Jira [AAP-4802](https://issues.redhat.com/browse/AAP-4802) Improve automation mesh access controls
Preview link to [1.2 Access control requirements](http://file.rdu.redhat.com/~lmodemal/aap-installation-guide-220815/master.html)
- Added new column for installer inventory variables
- Added note to clarify what may happen when the user changes the inventory variable or destination port
=> AAP-4802: Add Installer Inventory Variable and note

downstream/modules/platform/ref-access-control-requirements.adoc
Jira [AAP-4802](https://issues.redhat.com/browse/AAP-4802) Improve automation mesh access controls
Preview link to [1.2 Access control requirements](http://file.rdu.redhat.com/~lmodemal/aap-installation-guide-220815/master.html)
- Added new column for installer inventory variables
- Added note to clarify what may happen when the user changes the inventory variable or destination port
=> AAP-4802: Add Installer Inventory Variable and note (#469)

downstream/modules/aap-on-azure/proc-azure-update-route-tables.adoc
Backports #471 and #475 to 2.1
Affects Ansible on Azure guide
AAP-5260
=> 2.1 AAP-5260 Add virtual appliance routing info 

downstream/attributes/attributes.adoc
AAP-5310 
Add an attribute to represent Ansible Galaxy
Backport to 2.1 and 2.2
=> AAP-5310 Add attribute for Ansible Galaxy

downstream/attributes/attributes.adoc
Backports #478  AAP-5310 to 2.1
Add an attribute to represent Ansible Galaxy
=> 2.1 AAP-5310 Add attribute for Ansible Galaxy (#478)

downstream/attributes/attributes.adoc
Backports https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/478 AAP-5310 to 2.2
Add an attribute to represent Ansible Galaxy
=> 2.2 AAP-5310 Add attribute for Ansible Galaxy (#478)

downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc, downstream/assemblies/hub/assembly-synclists.adoc, downstream/modules/automation-hub/con-remote-repos.adoc, downstream/modules/automation-hub/con-rh-certified-synclist.adoc, downstream/modules/automation-hub/proc-create-synclist.adoc, downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc, downstream/modules/automation-hub/proc-set-community-remote.adoc, downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
Add attributes and correct accessibility options
https://issues.redhat.com/browse/AAP-5297
Affects `titles/hub/configuring-private-hub-rh-certified`: 'Managing Red Hat Certified and Ansible Galaxy collections in Automation Hub'
=> AAP-5297 Added attributes and corrected accessibility options

downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc, downstream/assemblies/hub/assembly-synclists.adoc, downstream/modules/automation-hub/con-remote-repos.adoc, downstream/modules/automation-hub/con-rh-certified-synclist.adoc, downstream/modules/automation-hub/proc-create-synclist.adoc, downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc, downstream/modules/automation-hub/proc-set-community-remote.adoc, downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
* Added attributes and corrected accessibility options
https://issues.redhat.com/browse/AAP-5297
Backports #483
=> 2.1 AAP-5297 Added attributes and corrected accessibility options (#483)

downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc, downstream/assemblies/hub/assembly-synclists.adoc, downstream/modules/automation-hub/con-remote-repos.adoc, downstream/modules/automation-hub/con-rh-certified-synclist.adoc, downstream/modules/automation-hub/proc-create-synclist.adoc, downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc, downstream/modules/automation-hub/proc-set-community-remote.adoc, downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
* Added attributes and corrected accessibility options
https://issues.redhat.com/browse/AAP-5297
Backports #483 to 2.2
=> 2.2 AAP-5297 Added attributes and corrected accessibility options (#483)

downstream/assemblies/platform/assembly-multi-machine-cluster-scenario.adoc, downstream/assemblies/platform/assembly-planning-installation.adoc
Change intallation to installation
Error in title.
https://issues.redhat.com/browse/AAP-5366
=> AAP-5366 Corrected spelling error

downstream/assemblies/platform/assembly-multi-machine-cluster-scenario.adoc, downstream/assemblies/platform/assembly-planning-installation.adoc
Fix error in title.
https://issues.redhat.com/browse/AAP-5366
=> 2.2 AAP-5366 Corrected spelling error (#496)

downstream/assemblies/platform/assembly-multi-machine-cluster-scenario.adoc, downstream/assemblies/platform/assembly-planning-installation.adoc
Fix error in title.
https://issues.redhat.com/browse/AAP-5366
=> 2.1 AAP-5366 Corrected spelling error (#496)

downstream/assemblies/platform/assembly-planning-installation.adoc, downstream/modules/platform/proc-choosing-obtaining-installer.adoc
Jira: [AAP-3713](https://issues.redhat.com/browse/AAP-3713)
- Added rpm install instructions.
- Reordered _**Choosing and obtaining a Red Hat Ansible Automation Platform installer**_ section to go after the _**Attaching your Red Hat Ansible Automation Platform subscription**_ section.
=> AAP-3713: New installable RPM

downstream/modules/platform/proc-choosing-obtaining-installer.adoc
Jira: [AAP-3713](https://issues.redhat.com/browse/AAP-3713)
Added information about where the files will be located once RPM is used.
=> AAP-3713-Revised: Add directory info

downstream/modules/platform/proc-choosing-obtaining-installer.adoc
Jira: [AAP-3713](https://issues.redhat.com/browse/AAP-3713)
Added information about where the files will be located once RPM is used.
Affects installation guide
=> [2.2] AAP-3713-Revised: Add directory info (509)

downstream/modules/platform/proc-migrate-playbooks-roles.adoc
Correct platform version
https://issues.redhat.com/browse/AAP-5544
=> Corrected platform version

downstream/modules/platform/proc-migrate-playbooks-roles.adoc
Correct platform version
https://issues.redhat.com/browse/AAP-5544
=> Corrected platform version (#517)

downstream/modules/platform/ref-complex-mesh-topology.adoc
typo in the automation mesh guide
https://issues.redhat.com/browse/AAP-5528
=> Corrected typo

downstream/modules/builder/proc-customize-ee-image.adoc
Ansible-builder documentation references aap2.0-ea
https://issues.redhat.com/browse/AAP-5355
=> AAP-5355 Updated builder to use AAP 2.1 EE image

downstream/modules/builder/proc-customize-ee-image.adoc
Ansible-builder documentation references aap2.0-ea
https://issues.redhat.com/browse/AAP-5355
=> AAP-5355 Updated builder to use AAP 2.2 EE image

downstream/modules/builder/proc-customize-ee-image.adoc
Ansible-builder documentation references aap2.0-ea AAP-5355
=> AAP-5355 Updated builder to use AAP 2.2 EE image (#525)

downstream/attributes/attributes.adoc
Add atttribute for console.redhat.com
https://issues.redhat.com/browse/AAP-5740
=> AAP-5740 Add attribute for console.redhat.com

downstream/modules/automation-hub/proc-configure-ansible-galaxy-cli-verify.adoc
Fix linebreaks in AAP-2844 (#493)
=> AAP-2844 Fix linebreaks

downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
* Updated navigator installation method
=> Updated navigator installation method (#461)

downstream/assemblies/central-auth/assembly-central-auth-group-perms.adoc
It looks like most have been corrected at some other time. There was only one issue listed that remained to be fixed.
Correct Content Structure Issues
https://issues.redhat.com/browse/AAP-4207
=> Corrected Structure Issues

downstream/assemblies/central-auth/assembly-central-auth-group-perms.adoc
It looks like most have been corrected at some other time. There was only one issue listed that remained to be fixed.
Correct Content Structure Issues
https://issues.redhat.com/browse/AAP-4207
=> Corrected Structure Issues (#543)

downstream/attributes/attributes.adoc
Create certified content attributes
https://issues.redhat.com/browse/AAP-5978
=> Added new attributes

downstream/attributes/attributes.adoc
* Added new attributes Create certified content attributes
Added a further attribute for automation hub
AAP-5978
Correcting merge errors
=> [2.1] Added new attributes (#548)

downstream/attributes/attributes.adoc
* Added new attributes Create certified content attributes
Added a further attribute for automation hub
AAP-5978
=> [2.2] Added new attributes (#548)

downstream/attributes/attributes.adoc
Change AAP on AWS attribtes, replacing them with an attribute for AWS and one for GCP
Change to AAP on Clouds attributes
https://issues.redhat.com/browse/AAP-6298
=> Update attributes for cloud

downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-1758.
Changes in this pull request include:
Added info to set automationhub_upgrade=true in section titled "Setting up the inventory file"
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP1758/master.html
=> AAP-1758 added note to set automationhub_upgrade flag to true

downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/platform/proc-access-hub-operator-ui.adoc
This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-3678.
Changes in this pull request include:
Added info for locating the admin password to the procedure in Section 3.2.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP3678/master.html
=> AAP-3678 - Added note for locating admin password

downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/platform/proc-access-hub-operator-ui.adoc
* AAP-3678 - Added note for locating admin password
=> AAP-3678 - Added note for locating admin password (#549)

downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/platform/proc-access-hub-operator-ui.adoc
* AAP-3678 - Added note for locating admin password
=> Backport AAP-3678 - Added note for locating admin password (#549)

downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Backporting changes from PR 556 to the v2.2 branch.
=> Backport - AAP-1758 added note to set automationhub_upgrade flag to true (#556)

downstream/modules/platform/proc-install-aap-operator.adoc
Backport changes for AAP-3675 in PR#494 to the v2.2 branch
=> AAP-3675 - added information describing update channels (#494)

downstream/modules/platform/proc-install-aap-operator.adoc
Backports #575 to 2.1
Affects operator guide
* Minor last minute correction to AAP-3675
* AAP-3675A - Fixed description of stable-2.x channel
=> 2.1 Minor last minute correction to AAP-3675 (#575)

downstream/assemblies/builder/assembly-building-off-existing-ee.adoc, downstream/assemblies/builder/assembly-definition-file-breakdown.adoc, downstream/assemblies/builder/assembly-intro-to-builder.adoc, downstream/assemblies/builder/assembly-publishing-exec-env.adoc, downstream/assemblies/builder/assembly-using-builder.adoc, downstream/assemblies/hub/assembly-pull-image.adoc, downstream/assemblies/hub/assembly-setup-container-repository.adoc, downstream/modules/automation-hub/proc-add-group-to-container-repo.adoc, downstream/modules/automation-hub/proc-obtain-images.adoc, downstream/modules/automation-hub/proc-pull-image.adoc, downstream/modules/automation-hub/proc-push-container.adoc, downstream/modules/automation-hub/proc-tag-pulled-image.adoc, downstream/modules/builder/con-about-builder.adoc, downstream/modules/builder/con-about-ee.adoc, downstream/modules/builder/con-additional-custom-build-steps.adoc, downstream/modules/builder/con-ansible-config-file-path.adoc, downstream/modules/builder/con-building-definition-file.adoc, downstream/modules/builder/con-container_file.adoc, downstream/modules/builder/con-definition-dependencies.adoc, downstream/modules/builder/con-ee-precedence.adoc, downstream/modules/builder/con-optional-build-command-arguments.adoc, downstream/modules/builder/con-why-builder.adoc, downstream/modules/builder/con-why-ee.adoc, downstream/modules/builder/proc-customize-ee-image.adoc, downstream/modules/builder/proc-installing-builder.adoc, downstream/modules/builder/proc-pull-protected-registry.adoc, downstream/modules/builder/ref-build-args-base-image.adoc, downstream/titles/builder/docinfo.xml, downstream/titles/builder/hub, downstream/titles/builder/master.adoc
Backport #417 to 2.2
Affects `/titles/builder/`
=> 2.2 AAP-4364 - Restructure Builder Guide to create new EE Guide (#417)

downstream/assemblies/platform/assembly-aap-migration.adoc, downstream/assemblies/platform/assembly-operator-upgrade.adoc, downstream/modules/platform/con-aap-migration-considerations.adoc, downstream/modules/platform/con-aap-migration-prepare.adoc, downstream/modules/platform/con-aap-migration-prereqs.adoc, downstream/modules/platform/con-ocp-supported-install.adoc, downstream/modules/platform/con-operator-upgrade-considerations.adoc, downstream/modules/platform/con-operator-upgrade-prereq.adoc, downstream/modules/platform/proc-aap-create_controller.adoc, downstream/modules/platform/proc-aap-create_hub.adoc, downstream/modules/platform/proc-aap-migration-backup.adoc, downstream/modules/platform/proc-aap-migration.adoc, downstream/modules/platform/proc-create-postresql-secret.adoc, downstream/modules/platform/proc-create-secret-key-secret.adoc, downstream/modules/platform/proc-find-delete-PVCs.adoc, downstream/modules/platform/proc-install-aap-operator.adoc, downstream/modules/platform/proc-operator-upgrade.adoc, downstream/modules/platform/proc-post-migration-cleanup.adoc, downstream/modules/platform/proc-verify-network-connectivity.adoc, downstream/titles/aap-operator-installation/docinfo.xml, downstream/titles/aap-operator-installation/master.adoc
Backports  #460  and #586  to 2.2
* AAP-2336 - Created topics for Migration & Upgrade of Operator on OCP
Affects `titles/aap-operator-installation/`
=> 2.2 AAP-2336 - Created topics for Migration & Upgrade of Operator on OCP

downstream/assemblies/platform/assembly-planning-installation.adoc, downstream/modules/platform/ref-platform-components.adoc
Added individual summaries of platform components
Outline individual platform components
https://issues.redhat.com/browse/AAP-2162
=> Add summary of platform components

downstream/assemblies/platform/assembly-planning-installation.adoc, downstream/modules/platform/ref-platform-components.adoc
* Add summary of platform components AAP-2162
=> AAP-2162 Add summary of platform components (#582)

downstream/modules/platform/con-declaring-variables.adoc, downstream/modules/platform/con-inventory-variables-intro.adoc
Correct minor errors in new inventory file section.
Correct minor errors in Section 1.6 of the Installation Guide
https://issues.redhat.com/browse/AAP-6772
=> Correct minor errors

downstream/modules/platform/con-declaring-variables.adoc, downstream/modules/platform/con-inventory-variables-intro.adoc
Correct minor errors in new inventory file section.
Correct minor errors in Section 1.6 of the Installation Guide
https://issues.redhat.com/browse/AAP-6772
=> Correct minor errors (#595)

downstream/modules/platform/ref-hub-variables.adoc
Removed variable automationhub_upgrade
Remove automationhub_upgrade variable from appendix.
https://issues.redhat.com/browse/AAP-6766
=> Removed automationhub variable

downstream/modules/platform/ref-hub-variables.adoc
Removed variable automationhub_upgrade
Remove automationhub_upgrade variable from appendix.
https://issues.redhat.com/browse/AAP-6766
=> Removed automationhub variable (#600)

downstream/modules/platform/ref-hub-variables.adoc
Updated definition of automationhub_main_url
Update variable definition
https://issues.redhat.com/browse/AAP-6810
=> Updated variable definition (#604)

downstream/assemblies/hub/assembly-collections-and-content-signing-in-pah.adoc, downstream/modules/automation-hub/proc-downloading-signature-public-keys.adoc
Jira: [AAP-4928](https://issues.redhat.com/browse/AAP-4928)
- New section on how to download public key from automation hub UI.
- Draft in [google doc](https://docs.google.com/document/d/1LwNRNryZlf_3ygAXG3jQQYxE9qkwLhisFOXifSIZ6x0/edit#)
=> AAP-4928: Show how to download public key in AH UI

downstream/assemblies/hub/assembly-collections-and-content-signing-in-pah.adoc, downstream/modules/automation-hub/proc-downloading-signature-public-keys.adoc
Jira: [AAP-4928](https://issues.redhat.com/browse/AAP-4928)
New section on how to download public key from automation hub UI.
Draft in [google doc](https://docs.google.com/document/d/1LwNRNryZlf_3ygAXG3jQQYxE9qkwLhisFOXifSIZ6x0/edit#)
=> AAP-4928: Show how to download public key in AH UI (#618)

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc, downstream/assemblies/platform/assembly-platform-install-scenario.adoc, downstream/titles/aap-installation-guide/master.adoc
Backporting AAP-6953 (PR 624) "Added important note to Chapter 2 of 2.2 Installation Guide" to 2.2
=> AAP-6953 Backport 2.2 624

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc, downstream/assemblies/platform/assembly-platform-install-scenario.adoc, downstream/titles/aap-installation-guide/master.adoc
Backporting AAP-6953 (PR 624) "Added important note to Chapter 2 of 2.2 Installation Guide" to 2.3
=> Backport AAP-6953 added 'Important' note (#624)

release-notes/master.adoc, release-notes/topics/aap-213.adoc
This PR addresses JIRA issue [AAP-5413](https://issues.redhat.com/browse/AAP-5413).
Following are the changes:
- Added platform and hub release notes for AAP 2.1.3
Author: sayjadha
=> AAP-5413: Created AAP 2.1.3 release notes

downstream/modules/platform/ref-single-node-inventory.adoc, downstream/modules/platform/ref-standalone-controller-ext-db.adoc
Replaced 127.0.0.1 with controller.example.com
Update the documentation
https://issues.redhat.com/browse/AAP-7097
=> Replaced IP address with FQDN

downstream/modules/platform/ref-single-node-inventory.adoc, downstream/modules/platform/ref-standalone-controller-ext-db.adoc
* Replaced IP address with FQDN https://issues.redhat.com/browse/AAP-7097
=> Replaced IP address with FQDN (#634)

downstream/modules/platform/proc-choosing-obtaining-installer.adoc
changed rpm to rpms
various installation issues
https://issues.redhat.com/browse/AAP-6988
=> Corrected rpm install command

release-notes/master.adoc, release-notes/topics/aap-221.adoc
This PR addresses JIRA issue [AAP-5414](https://issues.redhat.com/browse/AAP-5414).
Following are the changes:
- Added platform and hub release notes for AAP 2.2.1
Author: sayjadha
=> AAP-5414: Created AAP 2.2.1 release notes

release-notes/docinfo.xml, release-notes/master.adoc, release-notes/master.html, release-notes/topics/aap-23.adoc, release-notes/topics/catalog-11-2022.adoc, release-notes/topics/controller-430.adoc, release-notes/topics/hub-460.adoc, release-notes/topics/operator-230.adoc, release-notes/topics/platform-intro.adoc
Updated the following files for 2.3 release notes:
- docinfo.xml
- master.adoc
- platform-intro.adoc
Added new files:
- aap-23.adoc
- controller-430.adoc
- hub-460.adoc
- operator-230.adoc
- catalog-11-2022.adoc (commented this one out for now because there were no release notes related to this component)
=> AAP 5059 Release notes for AAP 2.3

downstream/titles/aap-installation-guide/docinfo.xml, downstream/titles/aap-operator-backup/docinfo.xml, downstream/titles/aap-operator-installation/docinfo.xml, downstream/titles/analytics/automation-savings-planner/docinfo.xml, downstream/titles/analytics/automation-savings/docinfo.xml, downstream/titles/analytics/job-explorer/docinfo.xml, downstream/titles/analytics/reports/docinfo.xml, downstream/titles/automation-mesh/docinfo.xml, downstream/titles/builder/docinfo.xml, downstream/titles/catalog/getting-started/docinfo.xml, downstream/titles/catalog/itsm-integration/docinfo.xml, downstream/titles/catalog/support-matrix/docinfo.xml, downstream/titles/central-auth/docinfo.xml, downstream/titles/dev-guide/docinfo.xml, downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml, downstream/titles/hub/getting-started/docinfo.xml, downstream/titles/hub/high-availability/docinfo.xml, downstream/titles/hub/install/docinfo.xml, downstream/titles/hub/lifecycle/docinfo.xml, downstream/titles/hub/manage-containers/docinfo.xml, downstream/titles/hub/managing-user-access/docinfo.xml, downstream/titles/hub/publishing-internal-content/docinfo.xml, downstream/titles/hub/uploading-collections/docinfo.xml, downstream/titles/hub/uploading-internal-collections/docinfo.xml, downstream/titles/navigator-guide/docinfo.xml, downstream/titles/security-guide/docinfo.xml, downstream/titles/upgrade/docinfo.xml, downstream/titles/worker-install/docinfo.xml, release-notes/docinfo.xml
Update the release number in the docinfo.xml files for the 2.3 docs.
=> Update release in docinfo files to 2.3

release-notes/docinfo.xml, release-notes/master.adoc, release-notes/master.html, release-notes/topics/aap-23.adoc, release-notes/topics/catalog-11-2022.adoc, release-notes/topics/controller-430.adoc, release-notes/topics/hub-460.adoc, release-notes/topics/operator-230.adoc, release-notes/topics/platform-intro.adoc
Updated the following files for 2.3 release notes:
- docinfo.xml
- master.adoc
- platform-intro.adoc
Added new files:
- aap-23.adoc
- controller-430.adoc
- hub-460.adoc
- operator-230.adoc
=> Backport-2.3-632 AAP 2.3 Release notes (based on AAP-5059, PR #632)

downstream/attributes/attributes.adoc
Update the attribute for the current AAP version to 2.3
=> Update PlatformVers attribute

downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc, downstream/modules/platform/proc-accessing-rpm-repositories-for-locally-mounted-dvd.adoc, downstream/modules/platform/proc-completing-post-installation-tasks.adoc, downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc, downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
Fixed several link formatting issues.. Cleaned up some paragraph structures by deleting forced returns, and ensured several stray formatting marks were removed.
=> Fixed formatting and spacing issues

downstream/modules/core/con-execution-environments.adoc, downstream/modules/dev-guide/con-content-workflows.adoc
* AAP-357 added links to builder and navigator guides
* AAP-357 updated additions
* AAP-357 updated doc
* AAP-357 updated doc
* AAP-357 updated doc post-peer review
* AAP-357 updated core/con-execution-environments post peer-review
=> AAP-357 added links to builder and navigator guides (#656)

downstream/assemblies/platform/assembly-aap-migration.adoc
Affects /titles/aap-operator-installation/
AAP-7480 Fix release number for OpenShift Ansible Tower version
=> 2.2 AAP-7480 Update OpenShift Ansible Tower version (#670)

downstream/assemblies/platform/assembly-planning-installation.adoc, downstream/modules/platform/con-editing-inventory-files.adoc, downstream/modules/platform/ref-automation-hub-requirements.adoc, downstream/modules/platform/ref-controller-system-requirements.adoc, downstream/modules/platform/ref-guidelines-hosts-groups.adoc, downstream/modules/platform/ref-postgresql-requirements.adoc, downstream/modules/platform/ref-system-requirements.adoc
Docathon: Reordering and rearranging sections 1.1 to 1.6
Create New Content for Introduction to Red Hat Automation Platform Installation Guide Chapter One (Sections 1.1-1.6)
https://issues.redhat.com/browse/AAP-7531
=> AAP-7531 Docathon  Reordering and rearranging sections

downstream/modules/platform/con-websocket-setup.adoc, downstream/modules/platform/proc-configuring-discovery.adoc
Updates to sub-chapters 2.1 (downstream/modules/platform/con-websocket-setup.adoc and 2.1.1 (downstream/modules/platform/proc-configuring-discovery.adoc)
=> AAP-7534B Updates to Chapter 2 of new Operations guide

release-notes/master.adoc, release-notes/master.html, release-notes/topics/docs-23.adoc
This PR addresses the changes for https://issues.redhat.com/browse/AAP-7602.
Changes include the following:
- Add details about Install Guide Restructuring
- Add details about renaming Red Hat Ansible Automation Platform Operator Installation Guide and the addition of migration and upgrade details.
- Add details about new Red Hat Ansible Automation Platform Operator Backup and Recovery Guide
- Add details about renaming Red Hat Ansible Builder Guide.
=> AAP-7602 Release Notes update for major doc changes

downstream/modules/platform/ref-automation-hub-requirements.adoc
Added extra column and removed entries that are included in general system requirements
Correct table in Planning Guide
https://issues.redhat.com/browse/AAP-7672
=> Corrected table (#695)

downstream/modules/platform/con-editing-inventory-files.adoc
Added link to appendic in installation guide
Update reference to Inventory file appendix
https://issues.redhat.com/browse/AAP-7715
=> Added cross reference

downstream/modules/platform/con-editing-inventory-files.adoc
Added link to appendix in installation guide
https://issues.redhat.com/browse/AAP-7715
=> Add cross reference from planning guide to install guide (#698)

.gitignore
Add release notes HTML files to `.gitignore`
=> Add release notes HTML files to .gitignore

release-notes/master.adoc, release-notes/master.html, release-notes/topics/docs-23.adoc
Backports #691 to 2.3
Affects `/release-notes`
* AAP-7602 Release Notes update for major doc changes
* AAP-7602 Add title change for Ansible Builder Guide
=> 2.3 AAP-7602 Release Notes update for major doc changes (#691)

downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc, downstream/modules/platform/con-aap-installation-on-disconnected-rhel.html, downstream/modules/platform/proc-accessing-rpm-repositories-for-locally-mounted-dvd.adoc, downstream/modules/platform/proc-completing-post-installation-tasks.adoc, downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc, downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
Backports #660 to 2.3
Affects modules in disconnected installation chapter of `/titles/aap-installation-guide`
=> 2.3 Fixed formatting and spacing issues (#660)

downstream/assemblies/platform/assembly-platform-install-overview.adoc, downstream/assemblies/platform/assembly-platform-install-scenario.adoc, downstream/assemblies/platform/assembly-platform-whats-next.adoc, downstream/modules/platform/con-aap-installation-prereqs.adoc, downstream/modules/platform/con-why-automation-mesh.adoc, downstream/modules/platform/con-why-migrate-ansible-29.adoc, downstream/modules/platform/con-why-migrate-ansible-core-212.adoc, downstream/modules/platform/con-why-migrate-ansible-core-213.adoc, downstream/modules/platform/con-why-migrate-venvs-ee.adoc, downstream/modules/platform/proc-verify-controller-installation.adoc, downstream/modules/platform/proc-verify-hub-installation.adoc, downstream/modules/platform/ref-controller-configs.adoc, downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc, downstream/modules/platform/ref-hub-configs.adoc
This PR backports the changes for PR#704. 
IG-LINKFIX - changed hardcoded 2.3 in links to the PlatformVers attribute
=> Backport-PR704 - changed hardcoded 2.3 in links to the PlatformVers (#704)

downstream/modules/platform/con-aap-installation-prereqs.adoc
Corrected link
Wrong link towards Red Hat Ansible Automation Platform system requirements
https://issues.redhat.com/browse/AAP-7804
=> Updated link in installation guide

downstream/modules/automation-hub/con-ha-hub-installation.adoc
Updated description of automatinhub_main_url
[Doc BUG] : Update automationhub_main_url description.
https://issues.redhat.com/browse/AAP-7805
=> Corrected description

downstream/modules/automation-hub/con-ha-hub-installation.adoc
Updated description of automatinhub_main_url
[Doc BUG] : Update automationhub_main_url description.
https://issues.redhat.com/browse/AAP-7805
=> Corrected description (#714)

downstream/assemblies/platform/assembly-installing-aap-components.adoc, downstream/assemblies/platform/assembly-platform-ext-database-install.adoc, downstream/assemblies/platform/assembly-platform-non-inst-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-non-inst-database-installation.adoc, downstream/assemblies/platform/assembly-standalone-hub-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-hub-non-inst-database.adoc, downstream/attributes/attributes.adoc, downstream/modules/platform/con-aap-installation-prereqs.adoc
This PR addresses the changes required by https://issues.redhat.com/browse/AAP-7802.
Changes include the following:
Created a new attribute {PlatformDownloadURL} to ensure the latest version of the product download page is linked.
Updated links in modules to use the new attribute.
=> AAP-7802 - Created attribute to current product download page.

downstream/assemblies/platform/assembly-installing-aap-components.adoc, downstream/assemblies/platform/assembly-platform-ext-database-install.adoc, downstream/assemblies/platform/assembly-platform-non-inst-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-controller-non-inst-database-installation.adoc, downstream/assemblies/platform/assembly-standalone-hub-ext-database.adoc, downstream/assemblies/platform/assembly-standalone-hub-non-inst-database.adoc, downstream/attributes/attributes.adoc, downstream/modules/platform/con-aap-installation-prereqs.adoc
This PR backports the changes required by AAP-7802 from PR#708 to the 2.3 branch.
=> Backport PR708 - Created attribute to current product download page. (#708)

downstream/modules/platform/proc-choosing-obtaining-installer.adoc
* Corrected Platform version
Changed AAP version from 2.2 to 2.3
Upgrade Docs for AAP 2.3 not fully updated
https://issues.redhat.com/browse/AAP-7332
* Corrected Platform version
Updated RHEL supported version
Upgrade Docs for AAP 2.3 not fully updated
https://issues.redhat.com/browse/AAP-7332
=> Corrected Platform version (#726)

downstream/modules/automation-hub/con-ha-hub-installation.adoc
Updated feld to variable, and changed variable name
Doc BUG] : Update automationhub_main_url description.
https://issues.redhat.com/browse/AAP-7805
=> Updated automationhub information

downstream/modules/automation-hub/con-ha-hub-installation.adoc
* Updated automationhub information Updated field to variable, and changed variable name https://issues.redhat.com/browse/AAP-7805
=> 2.3 Updated automationhub information (#728)

downstream/modules/automation-hub/con-ha-hub-installation.adoc
Moved the code format tick mark to the correct place
Change text from code format
https://issues.redhat.com/browse/AAP-8039
=> Changed text format

downstream/assemblies/hub/assembly-installing-high-availability-hub.adoc
Corrected typo
Correct typo
https://issues.redhat.com/browse/AAP-8070
=> Corrected typo (#732)

downstream/modules/builder/proc-installing-builder.adoc
This PR addresses the changes for https://issues.redhat.com/browse/AAP-2948.
=> Updated Ansible Builder install steps, per AAP-2948

downstream/modules/builder/proc-installing-builder.adoc
Co-authored-by: Jameria Self <jself@redhat.com>
This PR backports the changes for PR#737 to the 2.3 branch.
=> Backport - Updated Ansible Builder install steps, per AAP-2948 (#737)

downstream/modules/platform/ref-operator-ocp-version.adoc
This PR addresses the changes required by https://issues.redhat.com/browse/AAP-7408.
Changes include the following:
- Updated the AAP and OCP Versions numbers under 1.2. OpenShift Container Platform version compatibility
- Added link to Support Matrix information under Additional resources in the same section
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP7408/master.html
=> AAP-7408 Updated OCP/AAP compatibility information &  added link

downstream/modules/platform/proc-editing-inventory-file.adoc
This PR backports the changes from PR747 to the 2.3 branch.
=> Backport - AAP-7625 - added information for RPM installed package (#747)

downstream/modules/platform/proc-verify-network-connectivity.adoc
=> AAP-8273 Updated postgresql version from 12 to 13.

downstream/modules/platform/ref-operator-ocp-version.adoc
This PR backports the changes for PR694 to the 2.3 branch.
=> Backport - AAP-7408 Updated OCP/AAP compatibility information &  added link (#694)

downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Wrong database guidelines have been corrected in the Planning Guide.
=> AAP-8071 Wrong database guidelines have been updated in  planning guide

downstream/assemblies/platform/assembly-aap-troubleshoot-backup-recovery.adoc, downstream/modules/platform/proc-aap-controller-restore.adoc, downstream/modules/platform/proc-troubleshoot-same-name.adoc, downstream/titles/aap-operator-backup/master.adoc
This PR backports the changes from PR738 to the 2.3 branch. Change includes:
* AAP-7610 Added troubleshooting topic and included procedure
Affects `/titles/aap-operator-backup`
=> Backport - AAP-7610 Added troubleshooting topic and included procedure (#738)

downstream/snippets/external-site-disclaimer.adoc
Backports #760 to 2.3:
* Add disclaimer for links to external sites
* Add symlink command to disclaimer snippet
=> 2.3 Add disclaimer for links to external sites (#760)

downstream/modules/builder/proc-installing-builder.adoc
Changes made under [PR 719](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/719) as per [AAP-6697](https://issues.redhat.com/browse/AAP-6697). 
Backporting to 2.2.
=> AAP-6697 updated verification step

downstream/modules/builder/proc-installing-builder.adoc
=> Fix RPM version

downstream/modules/platform/con-inventory-introduction.adoc, downstream/modules/platform/ref-ansible-inventory-variables.adoc, downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-general-inventory-variables.adoc, downstream/modules/platform/ref-guidelines-hosts-groups.adoc, downstream/modules/platform/ref-hub-variables.adoc, downstream/modules/platform/ref-sso-variables.adoc
=> Changes to inventory file content 

downstream/modules/platform/con-inventory-introduction.adoc, downstream/modules/platform/ref-ansible-inventory-variables.adoc, downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-general-inventory-variables.adoc, downstream/modules/platform/ref-guidelines-hosts-groups.adoc, downstream/modules/platform/ref-hub-variables.adoc, downstream/modules/platform/ref-sso-variables.adoc
* Corrections to inventory variables tables
Minor corrections and deprecated and unnecessary ansible variables removed.
Add a reference with all variables for inventory setup.sh https://issues.redhat.com/browse/AAP-1389
Amendments to tables and text in Planning Guide.
Add a reference with all variables for inventory setup.sh
=> Changes to inventory file content  (#769)

downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
Addendum to [AAP-7870](https://issues.redhat.com/browse/AAP-7870), PR [717](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/717): fixed git merge conflict within upstream/2.3.
=> AAP-7870A fixed git merge conflict in 2.3

downstream/assemblies/platform/assembly-inventory-introduction.adoc
Added files missed in rearrangement
Content missing from document
https://issues.redhat.com/browse/AAP-8550
Affects planning guide.
=> Re-added modules to inventory file chapter

downstream/assemblies/platform/assembly-inventory-introduction.adoc
Added files missed in rearrangement
https://issues.redhat.com/browse/AAP-8550
=> Re-added modules to inventory file chapter (#773)

downstream/modules/platform/ref-automation-hub-requirements.adoc
Added information on use of autumationhub_main_url
Add parameter to tell PAH which FQDN to use
https://issues.redhat.com/browse/AAP-4952
Affects `/titles/aap-planning-guide/`
=> Added installation note for private hub

downstream/modules/platform/ref-automation-hub-requirements.adoc
Added information on use of automationhub_main_url Add parameter to tell PAH which FQDN to use
https://issues.redhat.com/browse/AAP-4952
=> Added installation note for private hub (#740)

downstream/titles/catalog/getting-started/master.adoc
removed role from table 3.1
[Doc Bug] : Update user access for automation services catalog section.
https://issues.redhat.com/browse/AAP-7861
=> Removed Organization Administrator role

downstream/titles/catalog/getting-started/master.adoc
* Removed Organization Administrator role
removed role from table 3.1
[Doc Bug] : Update user access for automation services catalog section.
https://issues.redhat.com/browse/AAP-7861
* Removed Organization Administrotor role
Removed [Important] admonition
[Doc Bug] : Update user access for automation services catalog section.
https://issues.redhat.com/browse/AAP-7861
=> Removed Organization Administrator role (#718)

release-notes/topics/platform-intro.adoc
AAP-5780
Affects release notes.
Link to lifecycle page from the release notes.
=> AAP-5780 Add link to lifecycle page from release notes intro

release-notes/master.html, release-notes/topics/aap-23.adoc, release-notes/topics/platform-intro.adoc
This PR addresses the changes required by https://issues.redhat.com/browse/AAP-7858.
Changes include:
- Added a description of Technology previews to the RN Intro section
- Added a subheading titled Technology preview features under the AAP 2.3 section and moved all tech preview bullets to that section
- Added Additional resources and links to the AAP 2.3 section that links to the tech preview description and to the documentation for Openshift Deplooyments.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP7858/master.html
=> AAP-7858 - added information re tech preview features

release-notes/master.html, release-notes/topics/aap-23.adoc, release-notes/topics/platform-intro.adoc
This PR backports the changes from PR 725 to the 2.3 branch and includes the following:
* AAP-7858 - added information re tech preview features
* AAP-7858 - updates based on SME feedback
* AAP-7858 - made corrections identified in peer review
=> [Backport] - AAP-7858 - added information re tech preview features (#725)

downstream/modules/platform/con-alternative-capacity-limits.adoc, downstream/modules/platform/ref-container-resource-requirements.adoc
Small changes to document based on SME's edits
Corrections to Performance Considerations document
https://issues.redhat.com/browse/AAP-8737
=> Corrections to OCP Performance doc

downstream/modules/platform/con-alternative-capacity-limits.adoc, downstream/modules/platform/ref-container-resource-requirements.adoc
* Corrections to OCP Performance doc
Small changes to document based on SME's edits
Corrections to Performance Considerations document
https://issues.redhat.com/browse/AAP-8737
* Corrections to OCP Performance doc
Addressed comment
Corrections to Performance Considerations document
https://issues.redhat.com/browse/AAP-8737
=> Corrections to OCP Performance doc (#791)

release-notes/topics/platform-intro.adoc
AAP-5780. Backports #785 to 2.1
Affects release notes.
Link to lifecycle page from the release notes.
=> 2.1 AAP-5780 Add link to lifecycle page from release notes intro (#785)

release-notes/topics/platform-intro.adoc
AAP-5780
Affects release notes.
Link to lifecycle page from the release notes.
=> 2.2 AAP-5780 Add link to lifecycle page from release notes intro (#785)

downstream/assemblies/platform/assembly-installing-controller-operator.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/aap-on-azure/proc-azure-update-route-tables.adoc, downstream/modules/analytics/con-jobs-explorer.adoc, downstream/modules/analytics/proc-add-roles-to-group.adoc, downstream/modules/analytics/proc-add-user-to-group.adoc, downstream/modules/analytics/proc-create-groups.adoc, downstream/modules/analytics/proc-create-savings-plan.adoc, downstream/modules/analytics/proc-edit-savings-plan.adoc, downstream/modules/analytics/proc-filter-plans.adoc, downstream/modules/analytics/proc-link-plan-job-template.adoc, downstream/modules/analytics/proc-view-failed-jobs-detail.adoc, downstream/modules/automation-hub/proc-add-user-to-group.adoc, downstream/modules/automation-hub/proc-assigning-permissions.adoc, downstream/modules/automation-hub/proc-create-groups.adoc, downstream/modules/automation-hub/ref-permissions.adoc, downstream/modules/platform/proc-configuring-reverse-proxy.adoc, downstream/modules/platform/proc-enable-proxy-support.adoc, downstream/modules/platform/proc-restore-aap-backup.adoc
Per [AAP-4208](https://issues.redhat.com/browse/AAP-4208), changes made to accessibility formatting (PR 2/2)
See [PR 761](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/761) for PR 1/2.
=> AAP-4208A updated accessibility formatting

downstream/modules/automation-hub/proc-edit-namespace.adoc
Fix images path in modules/hub/proc-edit-namespace.adoc
=> Fix images path in hub module

downstream/modules/automation-hub/proc-edit-namespace.adoc
Backport #807 to 2.3
Fix images path in modules/hub/proc-edit-namespace.adoc
=> Fix images path in hub module (#807)

downstream/modules/builder/con-definition-dependencies.adoc
Replaced it with community.aws
ansible builder docs change/remove geerlingguy.java
https://issues.redhat.com/browse/AAP-421
=> Removed geerlingguy.java

downstream/modules/builder/con-definition-dependencies.adoc
Replaced it with community.aws
ansible builder docs change/remove geerlingguy.java
https://issues.redhat.com/browse/AAP-421
=> Removed geerlingguy.java (#814)

downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Inserted correct text from Jira
Note in documentation about database and automation controller location is incorrect
https://issues.redhat.com/browse/AAP-8783
=> Correct statement about database location

downstream/modules/analytics/proc-add-roles-to-group.adoc, downstream/modules/analytics/proc-add-user-to-group.adoc, downstream/modules/analytics/proc-create-groups.adoc, downstream/modules/automation-hub/proc-delete-collection.adoc, downstream/modules/automation-hub/proc-delete-namespace.adoc, downstream/modules/navigator/con-navigator-collections.adoc, downstream/modules/navigator/con-navigator-modes.adoc, downstream/modules/navigator/proc-browse-collections-tui.adoc, downstream/modules/navigator/proc-execute-playbook-tui.adoc, downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc, downstream/modules/navigator/proc-review-ansible-config-tui.adoc, downstream/modules/navigator/proc-review-artifact.adoc, downstream/modules/navigator/proc-review-docs-tui.adoc, downstream/modules/navigator/proc-review-ee-tui.adoc, downstream/modules/security/con-automate-idps-rules.adoc, downstream/modules/security/con-automating-firewall-rules.adoc, downstream/modules/security/proc-creating-firewall-rule.adoc, downstream/modules/security/proc-deleting-firewall-rule.adoc
The relevant Jira ticket is[ AAP-4206](https://issues.redhat.com/browse/AAP-4206). The changes requested by this ticket are in Analytics, the Navigator Guide, the Security Guide, and Automation Hub.
=> AAP-4206: Add alt-text to images

downstream/modules/platform/ref-guidelines-hosts-groups.adoc, downstream/modules/platform/ref-hub-variables.adoc, downstream/modules/platform/ref-sso-variables.adoc
* Add further information to inventory file sections
Information of database and pah groups, and additional variables.
Add a reference with all variables for inventory setup.sh
https://issues.redhat.com/browse/AAP-1389
=> Add further information to inventory file sections (#783)

downstream/modules/platform/con-install-scenario-examples.adoc, downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc, downstream/modules/platform/ref-standalone-hub-inventory.adoc
Corrections and amendments
Update inventory example in documentation
https://issues.redhat.com/browse/AAP-7256
Affects 
`titles/upgrade`
`titles/aap-installation-guide`
=> Changes to inventory file information

downstream/modules/platform/con-install-scenario-examples.adoc, downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc, downstream/modules/platform/ref-standalone-hub-inventory.adoc
* Changes to inventory file information Update inventory example in documentation
https://issues.redhat.com/browse/AAP-7256
=> 2.3 Changes to inventory file information (#736)

downstream/modules/platform/proc-verify-controller-installation.adoc
Removed broken link and corrected wording
Correct broken link
https://issues.redhat.com/browse/AAP-9093
=> Removed broken link from the installation guide

downstream/modules/platform/proc-verify-controller-installation.adoc
Removed broken link and corrected wording
Correct broken link
https://issues.redhat.com/browse/AAP-9093
=> Removed broken link from the installation guide (#841)

downstream/assemblies/platform/assembly-installing-controller-operator.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/aap-on-azure/proc-azure-update-route-tables.adoc, downstream/modules/analytics/con-jobs-explorer.adoc, downstream/modules/analytics/proc-add-roles-to-group.adoc, downstream/modules/analytics/proc-add-user-to-group.adoc, downstream/modules/analytics/proc-create-groups.adoc, downstream/modules/analytics/proc-create-savings-plan.adoc, downstream/modules/analytics/proc-edit-savings-plan.adoc, downstream/modules/analytics/proc-filter-plans.adoc, downstream/modules/analytics/proc-link-plan-job-template.adoc, downstream/modules/analytics/proc-view-failed-jobs-detail.adoc, downstream/modules/automation-hub/proc-add-user-to-group.adoc, downstream/modules/automation-hub/proc-assigning-permissions.adoc, downstream/modules/automation-hub/proc-create-groups.adoc, downstream/modules/automation-hub/ref-permissions.adoc, downstream/modules/platform/proc-configuring-reverse-proxy.adoc, downstream/modules/platform/proc-enable-proxy-support.adoc, downstream/modules/platform/proc-restore-aap-backup.adoc
Per [AAP-4208](https://issues.redhat.com/browse/AAP-4208), changes made to accessibility formatting (PR 2/2)
See https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/761 for PR 1/2. 
Backporting to 2.1, 2.2, 2.3.
* AAP-4208A updated accessibility formatting
* AAP-4208A updated accessibility formatting
* AAP-4208A updated accessibility formatting
* AAP-4208A updated image formatting
=> AAP-4208A updated accessibility formatting (#792)

downstream/modules/platform/ref-automation-hub-requirements.adoc
Addition of introductory text to the Automation hub system requirements section
Add introductory text to Automation hub system requirements
https://issues.redhat.com/browse/AAP-8735
=> Edits to Automation hub system requirements

downstream/modules/platform/ref-automation-hub-requirements.adoc
* Edits to Automation hub system requirements
Addition of introductory text to the Automation hub system requirements section
Add introductory text to Automation hub system requirements
https://issues.redhat.com/browse/AAP-8735
* Edits to Automation hub system requirements
Addition of introductory text to the Automation hub system requirements section
Add introductory text to Automation hub system requirements
https://issues.redhat.com/browse/AAP-8735
* Addition of introductory text to the Automation hub system requirements section
Add introductory text to Automation hub system requirements
https://issues.redhat.com/browse/AAP-8735
=> Edits to Automation hub system requirements (#845)

downstream/modules/platform/ref-system-requirements.adoc
Addition of introductory text to the Automation hub system requirements section for 2.2
Add introductory text to Automation hub system requirements
https://issues.redhat.com/browse/AAP-8735
=> Edits to Automation hub system requirements for 2.2

downstream/assemblies/hub/assembly-faq.adoc, downstream/assemblies/hub/assembly-private-automation-hub.adoc, downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc, downstream/assemblies/hub/assembly-synclists.adoc, downstream/assemblies/hub/assembly-validated-content.adoc, downstream/modules/automation-hub/con-remote-repos.adoc, downstream/modules/automation-hub/con-required-shared-filesystem.adoc, downstream/modules/automation-hub/con-rh-certified-synclist.adoc, downstream/modules/automation-hub/proc-configure-ansible-galaxy-cli-verify.adoc, downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc, downstream/modules/automation-hub/proc-create-synclist.adoc, downstream/modules/automation-hub/proc-enabling-firewall-services.adoc, downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc, downstream/modules/automation-hub/proc-set-community-remote.adoc, downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc, downstream/modules/automation-hub/proc-shared-filesystem.adoc, downstream/modules/automation-hub/proc-using-content-signing-services-in-pah.adoc, downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml, downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
Correct text to include Validated Content
Add support for validated content in hub
https://issues.redhat.com/browse/AAP-5046
Backports #801 
=> 2.3 Add Certified and Validated Content (AAP-5046a) (#801)

downstream/modules/analytics/proc-add-roles-to-group.adoc, downstream/modules/analytics/proc-add-user-to-group.adoc, downstream/modules/analytics/proc-create-groups.adoc, downstream/modules/automation-hub/proc-delete-collection.adoc, downstream/modules/automation-hub/proc-delete-namespace.adoc, downstream/modules/navigator/con-navigator-collections.adoc, downstream/modules/navigator/con-navigator-modes.adoc, downstream/modules/navigator/proc-browse-collections-tui.adoc, downstream/modules/navigator/proc-execute-playbook-tui.adoc, downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc, downstream/modules/navigator/proc-review-ansible-config-tui.adoc, downstream/modules/navigator/proc-review-artifact.adoc, downstream/modules/navigator/proc-review-docs-tui.adoc, downstream/modules/navigator/proc-review-ee-tui.adoc, downstream/modules/security/con-automate-idps-rules.adoc, downstream/modules/security/con-automating-firewall-rules.adoc, downstream/modules/security/proc-creating-firewall-rule.adoc, downstream/modules/security/proc-deleting-firewall-rule.adoc
This PR adds alt-text to images in release 2.1 as requested in [AAP-4206](https://issues.redhat.com/browse/AAP-4206).
Affected titles: Analytics, Navigator Guide, Security Guide.
=> [Backport] - AAP-4206: Add alt-text to images (#833)

downstream/modules/builder/ref-build-args-base-image.adoc
Updated table with default values (normal and with RH RPM build.
Correct default value for EE_XXXX_IMAGE
https://issues.redhat.com/browse/AAP-8980
=> Added default values of image.

downstream/modules/platform/ref-system-requirements.adoc
Removing incorrect PostgreSQL statement for 2.2 section.
Remove incorrect PostgreSQL statement.
https://issues.redhat.com/browse/AAP-9320
=> Removing instance of PostgreSQL statement for 2.2

downstream/assemblies/platform/assembly-installing-controller-operator-external-db.adoc, downstream/assemblies/platform/assembly-installing-controller-operator.adoc, downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/platform/proc-controller-ingress-options.adoc, downstream/modules/platform/proc-hub-ingress-options.adoc
This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-3677.
Changes in this pull request include:
Added info requested in Section 3.2.5.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP3677/master.html
=> AAP-3677 Added information about which pods to expect

downstream/assemblies/platform/assembly-installing-controller-operator-external-db.adoc, downstream/assemblies/platform/assembly-installing-controller-operator.adoc, downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/platform/proc-controller-ingress-options.adoc, downstream/modules/platform/proc-hub-ingress-options.adoc
This branch backports the changes from PR631 to the 2.2 branch.
=> [Backport] - AAP-3677 Added information about which pods to expect (#631)

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc, downstream/modules/platform/ref-hub-variables.adoc, downstream/modules/platform/ref-sso-variables.adoc
Also moved SSO variables to automationhub
Reorder inventory file appendices to remove automationcatalog terms
https://issues.redhat.com/browse/AAP-9471
=> Removed automationcatalog inventory file variables

downstream/modules/automation-hub/proc-delete-user.adoc, downstream/titles/hub/managing-user-access/master.adoc
Added :experimental: to the master .adoc
Modify master.adoc
https://issues.redhat.com/browse/AAP-9522
Affects `titles/hub/managing-user-access`
=> Modifying master.adoc

downstream/modules/automation-hub/proc-delete-user.adoc, downstream/titles/hub/managing-user-access/master.adoc
* Modifying master.adoc
Added :experimental: to the master .adoc
Modify master.adoc
https://issues.redhat.com/browse/AAP-9522
* Modifying master.adoc
Added :experimental: to the master .adoc and corrected icon
Modify master.adoc
https://issues.redhat.com/browse/AAP-9522
Affects titles/hub/managing-user-access
=> Modifying master.adoc (#878)

downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-hub-variables.adoc
Added new variable
Document new variable 'nginx_tls_protocols' for AAP 2.2+
https://issues.redhat.com/browse/AAP-9490
=> Added nginx_tls_protocols to appendix

release-notes/master.adoc, release-notes/master.html, release-notes/topics/aap-211.adoc, release-notes/topics/aap-212.adoc, release-notes/topics/aap-213.adoc
Updated [2.1 Release notes](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_release_notes/index) with notes for 2.1.2 and 2.1.3.
=> AAP-3275 added release notes for 2.1.2 and 2.1.3

downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-hub-variables.adoc
Added new variable
Document new variable 'nginx_hsts_max_age' for AAP 2.3+
https://issues.redhat.com/browse/AAP-9488
=> Added nginx_hsts_max_age to appendix

downstream/modules/platform/ref-network-ports-protocols.adoc
Corrected variable names
Update automation hub table.
https://issues.redhat.com/browse/AAP-9634
=> Updated automation hub and PostgreSQL ports tables

downstream/assemblies/hub/assembly-working-with-signed-containers.adoc, downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc, downstream/modules/automation-hub/proc-adding-containers-remotely-to-the-automation-hub.adoc, downstream/modules/automation-hub/proc-configuring-the-client-to-verify-signatures.adoc, downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc, downstream/modules/automation-hub/proc-pushing-container-images-from-your-local.adoc, downstream/modules/automation-hub/proc-using-policies-with-signed-images.adoc, downstream/titles/hub/manage-containers/master.adoc
Backports #619 and  #894  to 2.3
Affects `titles/hub/manage-containers`
=> 2.3 AAP-4667 Container signing for EE

downstream/modules/platform/ref-controller-variables.adoc
* Added nginx port variables to inventory appendix
Added nginx_http_port and nginx_https_port.
https://issues.redhat.com/browse/AAP-9700
=> Added nginx port variables to inventory appendix (#885)

downstream/assemblies/platform/assembly-upgrading-controller.adoc, downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
[AAP-9531](https://issues.redhat.com/browse/AAP-9531)
Updated RHEL version notation within the [Ansible Platform Installation Guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html-single/red_hat_ansible_automation_platform_installation_guide/index#rpm_source).
=> AAP-9531 updated RHEL version notation

downstream/assemblies/platform/assembly-upgrading-controller.adoc
2.1 Backport of [PR 900](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/900).
* AAP-9531 updated RHEL version notation
=> AAP-9531 updated RHEL version notation (#900)

downstream/assemblies/platform/assembly-upgrading-controller.adoc, downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
2.3 Backport of [PR 900](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/900).
* AAP-9531 updated RHEL version notation
=> 2.3 AAP-9531 updated RHEL version notation (#900)

downstream/snippets/aap-rn-template.adoc, downstream/snippets/assembly-rn-template.adoc, downstream/snippets/controller-rn-template.adoc, downstream/snippets/hub-rn-template.adoc, downstream/snippets/operator-rn-template.adoc, release-notes/master.adoc
This PR contains templates for future Release Notes updates. Templates with instructions at the top of each file are stored in the ../downstream/snippets directory.
=> Created templates for future release notes

downstream/modules/platform/ref-controller-variables.adoc, downstream/modules/platform/ref-hub-variables.adoc
* Added nginx_hsts_max_age to appendix
Added new variable
Document new variable 'nginx_hsts_max_age' for AAP 2.3+
https://issues.redhat.com/browse/AAP-9488
* Added nginx_hsts_max_age to appendix
Corrected wording.
Document new variable 'nginx_hsts_max_age' for AAP 2.3+
https://issues.redhat.com/browse/AAP-9488
=> Added nginx_hsts_max_age to appendix (#883)

downstream/assemblies/catalog/assembly-installing-receptor.adoc, downstream/assemblies/central-auth/assembly-assign-hub-admin-permissions.adoc, downstream/modules/aap-on-azure/proc-azure-configure-ad-sso.adoc, downstream/modules/automation-hub/proc-add-container-readme.adoc, downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc, downstream/modules/automation-hub/proc-adding-containers-remotely-to-the-automation-hub.adoc, downstream/modules/automation-hub/proc-create-credential.adoc, downstream/modules/automation-hub/proc-delete-collection.adoc, downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc, downstream/modules/automation-hub/proc-downloading-signature-public-keys.adoc, downstream/modules/automation-hub/proc-edit-namespace.adoc, downstream/modules/automation-hub/proc-push-container.adoc, downstream/modules/automation-hub/proc-review-collection-imports.adoc, downstream/modules/automation-hub/proc-using-policies-with-signed-images.adoc, downstream/modules/builder/proc-customize-ee-image.adoc, downstream/modules/builder/proc-pull-protected-registry.adoc, downstream/modules/platform/proc-configure-known-proxies.adoc, downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc, downstream/modules/platform/proc-configuring-controller-route-options.adoc, downstream/modules/platform/proc-controller-ingress-options.adoc, downstream/modules/platform/proc-creating-controller-form-view.adoc, downstream/modules/platform/proc-hub-ingress-options.adoc, downstream/modules/platform/proc-importing-collections-into-private-automation-hub.adoc, downstream/modules/platform/proc-installing-with-internet.adoc, downstream/modules/platform/proc-installing-without-internet.adoc, downstream/modules/platform/proc-new-aap-instance-upgrade.adoc
Backport of [PR 888](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/888).
* AAP-4208-2.3 updated accessibility formatting (further fixes)
* AAP-4208-2.3 updated accessibility formatting following peer feedback
=> AAP-4208-2.3 updated accessibility formatting (further fixes) (#888)

downstream/assemblies/catalog/assembly-installing-receptor.adoc, downstream/assemblies/central-auth/assembly-assign-hub-admin-permissions.adoc, downstream/modules/aap-on-azure/proc-azure-configure-ad-sso.adoc, downstream/modules/automation-hub/proc-add-container-readme.adoc, downstream/modules/automation-hub/proc-delete-collection.adoc, downstream/modules/automation-hub/proc-edit-namespace.adoc, downstream/modules/automation-hub/proc-push-container.adoc, downstream/modules/automation-hub/proc-review-collection-imports.adoc, downstream/modules/builder/proc-customize-ee-image.adoc, downstream/modules/builder/proc-pull-protected-registry.adoc, downstream/modules/platform/proc-configure-known-proxies.adoc, downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc, downstream/modules/platform/proc-configuring-controller-route-options.adoc, downstream/modules/platform/proc-controller-ingress-options.adoc, downstream/modules/platform/proc-creating-controller-form-view.adoc, downstream/modules/platform/proc-hub-ingress-options.adoc, downstream/modules/platform/proc-new-aap-instance-upgrade.adoc
Backport of https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/888.
* AAP-4208-2.3 updated accessibility formatting (further fixes)
* AAP-4208-2.3 updated accessibility formatting following peer feedback
=> 2.2 AAP-4208 updated accessibility formatting (further fixes) (#888)

downstream/modules/platform/ref-hub-variables.adoc
* Added automationhub variable
Added placemarker for _enable_analytics
Document new variable 'automationhub_enable_analytics' for AAP 2.3+
https://issues.redhat.com/browse/AAP-9491
=> Added automationhub variable (#880)

downstream/assemblies/catalog/assembly-installing-receptor.adoc, downstream/assemblies/central-auth/assembly-assign-hub-admin-permissions.adoc, downstream/modules/aap-on-azure/proc-azure-configure-ad-sso.adoc, downstream/modules/automation-hub/proc-add-container-readme.adoc, downstream/modules/automation-hub/proc-delete-collection.adoc, downstream/modules/automation-hub/proc-edit-namespace.adoc, downstream/modules/automation-hub/proc-push-container.adoc, downstream/modules/automation-hub/proc-review-collection-imports.adoc, downstream/modules/builder/proc-customize-ee-image.adoc, downstream/modules/builder/proc-pull-protected-registry.adoc, downstream/modules/platform/proc-configure-known-proxies.adoc, downstream/modules/platform/proc-controller-ingress-options.adoc, downstream/modules/platform/proc-controller-route-options.adoc, downstream/modules/platform/proc-hub-ingress-options.adoc, downstream/modules/platform/proc-new-aap-instance-upgrade.adoc
Backport of https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/888.
* AAP-4208-2.3 updated accessibility formatting (further fixes)
* AAP-4208-2.3 updated accessibility formatting following peer feedback
=> 2.1 AAP-4208 updated accessibility formatting (further fixes) (#888)

downstream/assemblies/hub/assembly-pull-image.adoc, downstream/assemblies/hub/assembly-setup-container-repository.adoc, downstream/modules/automation-hub/proc-add-container-readme.adoc, downstream/modules/automation-hub/proc-add-group-to-container-repo.adoc, downstream/modules/automation-hub/proc-add-user-to-group.adoc, downstream/modules/automation-hub/proc-assigning-permissions.adoc, downstream/modules/automation-hub/proc-delete-container.adoc, downstream/modules/automation-hub/proc-pull-image.adoc, downstream/modules/automation-hub/proc-tag-image.adoc, downstream/modules/automation-hub/ref-container-permissions.adoc
Making some minor corrections in hub documentation
Correct minor errors in document
https://issues.redhat.com/browse/AAP-10126
Affects `titles/hub/manage-containers`
=> Correcting minor errors

downstream/assemblies/hub/assembly-populate-container-registry.adoc, downstream/assemblies/hub/assembly-pull-image.adoc, downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Added admonition and tidied the content.
Update document to reflect new Red Hat registry network changes
https://issues.redhat.com/browse/AAP-9698
=> Added information about pulling container images

downstream/assemblies/hub/assembly-container-user-access.adoc, downstream/assemblies/hub/assembly-delete-container.adoc, downstream/assemblies/hub/assembly-populate-container-registry.adoc, downstream/assemblies/hub/assembly-setup-container-repository.adoc, downstream/modules/automation-hub/proc-add-group-to-container-repo.adoc, downstream/modules/automation-hub/proc-add-user-to-group.adoc, downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc, downstream/modules/automation-hub/proc-adding-containers-remotely-to-the-automation-hub.adoc, downstream/modules/automation-hub/proc-assigning-permissions.adoc, downstream/modules/automation-hub/proc-configuring-the-client-to-verify-signatures.adoc, downstream/modules/automation-hub/proc-create-groups.adoc, downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc, downstream/modules/automation-hub/proc-obtain-images.adoc, downstream/modules/automation-hub/proc-pull-image.adoc, downstream/modules/automation-hub/proc-push-container.adoc, downstream/modules/automation-hub/proc-tag-image.adoc, downstream/modules/automation-hub/proc-tag-pulled-image.adoc, downstream/modules/automation-hub/proc-using-policies-with-signed-images.adoc, downstream/modules/automation-hub/ref-container-permissions.adoc
Added correct attributes and did a general tidy up.
Update document
https://issues.redhat.com/browse/AAP-9878
=> Updated document

downstream/assemblies/hub/assembly-container-user-access.adoc, downstream/assemblies/hub/assembly-delete-container.adoc, downstream/assemblies/hub/assembly-populate-container-registry.adoc, downstream/assemblies/hub/assembly-setup-container-repository.adoc, downstream/modules/automation-hub/proc-add-group-to-container-repo.adoc, downstream/modules/automation-hub/proc-add-user-to-group.adoc, downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc, downstream/modules/automation-hub/proc-adding-containers-remotely-to-the-automation-hub.adoc, downstream/modules/automation-hub/proc-assigning-permissions.adoc, downstream/modules/automation-hub/proc-configuring-the-client-to-verify-signatures.adoc, downstream/modules/automation-hub/proc-create-groups.adoc, downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc, downstream/modules/automation-hub/proc-obtain-images.adoc, downstream/modules/automation-hub/proc-pull-image.adoc, downstream/modules/automation-hub/proc-push-container.adoc, downstream/modules/automation-hub/proc-tag-image.adoc, downstream/modules/automation-hub/proc-tag-pulled-image.adoc, downstream/modules/automation-hub/proc-using-policies-with-signed-images.adoc, downstream/modules/automation-hub/ref-container-permissions.adoc
Added correct attributes and did a general tidy up. https://issues.redhat.com/browse/AAP-9878
Affects `titles/hub/manage-containers`
=> 2.3 Updated document (#922)

downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc
[AAP-9671](https://issues.redhat.com/browse/AAP-9671)
Updated introduction for proc-install-ha-hub-selinux ([2.2. Install a high availability (HA) deployment of automation hub on SELinux](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/deploying_a_high_availability_automation_hub/installing-high-availability-hub#install_a_high_availability_ha_deployment_of_automation_hub_on_selinux)) to clarify procedure.
=> AAP-9671 updated Introduction

downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/platform/con-storage-options-for-operator-installation-on-ocp.adoc, downstream/modules/platform/proc-provision-ocp-storage-amazon-s3.adoc, downstream/modules/platform/proc-provision-ocp-storage-azure-blob.adoc
Backports #914 to 2.3.
Add s3 and Azure blob storage for Hub CR
AAP-6231
Affects `titles/aap-operator-installation/`
=> 2.3 AAP-6231 Add s3 and Azure blob storage for Hub CR (#914)

downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/platform/con-storage-options-for-operator-installation-on-ocp.adoc, downstream/modules/platform/proc-provision-ocp-storage-amazon-s3.adoc, downstream/modules/platform/proc-provision-ocp-storage-azure-blob.adoc
Backports #914 to 2.2.
Add s3 and Azure blob storage for Hub CR
AAP-6231
Affects `titles/aap-operator-installation/`
=> 2.2 AAP-6231 Add s3 and Azure blob storage for Hub CR (#914)

downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc
* AAP-9671 updated Introduction
* AAP-9671 edited attribute
=> AAP-9671 updated Introduction (#932)

downstream/attributes/attributes.adoc, downstream/titles/aap-installation-guide/docinfo.xml, downstream/titles/aap-operations-guide/docinfo.xml, downstream/titles/aap-operator-backup/docinfo.xml, downstream/titles/aap-operator-installation/docinfo.xml, downstream/titles/aap-planning-guide/docinfo.xml, downstream/titles/analytics/automation-savings-planner/docinfo.xml, downstream/titles/analytics/automation-savings/docinfo.xml, downstream/titles/analytics/job-explorer/docinfo.xml, downstream/titles/analytics/reports/docinfo.xml, downstream/titles/automation-mesh/docinfo.xml, downstream/titles/builder/docinfo.xml, downstream/titles/central-auth/docinfo.xml, downstream/titles/dev-guide/docinfo.xml, downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml, downstream/titles/hub/getting-started/docinfo.xml, downstream/titles/hub/high-availability/docinfo.xml, downstream/titles/hub/install/docinfo.xml, downstream/titles/hub/lifecycle/docinfo.xml, downstream/titles/hub/manage-containers/docinfo.xml, downstream/titles/hub/managing-user-access/docinfo.xml, downstream/titles/hub/publishing-internal-content/docinfo.xml, downstream/titles/hub/uploading-collections/docinfo.xml, downstream/titles/hub/uploading-internal-collections/docinfo.xml, downstream/titles/navigator-guide/docinfo.xml, downstream/titles/ocp_performance_guide/docinfo.xml, downstream/titles/security-guide/docinfo.xml, downstream/titles/upgrade/docinfo.xml
- Updates version in docinfo.xml from `2.3` to `2.4`
- Updates OpenShift version
**NOTE:**
- Does not update core version or path for AAP download.
- Does not update files whose version is older than `2.3`.
- Does not scrub `2.3` from the general docset
=> AAP-10662 Update AAP version to 2.4

release-notes/master.adoc, release-notes/master.html, release-notes/topics/aap-214.adoc, release-notes/topics/controller-414.adoc, release-notes/topics/hub-443.adoc
[AAP-5422](https://issues.redhat.com/browse/AAP-5422)
Added AAP 2.1.4 release notes following SME approval of [Google doc draft](https://docs.google.com/document/d/1j4IcAjGVhXYFwltmEF47WVmJl9jT0O_Ax24V3v4oWQI/edit#)
=> AAP-5422 Z-Stream release notes 2.1.4

downstream/assemblies/hub/assembly-working-with-namespaces.adoc, downstream/modules/automation-hub/con-namespaces.adoc, downstream/modules/automation-hub/proc-create-content-developers.adoc, downstream/modules/automation-hub/proc-create-namespace.adoc, downstream/modules/automation-hub/proc-delete-namespace.adoc, downstream/modules/automation-hub/proc-edit-namespace.adoc, downstream/modules/automation-hub/proc-review-collection-imports.adoc, downstream/modules/automation-hub/proc-uploading-collections.adoc, downstream/titles/hub/uploading-internal-collections/master.adoc
Editing hub documents to align them with style guide
https://issues.redhat.com/browse/AAP-10816
=> Editing hub documents

downstream/assemblies/hub/assembly-working-with-namespaces.adoc, downstream/modules/automation-hub/con-namespaces.adoc, downstream/modules/automation-hub/proc-create-content-developers.adoc, downstream/modules/automation-hub/proc-create-namespace.adoc, downstream/modules/automation-hub/proc-delete-namespace.adoc, downstream/modules/automation-hub/proc-edit-namespace.adoc, downstream/modules/automation-hub/proc-review-collection-imports.adoc, downstream/modules/automation-hub/proc-uploading-collections.adoc, downstream/titles/hub/uploading-internal-collections/master.adoc
Editing hub documents to align them with style guide
https://issues.redhat.com/browse/AAP-10816
Affects `titles/hub/uploading-internal-collections`
=> Editing hub documents (#943)

release-notes/master.adoc, release-notes/master.html, release-notes/topics/aap-214.adoc, release-notes/topics/controller-414.adoc, release-notes/topics/hub-443.adoc
Backport of https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/946.
[AAP-5422](https://issues.redhat.com/browse/AAP-5422) Z-Stream release notes 2.1.4
=> AAP-5422 Z-Stream release notes 2.1.4 (#946)

downstream/modules/platform/proc-create-keycloak-client.adoc, downstream/modules/platform/proc-create-keycloak-realm.adoc
Correcting attributes that have rendered incorrectly in code blocks
Code blocks not rendering Attributes correctly
https://issues.redhat.com/browse/AAP-11221
Affects `modules/platform`
=> [AAP-11221] Correcting attributes (#956) (#961)

downstream/assemblies/hub/assembly-managing-private-collections.adoc, downstream/modules/automation-hub/con-approval.adoc, downstream/modules/automation-hub/proc-reject-collections.adoc, downstream/titles/hub/publishing-internal-content/master.adoc
Ensuring that hub documentation adheres to Style Guide and adding missing attributes.
https://issues.redhat.com/browse/AAP-11277
Affects `titles/hub`
=> [AAP-11277] Hub document edits

downstream/assemblies/hub/assembly-managing-private-collections.adoc, downstream/modules/automation-hub/con-approval.adoc, downstream/modules/automation-hub/proc-reject-collections.adoc, downstream/titles/hub/publishing-internal-content/master.adoc
* [AAP-11277] Hub document edits
Ensuring that hub documentation adheres to Style Guide and adding missing attributes.
https://issues.redhat.com/browse/AAP-11277
Affects titles/hub
=> [AAP-11277] Hub document edits (#963)

downstream/assemblies/hub/assembly-managing-private-collections.adoc, downstream/modules/automation-hub/con-approval.adoc, downstream/modules/automation-hub/proc-reject-collections.adoc, downstream/titles/hub/publishing-internal-content/master.adoc
Ensuring that hub documentation adheres to Style Guide and adding missing attributes.
https://issues.redhat.com/browse/AAP-11277
Affects titles/hub
=> [AAP-11277] Hub document edits (#963) (#970)

downstream/assemblies/navigator/assembly-installing-on-rhel.adoc, downstream/assemblies/platform/assembly-attaching-subscriptions.adoc, downstream/assemblies/platform/assembly-upgrading-controller.adoc, downstream/attributes/attributes.adoc, downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc, downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc, downstream/modules/platform/proc-attaching-subscriptions.adoc
Part of AAP-10817
Updates Ansible core and minimum RHEL versions.
=> AAP-10817 Modify OCP and minimum RHEL versions for 2.4

bin/sync_docs.sh, bin/sync_ocp_latest.sh
Create a sync script in the `bin/` directory that will be deployed by the Jenkins server to sync the AAP 2.4 docs to the production server.
=> AAP-11388 Add sync script for AAP 2.4

downstream/assemblies/hub/assembly-hub-connect-sso.adoc, downstream/modules/automation-hub/proc-run-setup-script-hub.adoc, downstream/titles/hub/install/master.adoc
Adding missing attributes and updating content to align with Style Guide.
[Docs] Add missing attributes in hub documentation
https://issues.redhat.com/browse/AAP-11417
Affects `titles/hub/install`
=> Adding missing attributes

downstream/assemblies/hub/assembly-hub-connect-sso.adoc, downstream/modules/automation-hub/proc-run-setup-script-hub.adoc, downstream/titles/hub/install/master.adoc
Adding missing attributes and updating content to align with Style Guide.
[Docs] Add missing attributes in hub documentation
https://issues.redhat.com/browse/AAP-11417
Affects `titles/hub/install`
=> Adding missing attributes (#979)

downstream/assemblies/hub/assembly-hub-connect-sso.adoc, downstream/modules/automation-hub/proc-run-setup-script-hub.adoc, downstream/titles/hub/install/master.adoc
Adding missing attributes and updating content to align with Style Guide.
[Docs] Add missing attributes in hub documentation
https://issues.redhat.com/browse/AAP-11417
Affects `titles/hub/install`
=> Adding missing attributes (#979) (#981)

downstream/assemblies/hub/assembly-hub-connect-sso.adoc, downstream/modules/automation-hub/proc-run-setup-script-hub.adoc, downstream/titles/hub/install/master.adoc
Adding missing attributes and updating content to align with Style Guide.
[Docs] Add missing attributes in hub documentation
https://issues.redhat.com/browse/AAP-11417
Affects `titles/hub/install`
=> Adding missing attributes (#979) (#981) (#982)

downstream/modules/platform/ref-automation-hub-requirements.adoc, downstream/modules/platform/ref-controller-system-requirements.adoc, downstream/modules/platform/ref-postgresql-requirements.adoc, downstream/modules/platform/ref-system-requirements.adoc
This PR backports the changes made in PR #811 to the 2.3 branch.
=> AAP-7916 - Eliminate confusing "disk" terminology references (#811)

downstream/snippets/published-24.txt
AAP-11399 Add list of published 2.4 docs to the `snippets/` folder
Backports #987 to 2.4
=> AAP-11399 Add list of published 2.4 docs to snippets folder (#987)

downstream/titles/hub/install/docinfo.xml, downstream/titles/hub/install/master.adoc
This PR addresses the changes for https://issues.redhat.com/browse/AAP-8522.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP8522/master.html
=> AAP-8522 - updated the system requirements for PAH

downstream/assemblies/platform/assembly-network-ports-protocols.adoc
[AAP-11647](https://issues.redhat.com/browse/AAP-11647)
2.4 Backport of [PR 986](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/986)
=> AAP-11647 updated table 4.10 Automation hub (#986)

downstream/titles/hub/install/docinfo.xml, downstream/titles/hub/install/master.adoc
This PR backports the changes for PR#813 to the 2.4 branch.
=> [Backport] - AAP-8522 - updated the system requirements for PAH

downstream/titles/hub/install/docinfo.xml, downstream/titles/hub/install/master.adoc
This PR backports the changes for PR#813 to the 2.3 branch.
=> [Backport] - AAP-8522 - updated the system requirements for PAH (#813)

downstream/titles/hub/install/docinfo.xml, downstream/titles/hub/install/master.adoc
This PR backports the changes from PR 1006 to the 2.4 branch.
=> [Backport] - PR1006 Fixed missing doc title in master file

downstream/assemblies/platform/assembly-installing-controller-operator.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc
This PR addresses the changes for https://issues.redhat.com/browse/AAP-11313 and includes the following: 
Adds a paragraph to "Chapter 4: Installing and configuring automation hub on Red Hat OpenShift Container Platform web console"
=> AAP-11313 - added information regarding configuration of Hub connection

downstream/assemblies/platform/assembly-installing-controller-operator.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc
This PR backports the changes for PR 1001 to the 2.3 branch.
=> [Backport] AAP-11313 - added information for configuration of Hub connection

downstream/titles/release-notes/docinfo.xml
Update AAP version in 2.4 release notes.
Backport to 2.4
=> Update version in 2.4 release notes

downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc, downstream/assemblies/hub/assembly-synclists.adoc, downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc, downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
TO DO. Synclist deprecation.
Docs about synclist deprecation and requirements file
https://issues.redhat.com/browse/AAP-9650
=> Added information about requirements file.

downstream/modules/builder/proc-installing-builder.adoc
This PR backports the changes from #1039 to the 2.3 branch.
=> AAP-12541 - Update procedure for enabling the repo (#1039)

downstream/attributes/attributes.adoc
Backport: AAP-12753 Updated attributes.adoc with Event-driven Ansible attributes.
=> Backport: AAP-12753 Updated attributes.adoc with EDA

downstream/attributes/attributes.adoc
Just deleted attributes that were previously added prior to confirming with the SMEs for EDA.
=> AAP-12753A Deleted extra EDA attributes added previously.

downstream/modules/platform/con-aap-installation-prereqs.adoc
Jira link: [AAP-8366](https://issues.redhat.com/browse/AAP-8366)
Added prerequisite and note stating that users should use fully updated nodes prior to installing AAP.
=> [2.4] AAP-8366: Recommend using fully updated nodes to install AAP (#1029)

downstream/titles/eda/eda-user-guide/docinfo.xml, downstream/titles/eda/eda-user-guide/master.adoc
Reverts RedHatInsights/red-hat-ansible-automation-platform-documentation#1073
Reverting this because Ed's PR has not yet been merged. Will suggest this fix be part of his PR to create this document.
=> Revert "Modified title fields to remove attribute and match to fix build"

downstream/titles/aap-hardening/master.adoc
Jira link: [AAP-1636](https://issues.redhat.com/browse/AAP-1636)
=> [2.4] AAP-1636-fix: Reorder of titles (#1069)

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc, downstream/assemblies/eda/eda, downstream/attributes/attributes.adoc, downstream/modules/eda/proc-eda-activate-webhook.adoc, downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc, downstream/modules/eda/proc-eda-enable-rulebook-activations.adoc, downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc, downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc, downstream/modules/eda/proc-eda-set-up-new-project.adoc, downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc, downstream/modules/eda/proc-eda-set-up-token.adoc, downstream/modules/eda/proc-eda-test-with-K8s.adoc, downstream/titles/eda/eda-user-guide/docinfo.xml, downstream/titles/eda/eda-user-guide/master.adoc
* Creating EDA user guide
Adding content for the creation of EDA user guide
Create "Event-Driven Ansible controller user guide"
https://issues.redhat.com/browse/AAP-11062
Affects `titles/eda/eda-user-guide`
=> Creating EDA user guide (#1026)

downstream/titles/aap-operator-installation/docinfo.xml, downstream/titles/security-guide/docinfo.xml, downstream/titles/upgrade/docinfo.xml
Fix subtitle tags in `docinfo.xml` for the following docs:
- `./upgrade/docinfo.xml`
- `./aap-operator-installation/docinfo.xml`
- `./security-guide/docinfo.xml`
=> Fix tag in docinfo.xml

downstream/titles/aap-operator-installation/docinfo.xml, downstream/titles/security-guide/docinfo.xml, downstream/titles/upgrade/docinfo.xml
Backports #1088 to `2.4`
Fixes tags in `docinfo.xml`
=> Fix tag in docinfo.xml (#1088)

downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc, downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc, downstream/titles/aap-operator-installation/master.adoc
Created new assembly and module for instructions on installing EDA on AAP operator on OpenShift Container Platform. Also added new assembly to master. adoc.
=> AAP-10975C New chapter on EDA installation w/ AAP operator on OCP

downstream/assemblies/hub/assembly-managing-container-registry.adoc, downstream/assemblies/hub/assembly-synclists.adoc, downstream/assemblies/hub/assembly-validated-content.adoc, downstream/modules/automation-hub/con-container-registry.adoc, downstream/modules/automation-hub/con-remote-repos.adoc, downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc, downstream/modules/automation-hub/proc-configure-automation-hub-server-gui.adoc, downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc, downstream/modules/automation-hub/proc-create-api-token.adoc, downstream/modules/automation-hub/proc-create-content-developers.adoc, downstream/modules/automation-hub/proc-create-namespace.adoc, downstream/modules/automation-hub/proc-create-synclist.adoc, downstream/modules/automation-hub/proc-create-users.adoc, downstream/modules/automation-hub/proc-delete-collection.adoc, downstream/modules/automation-hub/proc-delete-user.adoc, downstream/modules/automation-hub/proc-edit-namespace.adoc, downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc, downstream/modules/automation-hub/proc-pushing-container-images-from-your-local.adoc, downstream/modules/automation-hub/proc-review-collection-imports.adoc, downstream/modules/automation-hub/proc-set-community-remote.adoc, downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc, downstream/modules/automation-hub/proc-uploading-collections.adoc, downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
The changes in this PR reflect the updates made to the UI for automation hub on both console and AAP to address https://issues.redhat.com/browse/AAP-12885.
=> AAP-12885 Update docs to reflect UI changes for automation hub

downstream/assemblies/hub/assembly-managing-container-registry.adoc, downstream/assemblies/hub/assembly-synclists.adoc, downstream/assemblies/hub/assembly-validated-content.adoc, downstream/modules/automation-hub/con-container-registry.adoc, downstream/modules/automation-hub/con-remote-repos.adoc, downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc, downstream/modules/automation-hub/proc-configure-automation-hub-server-gui.adoc, downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc, downstream/modules/automation-hub/proc-create-api-token.adoc, downstream/modules/automation-hub/proc-create-content-developers.adoc, downstream/modules/automation-hub/proc-create-namespace.adoc, downstream/modules/automation-hub/proc-create-synclist.adoc, downstream/modules/automation-hub/proc-create-users.adoc, downstream/modules/automation-hub/proc-delete-collection.adoc, downstream/modules/automation-hub/proc-delete-user.adoc, downstream/modules/automation-hub/proc-edit-namespace.adoc, downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc, downstream/modules/automation-hub/proc-pushing-container-images-from-your-local.adoc, downstream/modules/automation-hub/proc-review-collection-imports.adoc, downstream/modules/automation-hub/proc-set-community-remote.adoc, downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc, downstream/modules/automation-hub/proc-uploading-collections.adoc, downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
This PR backports the changes for #1051 to the 2.4 branch and includes the following changes:
* AAP-12885 Update docs to reflect UI changes for automation hub
* AAP12885 - implemented SME review changes
=> [Backport] - AAP-12885 Update docs to reflect UI changes for automation hub (#1051)

downstream/archive/archived-assemblies/platform/assembly-installing-hub-operator-local-db.adoc, downstream/assemblies/platform/assembly-installing-controller-operator.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/platform/proc-access-hub-operator-ui.adoc, downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc, downstream/modules/platform/proc-configuring-controller-ldap-security.adoc, downstream/modules/platform/proc-configuring-controller-route-options.adoc, downstream/modules/platform/proc-creating-a-secret.adoc, downstream/modules/platform/proc-creating-controller-form-view.adoc, downstream/modules/platform/proc-hub-route-options.adoc, downstream/modules/platform/proc-install-cli-aap-operator.adoc, downstream/modules/platform/proc-post-migration-cleanup.adoc
This PR fixes some minor formatting errors identified during the 2.4 pre-release check.
=> ocpguide24 Formatting fixes from pre-release check

downstream/archive/archived-assemblies/platform/assembly-installing-hub-operator-local-db.adoc, downstream/assemblies/platform/assembly-installing-controller-operator.adoc, downstream/assemblies/platform/assembly-installing-hub-operator.adoc, downstream/modules/platform/proc-access-hub-operator-ui.adoc, downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc, downstream/modules/platform/proc-configuring-controller-ldap-security.adoc, downstream/modules/platform/proc-configuring-controller-route-options.adoc, downstream/modules/platform/proc-creating-a-secret.adoc, downstream/modules/platform/proc-creating-controller-form-view.adoc, downstream/modules/platform/proc-hub-route-options.adoc, downstream/modules/platform/proc-install-cli-aap-operator.adoc, downstream/modules/platform/proc-post-migration-cleanup.adoc
This PR backports the changes for #1114 to the 2.4 branch.
=> ocpguide24 Formatting fixes from pre-release check (#1114)

downstream/assemblies/central-auth/assembly-central-auth-group-perms.adoc, downstream/modules/automation-hub/proc-assigning-roles.adoc, downstream/modules/platform/proc-choosing-obtaining-installer.adoc, downstream/modules/platform/proc-installing-with-internet.adoc
Added bullet points in a few prerequisite sections with only one requirement and clarified link text.
=> Centralauth2.4: Formatting and link text updates for pre-release checklist

downstream/titles/eda/eda-getting-started-guide/docinfo.xml, downstream/titles/eda/eda-getting-started-guide/master.adoc
This PR updates the mismatch title in master.adoc and docinfo files to fix Pantheon build.
=> edags2.4 - updating title in master.adoc and docinfo

downstream/titles/eda/eda-getting-started-guide/docinfo.xml, downstream/titles/eda/eda-getting-started-guide/master.adoc
This PR backports the changes for #1120 to the 2.4 branch and includes the following change:
edags2.4 - updating title in master.adoc and docinfo files to fix Pantheon build
=> [Backport] edags2.4 - updating title in master.adoc and docinfo (#1120)

downstream/titles/hub/repo-management/docinfo.xml, downstream/titles/hub/repo-management/master.adoc
This PR updates the abstract for consistency with other docs and removes the attribute from the book title to prevent potential Pantheon issues.
=> repo2.4 - Updated abstract and title in master.adoc file

downstream/titles/hub/repo-management/docinfo.xml, downstream/titles/hub/repo-management/master.adoc
This PR backports the changes from #1126 to the 2.4 branch.
=> [Backport] repo2.4 - Updated abstract and title in master.adoc file (#1126)

downstream/modules/platform/con-aap-backup-recovery.adoc
This PR fixes a broken attribute found during pre-release checks.
=> opback24 - fixed broken attribute

downstream/modules/platform/con-aap-backup-recovery.adoc
This PR backports the changes from #1129 to the 2.4 branch.
=> [Backport] opback24 - fixed broken attribute (#1129)

downstream/modules/automation-hub/proc-delete-user.adoc
This PR fixes the ellipses graphic so it renders at the appropriate size.
=> user24 - Fixing ellipses graphic

downstream/modules/automation-hub/proc-delete-user.adoc
This PR backports the changes from #1132 to the 2.4 branch.
=> [Backport] user24 - Fixing ellipses graphic (#1132)

downstream/assemblies/eda/assembly-using-eda-controller.adoc
Updated the link to the EDA controller's guide (still contain temporary link)
=> Corrected the link to the EDA controller user's guide

downstream/assemblies/eda/assembly-using-eda-controller.adoc
Updated the link to the EDA controller's guide in the Getting Started with EDA Guide.
=> Backport-2.4-1136 AAP-13532 Corrected the link to the EDA controller user's guide

downstream/modules/platform/ref-hub-variables.adoc
Added ee_from_hub_only variable to hub variables
Variable ee_from_hub_only isn't documented
https://issues.redhat.com/browse/AAP-10980
=> Added inventory variable

downstream/modules/platform/ref-hub-variables.adoc
* Added inventry variable
Added ee_from_hub_only variable to hub variables
Variable ee_from_hub_only isn't documented
https://issues.redhat.com/browse/AAP-10980
* Added inventory variable
Added line of what the value 'false' does.
Variable ee_from_hub_only isn't documented
https://issues.redhat.com/browse/AAP-10980
=> Added inventory variable (#948)

downstream/assemblies/eda/assembly-ansible-rulebooks.adoc
Corrected link to EDA controller user's guide in Ch 2 of GS w/ EDA Guide
=> AAP-13541 Corrected the link to EDA controller user's guide in Ch 2

downstream/assemblies/eda/assembly-ansible-rulebooks.adoc
Corrected the link to EDA controller user's guide in Chapter 2.
=> Backport-2.4-1142 Corrected the link to EDA controller user's guide in Ch 2

downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc, downstream/modules/automation-hub/con-remote-repos.adoc, downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc, downstream/modules/automation-hub/proc-set-community-remote.adoc, downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
* Fixed icon size
Changed size to 10,25
https://issues.redhat.com/browse/AAP-13667
=> 2.4 Fixed icon size (#1147)

downstream/assemblies/hub/assembly-validated-content.adoc, downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc, downstream/modules/dev-guide/con-content-workflows.adoc, downstream/modules/platform/con-aap-upgrade-prereq.adoc, downstream/modules/platform/proc-choosing-obtaining-installer.adoc, downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc, downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc, downstream/modules/platform/proc-installing-with-internet.adoc, downstream/modules/platform/proc-installing-without-internet.adoc, downstream/modules/platform/proc-upgrade-installer.adoc, downstream/modules/platform/ref-hub-configs.adoc, downstream/titles/hub/install/master.adoc
* Fix broken links that use PlatformVers attribute in 2.3, 2.4 docs
* Fix assembly link
=> Fix broken links that use PlatformVers attribute in 2.4 docs (#1144)

downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc, downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc, downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Changed format of icons to make them more visible
Icons in EDA user guide are barely visible.
https://issues.redhat.com/browse/AAP-13642
=> Changed icons in user guide

downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc, downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc, downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
* Changed icons in user guide
Changed format of icons to make them more visible
Icons in EDA user guide are barely visible.
https://issues.redhat.com/browse/AAP-13642
* Changed iccons in user guide
Fixed variable names
Icons in EDA user guide are barely visible.
https://issues.redhat.com/browse/AAP-13642
=> Changed icons in user guide (#1152)

downstream/titles/release-notes/topics/aap-23.adoc
Corrected bulleted list.
Formatting issue with Release notes
https://issues.redhat.com/browse/AAP-13644
=> Corrected Release Notes formatting

downstream/titles/release-notes/topics/aap-23.adoc
Corrected bulleted list.
Formatting issue with Release notes
https://issues.redhat.com/browse/AAP-13644
=> Corrected Release Notes formatting (#1154)

downstream/titles/hub/install/master.adoc
Replaced it with the 2.14 version, checked with SME
Wrong Ansible version supplied.
https://issues.redhat.com/browse/AAP-13646
=> Corrected Ansible version

downstream/titles/hub/install/master.adoc
Replaced it with the 2.14 version, checked with SME
Wrong Ansible version supplied.
https://issues.redhat.com/browse/AAP-13646
=> Corrected Ansible version (#1157)

downstream/titles/hub/install/master.adoc
Corrected required Ansible version
Wrong Ansible version supplied.
https://issues.redhat.com/browse/AAP-13646
=> Corrected Ansible version for 2.3

downstream/titles/release-notes/topics/aap-24.adoc, downstream/titles/release-notes/topics/controller-440.adoc, downstream/titles/release-notes/topics/docs-24.adoc, downstream/titles/release-notes/topics/platform-intro.adoc
JIRA:
- Restructuring release notes: https://issues.redhat.com/browse/AAP-12257
- Creating AAP 2.4 release notes: https://issues.redhat.com/browse/AAP-12511
Following are the changes:
Fixed broken links in AAP 2.4 release notes
=> AAP-12257-rn: Fixed broken links in AAP 2.4 release notes

downstream/assemblies/platform/assembly-converting-playbooks-for-aap2.adoc, downstream/modules/platform/con-persisting-data-from-auto-runs.adoc, downstream/modules/platform/ref-converting-playbook-examples.adoc, downstream/titles/upgrade/master.adoc
Corrected build errors
Correct build errors in upgrade and migration guide
https://issues.redhat.com/browse/AAP-13735
=> Corrected assembly names and include statement (#1168)

downstream/assemblies/dev-guide/assembly-virt-env-to-ee.adoc, downstream/assemblies/platform/assembly-migrate-isolated-execution-nodes.adoc, downstream/modules/dev-guide/proc-select-custom-venv-export.adoc, downstream/modules/platform/con-aap-upgrade-prereq.adoc, downstream/modules/platform/con-backup-aap.adoc, downstream/modules/platform/proc-configure-upgraded-aap.adoc, downstream/modules/platform/proc-new-aap-instance-upgrade.adoc, downstream/modules/platform/proc-restore-aap-backup.adoc, downstream/modules/platform/proc-upgrade-installer.adoc, downstream/titles/upgrade/master.adoc
Fix box around Migrating isolated nodes chapter in upgrade guide
=> Fix box around Migrating isolated nodes chapter in upgrade guide

downstream/assemblies/dev-guide/assembly-virt-env-to-ee.adoc, downstream/assemblies/platform/assembly-migrate-isolated-execution-nodes.adoc, downstream/modules/dev-guide/proc-select-custom-venv-export.adoc, downstream/modules/platform/con-aap-upgrade-prereq.adoc, downstream/modules/platform/con-backup-aap.adoc, downstream/modules/platform/proc-configure-upgraded-aap.adoc, downstream/modules/platform/proc-new-aap-instance-upgrade.adoc, downstream/modules/platform/proc-restore-aap-backup.adoc, downstream/modules/platform/proc-upgrade-installer.adoc, downstream/titles/upgrade/master.adoc
Fix box around Migrating isolated nodes chapter in upgrade guide
Backports #1171
=> Fix box around Migrating isolated nodes chapter in upgrade guide (#1171)

downstream/modules/dev-guide/proc-select-custom-venv-export.adoc
Add blank line between codeblock and note
=> Add blank line between codeblock and note

downstream/modules/dev-guide/proc-select-custom-venv-export.adoc
Add blank line between codeblock and note
=> Add blank line between codeblock and note (#1173)

downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
Fix a formatting issue in Chapter 4. Migrating isolated nodes to execution nodes on the customer portal.
The chapter is surrounded by a box:
=> AAP-13660 Fix formatting issues in 2.4 Upgrade guide

downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
This PR backports the doc change 'scenario updates when importing or generating API tokens in AAP installer' in AAP 2.4 docs.
See PR https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1061 for more info.
=> Backport pull request #1061 from main to 2.4

downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
This PR backports the doc change 'scenario updates when importing or generating API tokens in AAP installer' in AAP 2.3 docs.
See PR https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1061 for more info.
=> Backport pull request #1061 from main to 2.3

downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Updated file name for 2.4
[DDF] shows instructions for AAP 2.3
https://issues.redhat.com/browse/AAP-13654
=> Corrected install instructions

downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Updated file name for 2.4
https://issues.redhat.com/browse/AAP-13654
=> Corrected install instructions (#1182)

downstream/modules/eda/proc-eda-activate-webhook.adoc, downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc, downstream/modules/eda/proc-eda-enable-rulebook-activations.adoc, downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc, downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc, downstream/modules/eda/proc-eda-set-up-new-project.adoc, downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc, downstream/modules/eda/proc-eda-set-up-token.adoc, downstream/modules/eda/proc-eda-test-with-K8s.adoc
Adding step on how to generate a token and correcting document IDs.
Documentation lacking on token generation for EDA.
https://issues.redhat.com/browse/AAP-13749
Affects `titles/eda-user-guide`
=> Adding clarity on how to add token

downstream/modules/eda/proc-eda-activate-webhook.adoc, downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc, downstream/modules/eda/proc-eda-enable-rulebook-activations.adoc, downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc, downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc, downstream/modules/eda/proc-eda-set-up-new-project.adoc, downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc, downstream/modules/eda/proc-eda-set-up-token.adoc, downstream/modules/eda/proc-eda-test-with-K8s.adoc
Adding step on how to generate a token and correcting document IDs. 
Documentation lacking on token generation for EDA. 
https://issues.redhat.com/browse/AAP-13749
=> Adding clarity on how to add token (#1188)

downstream/attributes/attributes.adoc
Create attribute for install version
https://issues.redhat.com/browse/AAP-13789
=> Created Attribute

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc, downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc, downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
Adding steps on how to build a custom decision environment for EDA
Document how to build and publish a decision environment image
https://issues.redhat.com/browse/AAP-9547
Affects `titles/eda-user-guide`
=> Building a custom decision environment steps

downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc, downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc, downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
Adding steps on how to build a custom decision environment for EDA
Document how to build and publish a decision environment image
https://issues.redhat.com/browse/AAP-9547
Affects titles/eda-user-guide
=> Backport 2.4 1169 Building a custom decision environment steps

downstream/modules/navigator/con-about-ansible-navigator.adoc
This PR addresses JIRA issue: https://issues.redhat.com/browse/AAP-442. 
Changes made:
- Removed incorrect info. 
- Made a formatting change - added the last sentence of the para as a bulleted point.
=> AAP-442: Corrected the uses of Ansible Navigator

downstream/modules/navigator/con-about-ansible-navigator.adoc
Backport Ansible Navigator content updates (PR #1206) from main to 2.2 release branch.
=> Backport pull request #1206 from main to 2.2

downstream/modules/navigator/con-about-ansible-navigator.adoc
Backport Ansible Navigator content updates (PR #1206) from main to 2.4 release branch.
=> Backport pull request #1206 from main to 2.4

downstream/assemblies/platform/assembly-system-requirements.adoc
Adds requirements for user privilege escalation and de-escalation in the Planning Guide. 
See [AAP-13831](https://issues.redhat.com/browse/AAP-13831) for more info.
=> AAP-13831 Clarifies user privilege requirements in Planning Guide

downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc, downstream/modules/platform/ref-standalone-hub-inventory.adoc
This PR backports the doc update PR #1217 to AAP v2.2. 
JIRA: 
[AAP-433](https://issues.redhat.com/browse/AAP-433): Remove loopback address in automation hub inventory example
=> 2.2 Backport PR #1217 to AAP v2.2

downstream/modules/dev-guide/proc-downloading-base-ees.adoc
This PR backports PR #1218  from main to AAP v2.1.
=> Backport PR #1218 to AAP v2.1

downstream/modules/platform/ref-system-requirements.adoc
This PR addresses JIRA https://issues.redhat.com/browse/AAP-2133.
Changes made:
- Added specifications for Disk: Database node
- Formatted the info. in a way such that it has a separate CPU, RAM, and DISK requirement (is not listed under hybrid node thereby incorrectly implying that the database resides in hybrid node).
=> AAP-2133: Added specifications for AAP database node

downstream/modules/platform/ref-system-requirements.adoc
Backport PR #1216 to AAP v2.2.
=> Backport pull request #1216 from main to 2.2

downstream/modules/platform/ref-automation-hub-requirements.adoc, downstream/modules/platform/ref-controller-system-requirements.adoc, downstream/modules/platform/ref-postgresql-requirements.adoc, downstream/modules/platform/ref-system-requirements.adoc
* AAP-7916 
* Backports #811 to 2.4
Affects planning guide
=> 2.4 AAP-7916 - Eliminate confusing "disk" terminology references (#811)

downstream/titles/analytics/reports/docinfo.xml
This PR is to address JIRA https://issues.redhat.com/browse/AAP-3051.
Change made:
Updated the abstract "Use the reports feature **on Insights** for Red Hat Ansible Automation Platform to generate an overview report to monitor your automation environment." to "Use the reports feature **within Automation Analytics** to generate an overview report to monitor your automation environment."
Once this PR is approved and merged, I'll create backport PR for AAP v2.4, v2.3, v2.2, and v2.1 doc branches.
=> AAP-3051: Updated Automation Analytics docs product name in the abstract

downstream/modules/platform/ref-controller-system-requirements.adoc
This PR backports PR #1250  from main to AAP v2.4.
=> Backport pull request #1250 from main to AAP v2.4

downstream/modules/platform/ref-controller-system-requirements.adoc
This PR backports PR #1250 from main to AAP v2.3.
=> Backport pull request #1250 from main to AAP v2.3

downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc, downstream/modules/eda/con-about-event-driven-ansible.adoc, downstream/modules/platform/con-about-eda-controller.adoc, downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Use 'use' instead, as per IBM style guide.
Change wording
https://issues.redhat.com/browse/AAP-14494
=> Replace the word 'leverage'

downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc, downstream/modules/eda/con-about-event-driven-ansible.adoc, downstream/modules/platform/con-about-eda-controller.adoc, downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Use 'use' instead, as per IBM style guide.
https://issues.redhat.com/browse/AAP-14494
=> Replace the word 'leverage' (#1257)

downstream/titles/controller/controller-getting-started/docinfo.xml, downstream/titles/controller/controller-getting-started/master.adoc
Edited titles and content in master/doc.xml files
Move the controller quick start guide to the Customer Portal
https://issues.redhat.com/browse/AAP-14115
Affects `titles/controller/controller-getting-started`
=> Editing controller master and doc.xml files

downstream/titles/controller/controller-getting-started/docinfo.xml, downstream/titles/controller/controller-getting-started/master.adoc
* Editing controller master and doc.xml files
Edited titles and content in master/doc.xml files
Move the controller quick start guide to the Customer Portal
https://issues.redhat.com/browse/AAP-14115
Affects `titles/controller/controller-getting-started`
* Editing titles
=> 2.4 Editing controller master and doc.xml files (#1264)

downstream/modules/platform/proc-enable-pods-ref-images.adoc
=> Added edit icon

downstream/modules/platform/proc-enable-pods-ref-images.adoc
=> Added edit icon (#1266)

downstream/modules/platform/proc-enable-pods-ref-images.adoc
=> Replace icon

downstream/modules/platform/proc-enable-pods-ref-images.adoc
=> Replace icon (#1268)

downstream/assemblies/eda/assembly-eda-decision-environments.adoc, downstream/assemblies/eda/assembly-eda-projects.adoc, downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc, downstream/assemblies/eda/assembly-eda-set-up-token.adoc, downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc, downstream/modules/eda/proc-eda-activate-webhook.adoc, downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc, downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc, downstream/modules/eda/proc-eda-enable-rulebook-activations.adoc, downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc, downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc, downstream/modules/eda/proc-eda-set-up-new-project.adoc, downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc, downstream/modules/eda/proc-eda-set-up-token.adoc, downstream/modules/eda/proc-eda-test-with-K8s.adoc, downstream/titles/eda/eda-user-guide/master.adoc
* Updating EDA controller user guide asciidoc
Making necessary changes as per content audit
Updating EDA controller user guide asciidoc elements
https://issues.redhat.com/browse/AAP-13856
Affects `titles/eda-user-guide`
* Modularizing eda-user-guide docs
* Making final minor edits
=> Updating EDA controller user guide asciidoc (#1235)

downstream/modules/platform/proc-aap-activate-with-credentials.adoc
Testing showed that the unicode hex value worked best
=> Replaced attribute with Unicode icon

downstream/modules/platform/proc-aap-activate-with-credentials.adoc
Testing showed that the unicode hex value worked best
=> Replaced attribute with Unicode icon (#1270)

downstream/modules/platform/proc-aap-activate-with-credentials.adoc
No attribute to replace so replaced it directly
=> Replace settings icon with unicode image

downstream/assemblies/navigator/assembly-intro-navigator.adoc
This change updates Chapter 1 text to automation content navigator which was missed in the first round of changes for https://issues.redhat.com/browse/AAP-1320.
=> AAP1320 - Update Chapter 1 to automation content navigator

downstream/assemblies/navigator/assembly-intro-navigator.adoc, downstream/titles/navigator-guide/docinfo.xml
This PR backports the change for #1279 to the 2.3 branch.
=> [Backport] - AAP1320 - Update Chapter 1 to automation content navigator (#1279)

downstream/assemblies/navigator/assembly-intro-navigator.adoc
This PR backports the changes for #1279 to the 2.4 branch.
=> [Backport] AAP1320 - Update Chapter 1 to automation content navigator (#1279)

downstream/assemblies/platform/assembly-platform-install-scenario.adoc
removed incorrect information
[DOC]-Installing Red Hat Ansible Automation Platform has misleading information.
https://issues.redhat.com/browse/AAP-14648
=> Removed Note

downstream/assemblies/platform/assembly-platform-install-scenario.adoc
removed incorrect information
[DOC]-Installing Red Hat Ansible Automation Platform has misleading information.
https://issues.redhat.com/browse/AAP-14648
=> Removed Note (#1284)

downstream/modules/platform/proc-create-password-hashes.adoc
* Separate steps in procedure
Made one step into  two
[DDF] Running this step as listed on RHEL 9.2 running AAP 2.4 did not work. However, breaking it into two steps were I first
https://issues.redhat.com/browse/AAP-14866
* Separate steps in procedure
Correction
[DDF] Running this step as listed on RHEL 9.2 running AAP 2.4 did not work. However, breaking it into two steps were I first
https://issues.redhat.com/browse/AAP-14866
=> Separate steps in procedure (#1299)

downstream/modules/platform/ref-converting-playbook-examples.adoc
This is a backport for PR 1301 to v2.4 of the Upgrade and Migration guide. JIRA reference is [AAP-14883](https://issues.redhat.com/browse/AAP-14883).
=> AAP-14883 add URL to link reference

downstream/assemblies/hub/assembly-collection-import-export.adoc, downstream/assemblies/hub/assembly-remote-management.adoc, downstream/assemblies/hub/assembly-repo-management.adoc, downstream/assemblies/hub/assembly-repo-sync.adoc, downstream/modules/automation-hub/con-approval-pipeline.adoc, downstream/modules/automation-hub/proc-adding-collections-repository.adoc, downstream/modules/automation-hub/proc-basic-repo-sync.adoc, downstream/modules/automation-hub/proc-create-remote.adoc, downstream/modules/automation-hub/proc-create-repository.adoc, downstream/modules/automation-hub/proc-export-collection.adoc, downstream/modules/automation-hub/proc-import-collection.adoc, downstream/modules/automation-hub/proc-provide-remote-access.adoc, downstream/modules/automation-hub/proc-provide-repository-access.adoc, downstream/modules/automation-hub/proc-revert-repository-version.adoc, downstream/titles/hub/repo-management/docinfo.xml, downstream/titles/hub/repo-management/master.adoc
This PR incorporates the improvements suggested in the crowdsourced minimalism review performed on the content. Changes are being tracked in https://issues.redhat.com/browse/AAP-14045:
Link to preview draft (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP14045/master.html
=> AAP-14045 - Incorporating crowdsourced minimalism review changes (P1)

downstream/assemblies/hub/assembly-collection-import-export.adoc, downstream/assemblies/hub/assembly-remote-management.adoc, downstream/assemblies/hub/assembly-repo-management.adoc, downstream/assemblies/hub/assembly-repo-sync.adoc, downstream/modules/automation-hub/con-approval-pipeline.adoc, downstream/modules/automation-hub/proc-adding-collections-repository.adoc, downstream/modules/automation-hub/proc-basic-repo-sync.adoc, downstream/modules/automation-hub/proc-create-remote.adoc, downstream/modules/automation-hub/proc-create-repository.adoc, downstream/modules/automation-hub/proc-export-collection.adoc, downstream/modules/automation-hub/proc-import-collection.adoc, downstream/modules/automation-hub/proc-provide-remote-access.adoc, downstream/modules/automation-hub/proc-provide-repository-access.adoc, downstream/modules/automation-hub/proc-revert-repository-version.adoc, downstream/titles/hub/repo-management/docinfo.xml, downstream/titles/hub/repo-management/master.adoc
This PR backports the changes from #1220 to the 2.4 branch.
=> [Backport] AAP-14045 - Incorporating crowdsourced minimalism review changes (P1)
