RedHatInsights/red-hat-ansible-automation-platform-documentation

doc/modules/con_Adding_sources.adoc
doc/modules/proc_Adding_ansible_tower_source.adoc

Updating workflow for adding Ansible Tower source. This PR:
- Adds context to why an org adds a source
- Adds context to adding Ansible Tower
- Up-to-date with UI Ansible Tower source workflow
- Removes Receptor related features from catalog-specific source workflow

update ansible tower add source workflow

---

doc/modules/con_Assigning_approval_workflow.adoc
doc/modules/con_Editing_portfolios.adoc
doc/modules/proc_Assigning_approval_workflow.adoc
doc/modules/proc_Editing_portfolios.adoc

This PR updates the edit portfolio workflow:
1. Editing Portfolios is limited to the current state of edit -> change name and description.
2. Set approval process description is updated and the procedure for applying an approval process to a portfolio is now current.

Update edit portfolios

---

downstream/assemblies/navigator/assembly-installing-on-rhel.adoc
downstream/modules/navigator/proc-installing-navigator-rhel-pip.adoc
downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
downstream/modules/navigator/proc-installing-navigator-rhel-tar.adoc

At this point, only pip install is supported. Leave the other two procedures in the repo but not in the assembly. (as in they won't show up in the documentation for now).

Install navigator

---

README.adoc

Updated the following links in README.adoc:
- mod-docs reference guide: linked to the build, not the mod-docs repo
- templates for modular docs
- Asciidoc conventions

README: Update links to mod-docs guide, templates, asciidoc guide

---

downstream/modules/builder/proc-customize-ee-image.adoc

Per: https://issues.redhat.com/browse/AAP-396
Also updated sec 4.3 -> step 7 on pushing image to the automation hub container registry.

AAP 396 Remove references to quay.io and replace with registry.redhat.io

---

downstream/assemblies/catalog/assembly-itsm-substitution.adoc
downstream/modules/builder/con-definition-dependencies.adoc
downstream/modules/builder/proc-customize-ee-image.adoc
downstream/modules/catalog/proc-edit-set-stats.adoc
downstream/modules/dev-guide/proc-create-playbooks.adoc
downstream/modules/security/proc-creating-firewall-rule.adoc
downstream/modules/security/proc-deleting-firewall-rule.adoc

Ansible does not make use of multiple YAML documents, so the document separator can be omitted from examples.
Update descriptions of basic playbook components to be more accurate and avoid the use of latin phrases.

Update YAML examples and play description

---

downstream/modules/catalog/proc-preparing-worker-installer.adoc

This PR fixes the markdown used in the procedure and removes the Additional Resources template text.
Preview here: http://file.rdu.redhat.com/cbudzilo/worker/build/tmp/en-US/html-single/

Correct markdown in procedures

---

downstream/attributes/attributes.adoc

Platform operator concept content - describes the Platform Operator that deploys Automation Platform on OpenShift.
- Attribute values for operator per [Ansible Automation Platform product component and feature naming](https://docs.google.com/spreadsheets/d/1l8YLUY-AFHYgxQKNe2NvRtk85-MenYcr-BaMAYFZjfs/edit#gid=0) Google Sheet
- The Platform operator modules and assemblies are in the `platform` directories
- This PR affects the `/titles/aap-operator-installation` book.

Platform operator concept content

---

downstream/assemblies/platform/assembly-installing-controller-operator-external-db.adoc
downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc
downstream/titles/aap-operator-installation/master.adoc

First draft of the platform operator installation procedures on OpenShift. I edited some of the assemblies that were created previously to reflect the TLS secrets and Ingress configurations in the form view. This draft encompasses both hub and controller installations.
Preview (VPN required to view): http://file.rdu.redhat.com/kevchin/operator/operator-procs/tmp/en-US/html-single/
Note: These drafts only reflect some of the installation scenarios we were tasked to do. Once we get a clearer understanding on how the procedures change on a external/local database, we can add those later.

First draft of operator install procedures

---

downstream/assemblies/dev-guide/assembly-creating-content.adoc
downstream/modules/automation-hub/con-about-automation-hub.adoc
downstream/modules/core/con-ansible-roles.adoc
downstream/modules/core/con-content-collections.adoc
downstream/modules/core/con-execution-environments.adoc
downstream/modules/dev-guide/proc-create-collections.adoc
downstream/modules/dev-guide/proc-create-role.adoc

Standalone roles while still supported should be de-emphasized. Instead, creating roles inside of collections is the recommended approach.
Correct some problems with the example collections layout and add some more example content.

Updates to docs around roles and collections

---

downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/attributes/attributes.adoc

Affects Operator installation title: downstream/titles/aap-operator-installation/master.adoc
Backported the following commits, comprising PR#155,  from the `AAP-516-operator-install-guide` feature branch to the `2.0-ea` release branch:
```
8624621 (origin/platform-operator-concept) Implement review comment
0335f55 Apply suggestions from review
b2f770e Add Platform operator concept content
c448f32 Update attribute values for operator components
```

Backport PR#155 from AAP-516 feature branch to 2.0-ea

---

downstream/assemblies/dev-guide/assembly-creating-content.adoc
downstream/modules/automation-hub/con-about-automation-hub.adoc
downstream/modules/core/con-ansible-roles.adoc
downstream/modules/core/con-content-collections.adoc
downstream/modules/core/con-execution-environments.adoc
downstream/modules/dev-guide/proc-create-collections.adoc
downstream/modules/dev-guide/proc-create-role.adoc

Update roles and collections content in dev guide  (PR #142) from master to 2.0-ea release branch
Affects Dev Guide: /downstream/titles/dev-guide/master.adoc
* Remove duplicate period
* Correct command for install standalone role
* Update example collection directory structure
- use trailing '/' to inidicate a directory
- correct plugin directory names
* Correct display of content about Automation Hub
Leading spaces make this show up as a code block.
* Improve description of EEs and their content
* Move role creation above collection creation
Since we want to emphasize the creation of roles within collections, it is
less confusing to the user to first discuss creating a collection, then
how to create roles.
* Improve role description
* Update documentation to describe how to create roles …

Backport PR#142 from main branch to 2.0-ea release branch

---

downstream/assemblies/platform/assembly-installing-controller-operator-external-db.adoc
downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc
downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/con-ocp-supported-install.adoc
downstream/modules/platform/con-operator-additional-resources.adoc
downstream/modules/platform/con-operator-custom-resources.adoc
downstream/modules/platform/proc-access-hub-operator-ui.adoc
downstream/modules/platform/proc-controller-ingress-options.adoc
downstream/modules/platform/proc-controller-route-options.adoc
downstream/modules/platform/proc-hub-ingress-options.adoc
downstream/modules/platform/proc-hub-route-options.adoc
downstream/modules/platform/proc-install-aap-operator.adoc

Modularized the aap operation installation content that we have prior to SME feedback.
Preview here  (VPN required): http://file.rdu.redhat.com/kevchin/operator/operator-procs2/tmp/en-US/html-single/
Files added to the following assemblies:
- assembly-operator-install-planning.adoc
-- platform/con-about-operator.adoc
-- platform/con-ocp-supported-install.adoc
-- platform/con-operator-custom-resources.adoc
-- platform/con-operator-additional-resources.adoc
- assembly-installed-hub-operator-external.adoc
-- platform/proc-install-aap-operator.adoc
-- platform/proc-hub-route-options.adoc
-- platform/proc-hub-ingress-options.adoc
-- platform/proc-access-hub-operator-ui.adoc
- assembly-installing-controller-operator-external.adoc
-- platform/proc-install-aap-operator.adoc
-- …

Modularize existing aap operator installation content

---

downstream/assemblies/platform/assembly-installing-controller-operator-external-db.adoc
downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc
downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/con-ocp-supported-install.adoc
downstream/modules/platform/con-operator-additional-resources.adoc
downstream/modules/platform/con-operator-custom-resources.adoc
downstream/modules/platform/proc-access-hub-operator-ui.adoc
downstream/modules/platform/proc-controller-ingress-options.adoc
downstream/modules/platform/proc-controller-route-options.adoc
downstream/modules/platform/proc-hub-ingress-options.adoc
downstream/modules/platform/proc-hub-route-options.adoc
downstream/modules/platform/proc-install-aap-operator.adoc

Modularized the aap operation installation content that we have prior to SME feedback.
Preview here (VPN required): http://file.rdu.redhat.com/kevchin/operator/operator-procs2/tmp/en-US/html-single/
Files added to the following assemblies:
assembly-operator-install-planning.adoc
-- platform/con-about-operator.adoc
-- platform/con-ocp-supported-install.adoc
-- platform/con-operator-custom-resources.adoc
-- platform/con-operator-additional-resources.adoc
assembly-installed-hub-operator-external.adoc
-- platform/proc-install-aap-operator.adoc
-- platform/proc-hub-route-options.adoc
-- platform/proc-hub-ingress-options.adoc
-- platform/proc-access-hub-operator-ui.adoc
assembly-installing-controller-operator-external.adoc
-- platform/proc-install-aap-operator.adoc
-- …

Backport PR#161 from AAP-516 feature branch to 2.0 ea (Modularize Operator installation content)

---

downstream/assemblies/central-auth/assembly-assign-hub-admin-permissions.adoc
downstream/assemblies/central-auth/assembly-central-auth-add-user-storage.adoc
downstream/assemblies/central-auth/assembly-central-auth-group-perms.adoc
downstream/assemblies/central-auth/assembly-central-auth-hub.adoc
downstream/assemblies/central-auth/assembly-central-auth-identity-broker.adoc
downstream/assemblies/central-auth/assembly-install-central-auth-hub.adoc
downstream/assemblies/central-auth/automation-hub
downstream/assemblies/central-auth/central-auth
downstream/assemblies/central-auth/platform
downstream/attributes/attributes.adoc
downstream/modules/central-auth/con-central-auth-reqs.adoc
downstream/modules/central-auth/platform
downstream/modules/central-auth/proc-aap-configure-centralauth.adoc
downstream/modules/central-auth/proc-login-centralauth.adoc
downstream/modules/central-auth/proc-running-aap-install.adoc
downstream/titles/central-auth/attributes
downstream/titles/central-auth/central-auth
downstream/titles/central-auth/docinfo.xml
downstream/titles/central-auth/master.adoc

The first complete draft of the AAP central authentication guide (formerly the SSO docs)
Preview: http://file.rdu.redhat.com/kevchin/centralauth/build/tmp/en-US/html-single/
Relevant Jira tickets: https://issues.redhat.com/browse/AAH-892 , https://issues.redhat.com/browse/AAP-414

AAP - Central Authentication Install and Configuration Docs

---

downstream/assemblies/platform/assembly-example-topologies.adoc
downstream/assemblies/platform/assembly-installing-automation-mesh.adoc
downstream/assemblies/platform/assembly-migrating-to-mesh.adoc
downstream/modules/platform/con-automation-mesh-node-types.adoc
downstream/modules/platform/con-control-execution-planes.adoc
downstream/modules/platform/ref-complex-mesh-topology.adoc
downstream/titles/automation-mesh/master.adoc

This update revises the description of the control and execution plane, nesting the node types beneath those descriptions. 
The complex mesh design is also updated to unify the example node types as they appear in all other reference inventory files, as suggested by Roger Lopez. 
Preview: http://file.rdu.redhat.com/cbudzilo/mesh/build/tmp/en-US/html-single/#ref-complex-mesh-topology

Revise mesh plane desciptions and complex example

---

downstream/modules/catalog/proc-preparing-worker-installer.adoc

@TarikFD  would you mind taking a look and approving this PR?
Fixing  typo in the Catalog worker installation doc per [AAP-1222](https://issues.redhat.com/browse/AAP-1222)
Preview: http://file.rdu.redhat.com/cbudzilo/worker/build/tmp/en-US/html-single/

Fix typo in worker module

---

downstream/assemblies/platform/assembly-upgrading-to-aap.adoc
downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
downstream/modules/platform/proc-running-setup-script-for-updates.adoc
downstream/titles/upgrade/docinfo.xml

Fixed several issues relating to the [AAP upgrade guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_upgrade_and_migration_guide/index):
Issue 1: Broken link to the jira page ([AAP-1397](https://issues.redhat.com/browse/AAP-1397))
- Fixed a broken link in docinfo.xml . Link works in the preview now.
Issue 2: Incomplete and wrong modules linked in the upgrade guide ([AAP-1594](https://issues.redhat.com/browse/AAP-1594))
- The current docs links to irrelevant modules from 1.3-1.4, and the guide is incomplete as a result. Added proper content about how to upgrade using the AAP installer, using information as gathered from productization team. 
Please see my changes and feel free to leave any feedback.
Preview …

Platform - Fixes to platform upgrade docs

---

downstream/assemblies/platform/assembly-installing-controller-operator-external-db.adoc
downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc

Problem was that old link linked to a specific version of the OCP product docs. Changed the paragraph so that the link led to the main product docs splash page, but included text to instruct users to find the operator docs so it'll always show the latest version.
Jira issue: https://issues.redhat.com/browse/AAP-1398

AAP-1398: Update link to operator product docs link

---

downstream/assemblies/platform/assembly-standalone-controller-ext-database.adoc
downstream/assemblies/platform/assembly-standalone-controller-non-inst-database-installation.adoc
downstream/assemblies/platform/assembly-standalone-hub-ext-database.adoc
downstream/assemblies/platform/assembly-standalone-hub-non-inst-database.adoc
downstream/modules/platform/ref-additional-inv-configs.adoc
downstream/modules/platform/ref-setup-script-args.adoc

JIRA request: https://issues.redhat.com/browse/AAP-1620
Adds content about enabling api logs to an AAP install. In doing so, added a reference module to house any future configurations to the inventory file.
See section 2.1.4, 2.2.4, etc. of the preview link below
Preview link (VPN required): http://file.rdu.redhat.com/kevchin/installer2/tmp/en-US/html-single/#additional_inventory_file_variables

AAP Installer - Enable API-access Logs + installer config module

---

downstream/titles/automation-mesh/master.adoc

**Problem:**
At the end of the preface in the [Automation Mesh Guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_automation_mesh_guide/pr01), an artefact from Asciidoc (`:leveloffset:+1`) is visible in the published docs.
We think this is caused by a hidden character in the blank line between the preface and the first included assembly.
**Solution:**
Deleted the blank line and added in another one.
Also added a blank line at the end of of the doc, as Git didn't detect a diff when the blank line that was causing the problem was replaced.
Before:
After:

bugfix: Asciidoc artefact visible in rendered Automation Mesh guide

---

downstream/modules/dev-guide/proc-create-playbooks.adoc

Jira request: https://issues.redhat.com/browse/AAP-397
Replaced use of `awx.awx` with `ansible.controller` in the AAP creator guide.
Titles affected: `/titles/dev-guide`

AAP 2.0 - Dev Creator Guide: Replaced awx with ansible.controller

---

downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc

Jira issue: https://issues.redhat.com/browse/AAP-1733
Updated navigator instructions to download 2.1 version, rather than 2.0 ea
Titles affected: titles/navigator-guide

AAP-1733 Update navigator example to 2.1 version

---

downstream/assemblies/platform/assembly-upgrading-to-aap.adoc
downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
downstream/titles/upgrade/master.adoc

Issue link: https://issues.redhat.com/browse/AAP-1337
Developed procedure on upgrading AAP to a later version. 
Preview link (VPN required): http://file.rdu.redhat.com/kevchin/upgrade/tmp/en-US/html-single/

AAP-1337: AAP upgrade guide

---

downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
downstream/assemblies/platform/assembly-installing-hub-operator-external-db.adoc
downstream/attributes/attributes.adoc
downstream/modules/platform/con-ocp-supported-install.adoc
downstream/modules/platform/proc-cli-get-controller-pwd.adoc
downstream/modules/platform/proc-install-cli-aap-operator.adoc
downstream/titles/aap-operator-installation/docinfo.xml
downstream/titles/aap-operator-installation/master.adoc

**Jira issue:**
[AAP-597](https://issues.redhat.com/browse/AAP-597): Document how to call operator to install without using OCP UI
**Build preview:**
http://file.emea.redhat.com/~ariordan/docs/aap-operator-cli/build/tmp/en-US/html-single/
**Summary:**
Add instructions to the _RHAAP Operator Installation Guide_  describing how to install the AAP Operator using the OpenShift  CLI (`oc`)
so that
Users who do not have access to the OperatorHub on the OpenShift web console can install the AAP operator.
**Title affected:** 
`titles/aap-operator-installation/`
**Reference:** 
[Operators guide](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/operators/user-tasks#olm-installing-operator-from-operatorhub-using-cli_olm-installing-operators-in-namespace) in …

AAP-597 Add procedure to install AAP operator on CLI 

---

downstream/assemblies/platform/assembly-configure-known-proxies.adoc
downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
downstream/modules/platform/con-known-proxies.adoc
downstream/modules/platform/proc-configure-known-proxies.adoc
downstream/modules/platform/proc-configuring-reverse-proxy.adoc
downstream/modules/platform/proc-enable-proxy-support.adoc

AAP 2.1 installer docs contain outdated proxy support content that needs updating, as well as two other fixes
Jira ticket: (Main issue) https://issues.redhat.com/browse/AAP-1939, (Bug fix 1) https://issues.redhat.com/browse/AAP-1634, (Bug fix 2) https://issues.redhat.com/browse/AAP-1680
Preview link (VPN required, See **section 5** of this doc) http://file.rdu.redhat.com/kevchin/proxy_update/tmp/en-US/html-single/#assembly-configuring-proxy-support

AAP-1939: Update proxy support docs on AAP installer

---

downstream/modules/automation-hub/proc-set-community-remote.adoc

Jira issue: https://issues.redhat.com/browse/AAP-1625
Update a broken link. To be backported to the 1.0 version of the docs.
Titles affected: `hub/configuring-private-hub-rh-certified`

AAP-1625: (1.0) Update broken hub link

---

downstream/modules/automation-hub/proc-set-community-remote.adoc

Jira issue: https://issues.redhat.com/browse/AAP-1625
Update a broken link. To be backported to the *1.2* version of the docs.
Titles affected: `hub/configuring-private-hub-rh-certified`

AAP-1625: (1.2) Update broken hub link

---

downstream/titles/hub/lifecycle/master.adoc

https://issues.redhat.com/browse/AAP-1740
Update the [lifecycle doc for automation hub](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/private_automation_hub_life_cycle/life_cycle_dates).
Automation hub version 4.4.0 is shipped with with AAP 2.1

AAP-1740 Update hub version in hub lifecycle doc

---

release-notes/master.adoc
release-notes/topics/aap-21.adoc
release-notes/topics/platform-intro.adoc

**Issue:**
[Jira AAP-2130](https://issues.redhat.com/browse/AAP-2130)
The `2.1` branch in the AAP docs repo includes the [AAP 2.1 release notes](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_release_notes/anchor-december-2021-release).
The `master` branch in the AAP docs repo does not include the AAP 2.1 release notes.
**Action:** 
Add the 2.1 release notes to the main branch.

AAP-2130 Copy 2.1 release notes to master branch from 2.1 branch

---

downstream/modules/platform/proc-attaching-subscriptions.adoc
downstream/titles/aap-installation-guide/docinfo.xml

Jira: https://issues.redhat.com/browse/AAP-1731
Requirements have been updating so that all nodes require a red hat subscription for the AAP installer to work. Edited the concept module to clarify this point, and added a troubleshooting step at the end as per Satoe's notes.
See section 1.3 of the preview below
Preview link (VPN required): http://file.rdu.redhat.com/kevchin/aap_sub/tmp/en-US/html-single/#proc-attaching-subscriptions_planning
Titles affected: `titles/aap-installation-guide`

AAP-1731 Clarifying subscriptions requirements for installing AAP

---

downstream/modules/platform/proc-attaching-subscriptions.adoc

Jira request: https://issues.redhat.com/browse/AAP-1637
Added a note in the aap installer > subscriptions section regarding enabling simple content access, some background info, and a link to the procedures on enabling it. 
Titles affect: `titles/aap-installation-guide`

AAP-1637 Added note about enabling Simple Content Access

---

downstream/assemblies/platform/assembly-installing-controller-operator-local-db.adoc
downstream/assemblies/platform/assembly-installing-controller-operator.adoc
downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/modules/platform/con-operator-additional-resources.adoc
downstream/titles/aap-operator-installation/docinfo.xml
downstream/titles/aap-operator-installation/master.adoc

Jira: https://issues.redhat.com/browse/AAP-1856
Received a suggestion to remove references to external dbs until we figure the steps to connect an external db before a hub/controller operator install. 
Also added modules that were omitted from the previous publish cycle, as well as a fix to docinfo.xml
Preview link (VPN required): http://file.rdu.redhat.com/kevchin/operator2/tmp/en-US/html-single/
Titles affected: `titles/aap-operator-installation`

AAP-1856 Fixed AAP operator install doc titles for clarity

---

downstream/titles/security-guide/docinfo.xml

Jira: https://issues.redhat.com/browse/AAP-743
- Fixed the broken link in the docinfo.xml file. Should be `<link xlink:href="https://issues.redhat.com"></link>.`
- Revised subtitle to describe the purpose of the guide.

AAP-743: Revised subtitle and fixed broken jira link

---

downstream/assemblies/hub/assembly-user-access.adoc
downstream/assemblies/hub/assembly-view-only-access.adoc
downstream/modules/automation-hub/con-enable-view-only.adoc
downstream/titles/hub/managing-user-access/docinfo.xml
downstream/titles/hub/managing-user-access/master.adoc

Jira Ticket: https://issues.redhat.com/browse/AAH-920 
Hub allows for a view-only mode for unauthorized users (not logged in) to view collections and namespaces but not download or edit anything on hub. This PR adds content to the "user access" title about enabling and verifying view-only mode.
Technical verification is still pending for QE review, but while QE is working through their backlog, we'll merge this first and add any necessary changes at a later date.
Preview (VPN required): http://file.rdu.redhat.com/kevchin/viewonly-redo/tmp/en-US/html-single/
Titles affected: `titles/hub/managing-user-access`

AAH-920 Hub view-only mode

---

downstream/modules/automation-hub/proc-push-container.adoc

Jira issue: https://issues.redhat.com/browse/AAP-1799
When dealing with images from registry.redhat.io , users need to include a `--remove-signatures` flag in order for the `podman push` command to work. Updated the command on the docs plus a note briefly explaining the need for the flag.
See section 3.4 in the preview below
Preview (VPN required): http://file.rdu.redhat.com/kevchin/manage-containers/tmp/en-US/html-single/#push-containers

AAP-1799 Update podman push command when pushing registry images

---

downstream/modules/platform/ref-complex-mesh-topology.adoc

Jira: https://issues.redhat.com/browse/AAP-2030
Fixed a typo found in an example in the mesh guide

AAP-2030 Fix typo in mesh guide example

---

downstream/assemblies/hub/assembly-container-user-access.adoc
downstream/assemblies/hub/assembly-delete-container.adoc
downstream/modules/automation-hub/proc-add-container-readme.adoc
downstream/modules/automation-hub/proc-add-group-to-container-repo.adoc
downstream/modules/automation-hub/proc-add-user-to-group.adoc
downstream/modules/automation-hub/proc-assigning-permissions.adoc
downstream/modules/automation-hub/proc-create-groups.adoc
downstream/modules/automation-hub/proc-delete-container.adoc
downstream/modules/automation-hub/proc-obtain-images.adoc
downstream/modules/automation-hub/proc-pull-image.adoc
downstream/modules/automation-hub/proc-push-container.adoc
downstream/modules/automation-hub/proc-tag-image.adoc
downstream/modules/automation-hub/proc-tag-pulled-image.adoc
downstream/modules/automation-hub/ref-container-permissions.adoc
downstream/titles/hub/manage-containers/docinfo.xml

Jira: https://issues.redhat.com/browse/AAP-2054
Ticket pointed out an error in a procedure in the "Managing containers in private automation hub" title that was caused by UI changes. I noticed a few other procedures that were affected as well, so I went ahead and updated those:
Preview link (VPN required): http://file.rdu.redhat.com/kevchin/hub_containers2/tmp/en-US/html-single/
Title affected: `titles/hub/manage-containers`

AAP-2054 Updating procedures regaring managing containers in private hub

---

downstream/modules/platform/ref-system-requirements.adoc

Jira ticket: https://issues.redhat.com/browse/AAP-1865
Updated the supported RHEL version of the 2.0ea AAP installer to the correct 8.3 version

(2.0) AAP-1865 Update supported RHEL version in installer docs

---

downstream/modules/automation-hub/ref-permissions.adoc

Jira: https://issues.redhat.com/browse/AAP-2163
The permissions table for automation hub needed to include new permissions as seen in the latest build of automation hub, including content deletion as well as container and task related permissions. 
See section 1.8 of the preview link below for the updated table.
Preview link (VPN required): http://file.rdu.redhat.com/kevchin/hub-permissions/tmp/en-US/html-single/#ref-permissions

AAP-2163 Added new hub permissions 

---

downstream/modules/automation-hub/proc-delete-user.adoc

Debugging: assembly including procedure containing an image is omitted from Pantheon builds, though local build is ok.

Delete inline image from hub delete-user procedure

---

downstream/modules/automation-hub/proc-delete-user.adoc

Procedure containing an inline image is omitted from Pantheon builds, though local build is ok.

Delete inline image from hub delete-user procedure (#268)

---

release-notes/docinfo.xml
release-notes/master.adoc
release-notes/topics/aap-126.adoc
release-notes/topics/aap-211.adoc
release-notes/topics/controller-411.adoc
release-notes/topics/hub-441.adoc
release-notes/topics/platform-intro.adoc
release-notes/topics/upgrading.adoc

Jira: https://issues.redhat.com/browse/AAP-1862
Added release notes for the current latest release of AAP and it's components, consisting of AAP 2.1.1, automation hub 4.4.1, and automation controller 4.1.1 .
Also retroactively added release notes for AAP 1.2.6, as requested in https://issues.redhat.com/browse/AAP-2124 
Preview link (VPN required): http://file.rdu.redhat.com/kevchin/release-notes-feb2022/build/tmp/en-US/html-single/

AAP-1862 Release notes for AAP January and February 2022 release

---

downstream/modules/automation-hub/proc-delete-user.adoc
downstream/modules/controller/proc-controller-delete-user.adoc

Add instructions to delete user accounts from controller so that customers know how to delete users' private information.
The module currently is not included in any doc title.
Adding it to the controller module directory as it's a Privacy Information requirement for Ansible on Azure. The content will appear in the controller docs user guide on docs.ansible.com, but we may need to have the information in the downstream repo.
Jira: [AAP-2389](https://issues.redhat.com/browse/AAP-2389)

aap-2389 Add delete user module to controller

---

downstream/titles/snippets/docinfo-feedback.xml

Added the directory `downstream/titles/snippets` containing the text file named `docinfo-feedback.xml`. 
Due to the outdated text in the feedback section of every AAP title, writers need to replace that text with clearer and accurate instructions about leaving feedback on AAP docs. To aid with this, I created a text file called `docinfo-feedback.xml` that has text that writers can use to paste into the `docinfo.xml` of the title they're working on. 
The new feedback section reads:
>  If you have a suggestion to improve this documentation, or find an error, please contact technical support at https://access.redhat.com to create an issue on the Ansible Automation Platform Jira project using the Docs component.

Added text file for writers to replace outdated feedback section in docinfo.xml

---

downstream/assemblies/platform/assembly-installing-controller-operator-local-db.adoc
downstream/assemblies/platform/assembly-installing-controller-operator.adoc
downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/modules/platform/con-operator-additional-resources.adoc
downstream/titles/aap-operator-installation/docinfo.xml
downstream/titles/aap-operator-installation/master.adoc

Backport [PR#249](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/249) to 2.1

AAP-1856 Operator guide removed reference to external db for clarity (#249)

---

downstream/modules/platform/con-operator-additional-resources.adoc
downstream/modules/platform/proc-install-aap-operator.adoc

Fixed a grammar error and a formatting error.
Affects operator doc section [2.2](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_operator_installation_guide/installing-hub-operator#installing_the_automation_hub_operator) and [1.4](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_operator_installation_guide/operator-install-planning#con-operator-additional-resources_operator-install-planning).

Fix operator modules

---

downstream/titles/aap-installation-guide/docinfo.xml
downstream/titles/aap-on-azure/docinfo.xml
downstream/titles/aap-operator-installation/docinfo.xml
downstream/titles/analytics/automation-savings-planner/docinfo.xml
downstream/titles/analytics/reports/docinfo.xml
downstream/titles/automation-mesh/docinfo.xml
downstream/titles/builder/docinfo.xml
downstream/titles/central-auth/docinfo.xml
downstream/titles/controller/docinfo.xml
downstream/titles/dev-guide/docinfo.xml
downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
downstream/titles/hub/getting-started/docinfo.xml
downstream/titles/hub/high-availability/docinfo.xml
downstream/titles/hub/install/docinfo.xml
downstream/titles/hub/manage-containers/docinfo.xml
downstream/titles/hub/managing-user-access/docinfo.xml
downstream/titles/hub/obtaining-token/docinfo.xml
downstream/titles/hub/publishing-internal-content/docinfo.xml
downstream/titles/hub/uploading-collections/docinfo.xml
downstream/titles/hub/uploading-internal-collections/docinfo.xml
downstream/titles/migration/docinfo.xml
downstream/titles/navigator-guide/docinfo.xml
downstream/titles/security-guide/docinfo.xml
downstream/titles/upgrade/docinfo.xml
downstream/titles/worker-install/docinfo.xml

[AAP-2853](https://issues.redhat.com/browse/AAP-2853)
Affects all titles that have a Providing Feedback section.
- Update the Providing Feedback section in `docinfo.xml` for all AAP docs: direct customers to raise issues with support.
- Replace the old feedback section with the feedback snippet in `titles/snippets/docinfo-feedback.xml` in the docs repo.
- Backport the updates to 2.1

AAP-2853 Update Providing feedback info

---

downstream/titles/aap-installation-guide/docinfo.xml
downstream/titles/aap-on-azure/docinfo.xml
downstream/titles/aap-operator-installation/docinfo.xml
downstream/titles/analytics/automation-savings-planner/docinfo.xml
downstream/titles/analytics/reports/docinfo.xml
downstream/titles/automation-mesh/docinfo.xml
downstream/titles/builder/docinfo.xml
downstream/titles/central-auth/docinfo.xml
downstream/titles/dev-guide/docinfo.xml
downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
downstream/titles/hub/getting-started/docinfo.xml
downstream/titles/hub/high-availability/docinfo.xml
downstream/titles/hub/install/docinfo.xml
downstream/titles/hub/manage-containers/docinfo.xml
downstream/titles/hub/managing-user-access/docinfo.xml
downstream/titles/hub/obtaining-token/docinfo.xml
downstream/titles/hub/publishing-internal-content/docinfo.xml
downstream/titles/hub/uploading-collections/docinfo.xml
downstream/titles/hub/uploading-internal-collections/docinfo.xml
downstream/titles/migration/docinfo.xml
downstream/titles/navigator-guide/docinfo.xml
downstream/titles/security-guide/docinfo.xml
downstream/titles/upgrade/docinfo.xml
downstream/titles/worker-install/docinfo.xml

Backport [PR#285](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/285) to 2.1
Jira issue: [AAP-2853](https://issues.redhat.com/browse/AAP-2853)
Affects all titles that have a _Providing Feedback_ section.
Update the _Providing Feedback_ section in `docinfo.xml` for all AAP docs: direct customers to raise issues with support.
Replace the old feedback section with the feedback snippet in `titles/snippets/docinfo-feedback.xml` in the docs repo.

AAP-2853 Update Providing feedback info (#285)

---

downstream/assemblies/platform/assembly-install-aap-operator.adoc
downstream/assemblies/platform/assembly-installing-controller-operator.adoc
downstream/assemblies/platform/assembly-installing-hub-operator.adoc
downstream/modules/platform/proc-install-aap-operator.adoc
downstream/modules/platform/proc-operator-external-db-controller.adoc
downstream/modules/platform/proc-operator-external-db-hub.adoc
downstream/titles/aap-operator-installation/master.adoc

Jira: https://issues.redhat.com/browse/AAP-2328
Added instructions to configure an external database when installing hub/controller on a AAP operator. Also restructured some of the operator content to consolidate procedures. See sections 3.4 and 4.3 in the preview below for the external DB content:
Preview link (VPN required): http://file.rdu.redhat.com/kevchin/operator4/tmp/en-US/html-single/

AAP-2328 Configuring external database for hub/controller on a AAP operator

---

downstream/attributes/attributes.adoc

Adds an attribute called {PlatformVers} that writers can use to always link to the latest version of AAP.

Add an AAP version attribute

---

downstream/attributes/attributes.adoc
downstream/modules/automation-hub/proc-configure-automation-hub-server.adoc
downstream/modules/automation-hub/proc-create-api-token.adoc
downstream/titles/hub/getting-started/docinfo.xml
downstream/titles/hub/getting-started/master.adoc

Jira: [AAP-3018](https://issues.redhat.com/browse/AAP-3018)
Affects the following title:
/hub/getting-started/
Fix the Private Automation Hub server URL in ansible.cfg: Include the /api/galaxy/ subdirectory.
Using the URL from the current docs causes an error.
Preview (requires VPN): http://file.emea.redhat.com/~ariordan/docs/hub-getting-started-220412/build/tmp/en-US/html-single/#proc-configure-automation-hub-server

AAP-3018 Specify subdirectory in server URL for PAH

---

downstream/attributes/attributes.adoc
downstream/modules/automation-hub/proc-configure-automation-hub-server.adoc
downstream/modules/automation-hub/proc-create-api-token.adoc
downstream/titles/hub/getting-started/docinfo.xml
downstream/titles/hub/getting-started/master.adoc

Backport [PR#296](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/296)
Jira: [AAP-3018](https://issues.redhat.com/browse/AAP-3018)
Affects the following title:
/hub/getting-started/
Fix the Private Automation Hub server URL in ansible.cfg: Include the /api/galaxy/ subdirectory.
Using the URL from the current docs causes an error.

AAP-3018 Specify subdirectory in server URL for PAH (#296)

---

downstream/modules/builder/proc-installing-builder.adoc

Jira: [AAP-2423](https://issues.redhat.com/browse/AAP-2423)
- Added prerequisites section with link to ansible-builder repo and subscription info.
- Added note about encountering issues with PyPI install.
Preview link: [2.1 Installing Ansilbe Builder](http://file.rdu.redhat.com/~lmodemal/aap-builder-221304/master.html)
- Needs verification from SME
- Needs peer review

AAP-2423: Add repo info for installing ansible-builder

---

downstream/assemblies/hub/assembly-view-only-access.adoc
downstream/modules/automation-hub/con-enable-view-only.adoc

Jira: https://issues.redhat.com/browse/AAP-3112
Updated the variable for enabling view-only access in automation hub during AAP install.
Changed `GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_ACCESS` to `automationhub_enable_unauthenticated_collection_access` 
Preview (VPN required): http://file.rdu.redhat.com/kevchin/view-only-update/build/tmp/en-US/html-single/#assembly-view-only-access

AAP-3112 Incorrect variable name for view-only Hub

---

downstream/assemblies/hub/assembly-view-only-access.adoc
downstream/modules/automation-hub/con-enable-view-only.adoc

Backport #301 
Jira: https://issues.redhat.com/browse/AAP-3112
Updated the variable for enabling view-only access in automation hub during AAP install.
Changed GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_ACCESS to automationhub_enable_unauthenticated_collection_access
Preview (VPN required): http://file.rdu.redhat.com/kevchin/view-only-update/build/tmp/en-US/html-single/#assembly-view-only-access

AAP-3112 Incorrect variable name for view-only Hub (#301)

---

downstream/modules/builder/proc-installing-builder.adoc

[AAP-2423](https://issues.redhat.com/browse/AAP-2423): Revised instructions to be more accurate.
Local build on backport branch reflected changes in [PR#99](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/299)

AAP-2423: Add repo info for installing ansible-builder (#299)

---

downstream/modules/automation-hub/proc-set-community-remote.adoc

Backport https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/305 to 1.2
- Jira: [AAP-2082](https://issues.redhat.com/browse/AAP-2082): Modify community remote URL
- [Link to original doc on portal](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/1.2/html/managing_red_hat_certified_and_ansible_galaxy_collections_in_automation_hub/assembly-creating-tokens-in-automation-hub#proc-set-community-remote)
Affects `titles/hub/configuring-private-hub-rh-certified`.

Backport PR305 to 1.2

---

downstream/assemblies/platform/assembly-content-migration.adoc
downstream/modules/platform/proc-migrate-playbooks-roles.adoc
downstream/titles/upgrade/master.adoc

**Jira**: Epic [AAP-2346](https://issues.redhat.com/browse/AAP-2346)
This epic has 2 child issues [AAP-2347](https://issues.redhat.com/browse/AAP-2347) and [AAP-2348](https://issues.redhat.com/browse/AAP-2348), which is addressed in this PR - how to migrate playbooks and roles to core 2.12. 
Draft of content, along with comments and revisions from SMEs included in [google doc](https://docs.google.com/document/d/1s4YZh0L6F7lMCIxCD6sWfuCIgPOFEVadFmsx4ahKseA/edit?userstoinvite=gnalawad%40redhat.com&actionButton=1#heading=h.2ntpwbtc7i5p). 
**Preview link**: [Ansible content migration](http://file.rdu.redhat.com/~lmodemal/aap-upgrade-220905/master.html)

Migrating playbooks and roles to Core 2.12

---

CODEOWNERS

When you create a PR, you must manually add reviewers.
This PR creates a CODEOWNERS file in the base directory of this repo.
The PR target branch is `temp-codeowners`.
If merged, then new PRs to this branch should add the team to the default list of reviewers.

Add writers who are members of the org to CODEOWNERS file

---

CODEOWNERS

**Problem:**
When you create a PR to the AAP repo, you have to select reviewers manually. There isn't a way to have the AAP docs team members at the top of the list.
**Solution:**
This PR creates a file called CODEOWNERS in the root directory of the repo.
The file contains a list of GitHub IDs for the writers on the team.
Once merged to `main`, these people will be selected by default in the **Reviewers** list for subsequent PRs to  the `main` branch.
You can add more people as reviewers in your PR.
You can remove people from your PR review list by clicking **Reviewers** and de-selecting them:
I have added the following team members in this PR.
- @ariordan-redhat
- @dcdacosta 
- @ianf77 
- @jself-sudoku
- @lmalivert 
- @oraNod 
- @rogrange 
- @TarikFD
Please approve this PR if you're …

Add AAP docs team members as default reviewers for PRs to main branch

---

.gitignore

Backports #355 
When you build a book using asciidoctor, a master.html file is created in the title directory for the book.
Add master.html to the .gitignore file for the repo so that master.html is not included in PRs.
I didn't use a regular expression for the master.html files because giving the explicit path makes it more obvious which files you want to ignore.

Ignore built master.html files (#355)

---

downstream/modules/automation-hub/con-required-shared-filesystem.adoc
downstream/titles/hub/high-availability/master.adoc

Backporting #330 
Conceptual fixes to the high availability docs to :
- Clarify if HA for private automation hub is an active-active or an active-passive setup.
- Clarify if DNS load balancing is implied
- Specify the requirements for a shared filesystem (NFS or otherwise?)
Preview link (VPN required): http://file.rdu.redhat.com/kevchin/ha_hub3/tmp/en-US/html-single/

[Backport 2.1] AAP-1621 Fixes to HA Hub (#330)

---

downstream/modules/automation-hub/con-required-shared-filesystem.adoc
downstream/titles/hub/high-availability/master.adoc

Backporting #330 
Conceptual fixes to the high availability docs to:
- Clarify if HA for private automation hub is an active-active or an active-passive setup.
- Clarify if DNS load balancing is implied
- Specify the requirements for a shared filesystem (NFS or otherwise?)
Preview link (VPN required): http://file.rdu.redhat.com/kevchin/ha_hub3/tmp/en-US/html-single/

[Backport 2.2] AAP-1621 Fixes to HA Hub (#330)

---

downstream/assemblies/platform/assembly-installing-hub-operator-local-db.adoc
downstream/modules/platform/ref-hub-system-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc
downstream/titles/hub/install/master.adoc

`Gb` means gigabits and is incorrect here whereas `GB` means gigabytes.
Additionally, there should be a space between the quantity and unit (e.g. `2 GB` not `2GB`).
https://redhat-documentation.github.io/supplementary-style-guide/#gb
Closes #360

Replace all Gb with GB for correctness and per style guide.

---

downstream/modules/platform/ref-system-requirements.adoc

Added requirement for Python 3.8 or later to Installation guide.
The Upgrade/Miration Guide has no correspponding requirements section so
that document has been missed out.
Add python requirements for AAP into docs
https://issues.redhat.com/browse/AAP-3385

Added Python requirement to AAP docs

---

downstream/assemblies/platform/assembly-content-migration.adoc
downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
downstream/modules/platform/con-aap-upgrade-prereq.adoc
downstream/modules/platform/con-why-ee.adoc
downstream/modules/platform/proc-new-aap-instance-upgrade.adoc
downstream/modules/platform/proc-upgrade-installer.adoc

Jira: https://issues.redhat.com/browse/AAP-4425
Updating version numbers in the Upgrade & Migration guide to publish as version 2.2 docs. The changes for "AAP 2.1" > "2.2" will change when building the docs in the 2.2 branch, due to the attribute {PlatformVers}
- Change Ansible Core 2.11 to 2.13
- Change Python 3.8 to 3.9
- Change links to 2.1 (we can update the links to 2.2 once the linked docs have been updated to 2.2)

[2.2] AAP-4425 Updating version numbers in Upgrade & Migration guide

---

downstream/modules/platform/proc-install-cli-aap-operator.adoc
downstream/modules/platform/proc-operator-external-db-controller.adoc
downstream/modules/platform/proc-operator-external-db-hub.adoc

Includes the following specified changes from ticket AAP-4426:
- Overall - Change any reference to Ansible Automation Platform 2.1 to 2.2
- 3.3. Configuring an external database for automation controller on Red Hat Ansible Automation Platform operator
- Note: Change the note to say Ansible Automation Platform 2.2 supports PostgreSQL 13
4.4. Configuring an external database for automation hub on Red Hat Ansible Automation Platform operator
- Note: Change the note to say Ansible Automation Platform 2.2 supports PostgreSQL 13
5.2. Subscribing a namespace to an operator using the OpenShift Container Platform CLI
- In the yaml code, change "stable-2.1" to "stable-2.2"

AAP-4426 Updated version #s from 2.1 to 2.2

---

downstream/assemblies/platform/assembly-migrate-platform.adoc
downstream/modules/platform/con-cluster-platform-ext-database.adoc
downstream/modules/platform/con-why-migrate-ansible-core-213.adoc
downstream/modules/platform/proc-attaching-subscriptions.adoc
downstream/modules/platform/ref-system-requirements.adoc

Backporting #388 
Jira Issue: [AAP-4424](https://issues.redhat.com/browse/AAP-4424)
**Overall**
Changed any reference to Ansible Automation Platform 2.1 to 2.2
Changed section with title "Migrating to Ansible Core 2.12" to "Migrating to Ansible Core 2.13"
Changed Ansible Core 2.12 to Ansible Core 2.13
Table 1.1 Base System: Changed PostgreSQL version 12 to PostgreSQL version 13
Table 1.2 Automation hub: Changed PostgreSQL version 12 to PostgreSQL version 13
Notable PostgreSQL: Changed PostgreSQL 12 to PostgreSQL 13
Change PostgreSQL 12 to PostgreSQL 13
1.3 Attaching your Red Hat Ansible Automation Platform subscription:
Troubleshooting section: Changed the command to use -> ansible-automation-platform-2.2-for-rhel-8-x86_64-rpms
Added a similar command for Red Hat Enterprise Linux 9
1.4.7 …

AAP-4424: AAP 2.2 Install Guide Priority Updates (#388)

---

downstream/modules/platform/proc-find-delete-PVCs.adoc

Backports #403 to `2.2`
Fix typo in a module

2.2 Fix typo  (#403)

---

CODEOWNERS

PR #347 was an attempt to populate the list of PR reviewers with a default selection.
It led to confusion: there was no way to deselect members of the default list before an email requesting a review was sent out to everyone.
This PR is an attempt to reduce email noise.
By deleting the CODEOWNERS file from the repo, the **Reviewers** list will not pre-select all AAP docs writers.
We have created a PR review team called `aap-docs-pr-review-group`. So far, Don and Aine are in this team: we want to make sure it works before adding the full team. 
Link to team page: https://github.com/orgs/RedHatInsights/teams/aap-docs-pr-review-group/
If the `CODEOWNERS` file is deleted, then when you create a PR, you can select individual reviewers manually or search for the `aap-docs-pr-review-group` team …

Delete CODEOWNERS file

---

downstream/modules/platform/proc-cli-get-controller-pwd.adoc

Fix password examples in output for `oc get secret` example codeblock in the [Operator Installation guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_operator_installation_guide/installing-aap-operator-cli#fetching_the_automation_controller_password).
Backport to 2.1 and 2.2

Fix password example in codeblock

---

downstream/modules/platform/proc-cli-get-controller-pwd.adoc

Backport #424 
Fix password examples in output for `oc get secret` example codeblock in the [Operator Installation guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_operator_installation_guide/installing-aap-operator-cli#fetching_the_automation_controller_password).

Fix password example in codeblock (#424)

---

downstream/assemblies/builder/assembly-building-off-existing-ee.adoc
downstream/modules/builder/con-pip-based-req.adoc
downstream/modules/builder/proc-installing-builder.adoc

Removed instructions from the builder guide about installing using pip
Remove Instructions on Installing ansible-builder via pip
https://issues.redhat.com/browse/AAP-4086

Removed instructions for installing builder with pip

---

downstream/assemblies/builder/assembly-building-off-existing-ee.adoc
downstream/modules/builder/con-pip-based-req.adoc
downstream/modules/builder/proc-installing-builder.adoc

Removed instructions from the builder guide about installing using pip
Remove Instructions on Installing ansible-builder via pip
https://issues.redhat.com/browse/AAP-4086

2.2 AAP-4086 Removed instructions for installing builder with pip (#427)

---

downstream/assemblies/builder/assembly-building-off-existing-ee.adoc
downstream/modules/builder/con-pip-based-req.adoc
downstream/modules/builder/proc-installing-builder.adoc

Removed instructions from the builder guide about installing using pip
Remove Instructions on Installing ansible-builder via pip
https://issues.redhat.com/browse/AAP-4086

2.1 AAP-4086 Removed instructions for installing builder with pip (#427)

---

downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-ssh-tunnel.adoc

[AAP-4775](https://issues.redhat.com/browse/AAP-4775)
The `ssh` command to establish an SSH tunnel contains an IP address. Replace this with a user-replaced value.
Affects the AAP on Azure guide.

AAP-4775 Add user-replaced value for SSH tunnelling IP address

---

downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-ssh-tunnel.adoc

Backports https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/431 Add user-replaced value for SSH tunnelling IP address to 2.1
[AAP-4775](https://issues.redhat.com/browse/AAP-4775)
The `ssh` command to establish an SSH tunnel contains an IP address. Replace this with a user-replaced value.
Affects the AAP on Azure guide.

2.1 AAP-4775 Add user-replaced value for SSH tunnelling IP address (#431)

---

downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-ssh-tunnel.adoc

Backports #431 Add user-replaced value for SSH tunnelling IP address to 2.2
[AAP-4775](https://issues.redhat.com/browse/AAP-4775)
The `ssh` command to establish an SSH tunnel contains an IP address. Replace this with a user-replaced value.
Affects the AAP on Azure guide.

2.2 AAP-4775 Add user-replaced value for SSH tunnelling IP address (#431)

---

downstream/modules/automation-hub/proc-create-synclist.adoc
downstream/modules/platform/ref-system-requirements.adoc
downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc

* Added allowlisted domains
Added list of allowlisted domains and other requirements
Add in the doc from config AAP the domains which need to be whitelisted
https://issues.redhat.com/browse/AAP-4122
* Added allowlisted domains
Corrections and addressed comments
Add in the doc from config AAP the domains which need to be whitelisted
https://issues.redhat.com/browse/AAP-4122
Title affected:  ./hub/configuring-private-hub-rh-certified ([section 1.2](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/managing_red_hat_certified_and_ansible_galaxy_collections_in_automation_hub/assembly-synclists#proc-create-synclist))

2.1 AAP-4122 Added allowlisted domains (#414)

---

downstream/modules/platform/proc-create-keycloak-realm.adoc

There is a formatting error in the table describing YAML fields in the [Creating a Keycloak realm for AAP](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html-single/red_hat_ansible_automation_platform_operator_installation_guide/index#proc-create-keycloak-realm_using-a-rhsso-operator) section of the Operator Installation guide
The field names should be enclosed in single backticks 
Backport to 2.2
AAP-5095

AAP-5095 fix YAML field formatting in table

---

downstream/modules/platform/proc-create-keycloak-realm.adoc

Backports #462 to 2.2
AAP-5095
There is a formatting error in the table describing YAML fields in the [Creating a Keycloak realm for AAP](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html-single/red_hat_ansible_automation_platform_operator_installation_guide/index#proc-create-keycloak-realm_using-a-rhsso-operator) section of the Operator Installation guide.
The field names should be enclosed in single backticks.

2.2 AAP-5095 Fix YAML field formatting in table (#462)

---

downstream/modules/platform/proc-create-keycloak-realm.adoc

Backports #462 to 2.1
AAP-5095
There is a formatting error in the table describing YAML fields in the [Creating a Keycloak realm for AAP](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html-single/red_hat_ansible_automation_platform_operator_installation_guide/index#proc-create-keycloak-realm_using-a-rhsso-operator) section of the Operator Installation guide.
The field names should be enclosed in single backticks.

2.1 AAP-5095 fix YAML field formatting in table (#462)

---

downstream/modules/automation-hub/proc-set-community-remote.adoc
downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc

Updating this again to replace version with attribute as the stated version
is rather old. This will be backported to 2.1 and 2.2.
Broken Links found for version 1.0 and 1.2 for ANSIBLE GALAXY COLLECTIONS IN AUTOMATION HUB
https://issues.redhat.com/browse/AAP-1625

Update broken hub link

---

downstream/modules/aap-on-azure/proc-azure-update-route-tables.adoc

AAP-5260
Add info about configuring routing through an Azure Virtual Appliance
so that
users can configure routes to allow traffic from their Ansible on Azure instance through an Azure Virtual Appliance to quay and registry.redhat.io, as well as to automation targets.
Affects titles/aap-on-azure

AAP-5260 Add virtual appliance routing info

---

downstream/modules/aap-on-azure/proc-azure-update-route-tables.adoc

AAP-5260
Update info about configuring routing through an Azure Virtual Appliance firewall
so that
outbound traffic from the full CIDR range of the managed application can access quay and registries, and so that you can enable all outbound traffic from port 443

AAP-5260 Update virtual appliance firewall content

---

downstream/modules/aap-on-azure/proc-azure-update-route-tables.adoc

Backports https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/471 and https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/475 to 2.2
Affects Ansible on Azure guide
AAP-5260

2.2 AAP-5260 Add virtual appliance routing info

---

downstream/attributes/attributes.adoc

Backports #479 AAP-5311 to `2.2`
Update the attribute representing the latest OpenShift release to 4.11

2.2 AAP-5311 Update latest OCP version to 4.11 (#479)

---

downstream/modules/platform/proc-import-mesh-ca.adoc

Reversed the file labels for keyfile and certificate variables
Documentation bug on 2.2. Importing a Certificate Authority (CA) certificate
https://issues.redhat.com/browse/AAP-4844
Affects AAP automation mesh guide `titles/automation-mesh/`

AAP-4844 Swapped file labels.

---

downstream/assemblies/dev-guide/assembly-tools-components.adoc

AAP-5335
Affects Platform Creator Guide (`/titles/dev-guide/`)
Chapter 4 isn't rendering on the customer portal: clicking on the chapter name in the left nav causes a 404-not-found error.
You can navigate to all other chapters from the left nav.
The local build is OK.
in the Pantheon prod build, you can scroll to the chapter, but clicking the chapter name in the left nav doesn't navigate to the chapter title.
Clicking all other chapters in the left nav brings you to the chapter.

AAP-5335 Fix ID for tools assembly

---

downstream/modules/platform/proc-import-mesh-ca.adoc

Swapped file labels.
Reversed the file labels for keyfile and certificate variables
Documentation bug on 2.2. Importing a Certificate Authority (CA) certificate
https://issues.redhat.com/browse/AAP-4844

2.2 AAP-4844 Swapped file labels. (#487)

---

downstream/assemblies/dev-guide/assembly-tools-components.adoc

Backports #488 to 2.1
AAP-5335
Affects Platform Creator Guide (`/titles/dev-guide/`)

2.1 AAP-5335 Fix ID for tools assembly (#488)

---

downstream/modules/platform/proc-import-mesh-ca.adoc

Swapped file labels.
Reversed the file labels for keyfile and certificate variables
Documentation bug on 2.2. Importing a Certificate Authority (CA) certificate
https://issues.redhat.com/browse/AAP-4844

2.1 AAP-4844 Swapped file labels (#487)

---

downstream/assemblies/dev-guide/assembly-tools-components.adoc

Backports https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/488 to 2.2
AAP-5335
Affects Platform Creator Guide (`/titles/dev-guide/`)

2.2 AAP-5335 Fix ID for tools assembly (#488)

---

downstream/modules/aap-on-azure/con-aap-azure-architecture.adoc

AAP-5346
Affects the Ansible on Azure guide (`/titles/aap-on-azure/`)
Incorporate information from a [KB article](https://access.redhat.com/articles/6869301  in the product documentation.
So that
customers understand the node pool resource group that's created when Ansible on Azure is deployed.

AAP-5346 Added AKS node pool resource group info

---

downstream/modules/aap-on-azure/con-aap-azure-architecture.adoc

Backport #498  to `2.1`
AAP-5346
Affects the Ansible on Azure guide (/titles/aap-on-azure/)
Incorporates information from a [KB article](https://access.redhat.com/articles/6869301 in the product documentation.

2.1 AAP-5346 Added AKS node pool resource group info (#498)

---

downstream/modules/aap-on-azure/con-aap-azure-architecture.adoc

Backport #498  to `2.2`
AAP-5346
Affects the Ansible on Azure guide (/titles/aap-on-azure/)
Incorporates information from a [KB article](https://access.redhat.com/articles/6869301 in the product documentation.

2.2 AAP-5346 Added AKS node pool resource group info (#498)

---

downstream/modules/aap-on-azure/con-aap-azure-network.adoc
downstream/modules/aap-on-azure/con-aap-private-access.adoc
downstream/modules/aap-on-azure/con-aap-public-access.adoc
downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-az-hosted-vm.adoc
downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-vpn.adoc
downstream/modules/aap-on-azure/proc-azure-nw-private-deploy.adoc
downstream/modules/aap-on-azure/proc-azure-provisioning-aap.adoc
downstream/modules/aap-on-azure/proc-peer-vwan-hub-to-aap.adoc

AAP-5465
Affects Ansible on Azure guide (`/titles/aap-on-azure/`)
In previous versions of the Azure docs, the CIDR range for the VNET was fixed.
Users can now configure the VNET CIDR block for their AAP on Azure managed application.
Link to a KB article (https://access.redhat.com/articles/6973251) for Azure-specific configuration: Red Hat doesn't support the Azure UI or Azure defaults.

AAP-5465 User-configurable CIDR blocks in AAP on Azure

---

downstream/modules/aap-on-azure/con-aap-azure-network.adoc
downstream/modules/aap-on-azure/con-aap-private-access.adoc
downstream/modules/aap-on-azure/con-aap-public-access.adoc
downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-az-hosted-vm.adoc
downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-vpn.adoc
downstream/modules/aap-on-azure/proc-azure-nw-private-deploy.adoc
downstream/modules/aap-on-azure/proc-azure-provisioning-aap.adoc
downstream/modules/aap-on-azure/proc-peer-vwan-hub-to-aap.adoc

Backports #505 to `2.1`
AAP-5465
Affects Ansible on Azure guide (/titles/aap-on-azure/)
In previous versions of the Azure docs, the CIDR range for the VNET was fixed.
Users can now configure the VNET CIDR block for their AAP on Azure managed application.

AAP-5465 User-configurable CIDR blocks in AAP on Azure (#505)

---

downstream/modules/aap-on-azure/con-aap-azure-network.adoc
downstream/modules/aap-on-azure/con-aap-private-access.adoc
downstream/modules/aap-on-azure/con-aap-public-access.adoc
downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-az-hosted-vm.adoc
downstream/modules/aap-on-azure/proc-azure-nw-private-deploy-vpn.adoc
downstream/modules/aap-on-azure/proc-azure-nw-private-deploy.adoc
downstream/modules/aap-on-azure/proc-azure-provisioning-aap.adoc
downstream/modules/aap-on-azure/proc-peer-vwan-hub-to-aap.adoc

Backports #505 to `2.2`
AAP-5465
Affects Ansible on Azure guide (/titles/aap-on-azure/)
In previous versions of the Azure docs, the CIDR range for the VNET was fixed.
Users can now configure the VNET CIDR block for their AAP on Azure managed application.

2.2 AAP-5465 User-configurable CIDR blocks in AAP on Azure (#505)

---

downstream/assemblies/platform/assembly-configure-known-proxies.adoc
downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
downstream/modules/platform/con-known-proxies.adoc
downstream/modules/platform/proc-configure-known-proxies.adoc
downstream/modules/platform/proc-configuring-reverse-proxy.adoc
downstream/modules/platform/proc-enable-proxy-support.adoc

Backport AAP-1939 #232 to `2.1`
Affects installation guide (`/titles/aap-installation-guide/`)

2.1 AAP-1939: Update proxy support docs on AAP installer (#232)

---

downstream/assemblies/platform/assembly-configure-known-proxies.adoc
downstream/assemblies/platform/assembly-supported-attributes-custom-notifications.adoc
downstream/titles/aap-installation-guide/master.adoc

Backports #468 to 2.1
Affects installation guide
AAP-5145
The [Installation guide preface](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_installation_guide/pr01) on access.redhat.com is showing a leveloffset artefact.

2.1 AAP-5145 Fix codeblock delimiter and leveloffset (#468)

---

downstream/assemblies/platform/assembly-configure-known-proxies.adoc
downstream/assemblies/platform/assembly-supported-attributes-custom-notifications.adoc
downstream/titles/aap-installation-guide/master.adoc

Backports #468  to 2.2
Affects installation guide
AAP-5145
The [Installation guide preface](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_installation_guide/pr01) on access.redhat.com is showing a leveloffset artefact.

2.2 AAP-5145 Fix codeblock delimiter and leveloffset (#468)

---

downstream/modules/platform/ref-complex-mesh-topology.adoc

typo in the automation mesh guide
https://issues.redhat.com/browse/AAP-5528

Corrected typo (#519)

---

downstream/assemblies/hub/assembly-collections-and-content-signing-in-pah.adoc
downstream/modules/automation-hub/proc-configure-ansible-galaxy-cli-verify.adoc
downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc
downstream/modules/automation-hub/proc-using-content-signing-services-in-pah.adoc
downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc

Adding collection and content signing topics to the **Managing Red Hat Certified and Ansible Galaxy collections in Automation Hub** guide: 
- Collections and content signing in private automation hub (Chapter 3)
- Configuring content signing on private automation hub (Chapter 3.1)
- Using content signing services in private automation hub (Chapter 3.2)
- Configuring Ansible-Galaxy CLI to verify collections (Chapter 3.3)
- Also, updated preface section to include a statement about collections in private automation hub so that the overall flow of the information is cohesive and Chapter 3 does not seem like it's simply thrown into the outline of topics.

AAP-2844 Add collections and content signing info

---

downstream/assemblies/hub/assembly-collections-and-content-signing-in-pah.adoc
downstream/modules/automation-hub/proc-configure-ansible-galaxy-cli-verify.adoc
downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc
downstream/modules/automation-hub/proc-using-content-signing-services-in-pah.adoc
downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc

Adding collection and content signing topics (based on jira [AAP-2844](https://issues.redhat.com/browse/AAP-2844)) to the Managing Red Hat Certified and Ansible Galaxy collections in Automation Hub guide for 2.2 docs:
- Collections and content signing in private automation hub (Chapter 3)
- Configuring content signing on private automation hub (Chapter 3.1)
- Using content signing services in private automation hub (Chapter 3.2)
- Configuring Ansible-Galaxy CLI to verify collections (Chapter 3.3)
Also, updated preface section to include a statement about collections in private automation hub so that the overall flow of the information is cohesive and Chapter 3 does not seem like it's simply thrown into the outline of topics. The final chapter (Conclusion) has also been updated to reflect …

Backport 2.2 493 Content signing documentation from PR #s 493 and 546 

---

downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc

Leaving ansible-autmoation-platform-2.1-for-rhel-8-x86_64-rpms enabled
causes installation to fail. A new installayion method was suggested.
Install Automation content navigator on RHEL Document update
https://issues.redhat.com/browse/AAP-4972

Updated navigator installation method

---

downstream/modules/builder/proc-installing-builder.adoc

Added a new first step in the **Ansible Builder Guide** in "Chapt 2.1 Installing Ansible Builder"  to activate the AAP repo.

AAP-2948 Add step to activate AAP repo

---

downstream/modules/builder/proc-installing-builder.adoc

Cherry-picked updates in original [PR #546](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/546) to 2.1 branch. 
* AAP-2948 Add step to activate AAP repo
* AAP-2948 Tweaked wording of new first step
* AAP-2948 Additional tweaks to instructions
* AAP-2948 Update command in step1 and syntax for note

AAP-2948 Add step to activate AAP repo (#546)

---

downstream/modules/builder/proc-installing-builder.adoc

In the original [PR](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/546), the note before the procedures was updated to match syntax suggested in other product's docs (brackets and = signs), but this rendered the content incorrectly. Returned the note back to original and note displays properly.

AAP-2948A Return note syntax to original

---

downstream/assemblies/platform/assembly-installing-controller-operator.adoc

Fix build error - Operator installation guide couldn't be built because one of the files included in an assembly was mis-spelt.

AAP-1505 Fix build error

---

downstream/assemblies/platform/assembly-installing-controller-operator.adoc
downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
downstream/modules/platform/proc-configuring-controller-route-options.adoc
downstream/modules/platform/proc-creating-controller-form-view.adoc
downstream/modules/platform/proc-hub-ingress-options.adoc
downstream/modules/platform/proc_configuring-tls-with-aap-operator.adoc

Backports #554 and #558 to `2.2`
Affects operator installation guide (`/titles/aap-operator-installation/`)

2.2 AAP-1505 Update docs for using custom SSL certificates in OCP

---

release-notes/master.adoc
release-notes/topics/operator-220.adoc

This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-4360.
Changes in this pull request include the following:
- Adding a section for Operator to the release notes for v2.2.
- Adding information regarding deprecation of the image_pull_secret variable.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP4360/master.html

AAP-4360 - Add section & info for AAP Operator to release notes for 2.2

---

downstream/assemblies/platform/assembly-aap-migration.adoc
downstream/assemblies/platform/assembly-operator-upgrade.adoc
downstream/modules/platform/con-aap-migration-considerations.adoc
downstream/modules/platform/con-aap-migration-prepare.adoc
downstream/modules/platform/con-aap-migration-prereqs.adoc
downstream/modules/platform/con-ocp-supported-install.adoc
downstream/modules/platform/con-operator-upgrade-considerations.adoc
downstream/modules/platform/con-operator-upgrade-prereq.adoc
downstream/modules/platform/proc-aap-create_controller.adoc
downstream/modules/platform/proc-aap-create_hub.adoc
downstream/modules/platform/proc-aap-migration-backup.adoc
downstream/modules/platform/proc-aap-migration.adoc
downstream/modules/platform/proc-create-postresql-secret.adoc
downstream/modules/platform/proc-create-secret-key-secret.adoc
downstream/modules/platform/proc-find-delete-PVCs.adoc
downstream/modules/platform/proc-install-aap-operator.adoc
downstream/modules/platform/proc-operator-upgrade.adoc
downstream/modules/platform/proc-post-migration-cleanup.adoc
downstream/modules/platform/proc-verify-network-connectivity.adoc
downstream/titles/aap-operator-installation/docinfo.xml
downstream/titles/aap-operator-installation/master.adoc

This bug addresses the work for https://issues.redhat.com/browse/AAP-2336 and the child tasks associated with it:
Changes in this pull request include:
Title change to "Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform"
Chapter 6: Migrating to the Ansible Automation Platform operator on OpenShift Container Platform 
Chapter 7: Upgrading the Ansible Automation Platform operator on OpenShift Container Platform
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP-2336/master.html

AAP2336 - Created topics for Migration & Upgrade of Operator on OCP

---

downstream/modules/platform/proc-install-aap-operator.adoc

Corrected the statement for stable-2.x in proc-install-aap-operator.adoc per comment from @rooftopcellist in PR https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/494

Minor last minute correction to AAP-3675

---

downstream/modules/platform/proc-install-aap-operator.adoc

Backports #575 to 2.2
Affects Operator guide
* Minor last minute correction to AAP-3675
* AAP-3675A - Fixed description of stable-2.x channel

2.2 Minor last minute correction to AAP-3675 (#575)

---

downstream/assemblies/platform/assembly-operator-upgrade.adoc
downstream/modules/platform/con-aap-migration-prepare.adoc
downstream/modules/platform/con-operator-upgrade-considerations.adoc
downstream/modules/platform/proc-aap-create_controller.adoc
downstream/modules/platform/proc-aap-create_hub.adoc
downstream/modules/platform/proc-aap-migration.adoc
downstream/modules/platform/proc-operator-upgrade.adoc
downstream/titles/aap-operator-installation/master.adoc

**Task:** 
Fix xref problems that occurred in AAP-2336.
Affects the following doc: /titles/aap-operator-installation/
**Problem:**
The Operator doc built OK with asciidoctor, but failed to build using bccutil due to bad internal cross-references.
**Note to reviewers:**
When reviewing, please build the doc and check the cross-references in the following sections:
- 6.2 Preparing for migration
- 6.3.1 Creating an AutomationController object
- 6.3.2 Creating an AutomationHub object
- 7.1 Upgrade considerations
**Summary of changes:**
I added some comments to a few files to explain why I made some changes
- Fixed duplicate IDs
- Fixed xref syntax
- Substituted values in place of `{context}` 
I made sure that none of the changes affected any other doc.
**Follow-up tasks**
Once merged, …

AAP-2336 Fix xref issues

---

downstream/modules/platform/con-aap-migration-prepare.adoc
downstream/modules/platform/con-operator-upgrade-considerations.adoc
downstream/modules/platform/proc-aap-create_controller.adoc
downstream/modules/platform/proc-aap-create_hub.adoc
downstream/modules/platform/proc-aap-migration.adoc
downstream/modules/platform/proc-operator-upgrade.adoc
downstream/titles/aap-operator-installation/master.adoc

Backports #586 to 2.3
Fixes xref problems that occurred in AAP-2336.
Affects the following doc: /titles/aap-operator-installation/

2.3 AAP-2336 Fix xref issues (#586)

---

downstream/assemblies/central-auth/assembly-central-auth-group-perms.adoc
downstream/modules/automation-hub/proc-assigning-roles.adoc
downstream/modules/automation-hub/ref-permissions.adoc

Jira: [AAP-1649](https://issues.redhat.com/browse/AAP-1649)
- Users can now add specific permissions to roles, and then add those roles to groups.
- Added instructions for assigning roles from both the **Groups** menu and the **Namespaces** menu.

AAP-1649: Adopt new Pulp RBAC

---

downstream/titles/builder/master.adoc

To fix Pantheon build problems, modify the title in master.adoc for /titles/builder to match docinfo.xml

Modify builder title to match docinfo

---

downstream/titles/builder/master.adoc

To fix Pantheon build problems, modify the title in master.adoc for /titles/builder to match docinfo.xml

2.2 Modify builder title to match docinfo (#610)

---

downstream/assemblies/central-auth/assembly-central-auth-group-perms.adoc
downstream/modules/automation-hub/proc-assigning-roles.adoc
downstream/modules/automation-hub/ref-permissions.adoc

Jira: [AAP-1649](https://issues.redhat.com/browse/AAP-1649)
- Users can now add specific permissions to roles, and then add those roles to groups.
- Added instructions for assigning roles from both the Groups menu and the Namespaces menu.

AAP-1649: Adopt new Pulp RBAC (#587)

---

downstream/modules/platform/ref-system-requirements.adoc

Updated note in the Installation Guide, Section 1.1.1 Automation Controller, to include the correct name of the directory for EE storage, per request in [AAP-6156](https://issues.redhat.com/browse/AAP-6156): 
**Note:** 
On all nodes except hop nodes, allocate a minimum of 20 GB to **`/var/lib/awx`** for execution environment storage.
Changed from `/home/awx`

AAP-6156 Updated EE storage location for controller

---

downstream/titles/builder/master.adoc

To fix Pantheon build problems, modify the title in master.adoc for /titles/builder to match docinfo.xml
Backports #610 to 2.3
Affects /titles/builder

2.3 Modify builder title to match docinfo (#610)

---

downstream/titles/aap-operator-installation/master.adoc

AAP-3475
Affects titles/aap-operator-installation
Update title in master.adoc to match title in docinfo.xml.

AAP-3475 Fix operator doc title to match docinfo

---

downstream/titles/aap-operator-installation/master.adoc

Backport #614 to 2.2
Affects titles/aap-operator-installation
Update title in master.adoc to match title in docinfo.xml.
aap-3475 Fix operator doc title to match docinfo

2.2 AAP-3475 Fix operator doc title to match docinfo (#614)

---

downstream/titles/aap-operator-installation/master.adoc

Backport https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/614 to 2.3
Affects titles/aap-operator-installation
Update title in master.adoc to match title in docinfo.xml.
aap-3475 Fix operator doc title to match docinfo

2.3 AAP-3475 Fix operator doc title to match docinfo (#614)

---

downstream/modules/platform/ref-system-requirements.adoc
downstream/titles/aap-installation-guide/master.adoc

Cherry-picked update to note in the 2.2 version of the Installation Guide, Section 1.1.1 Automation Controller, to include the correct name of the directory for EE storage, per request in [AAP-6156](https://issues.redhat.com/browse/AAP-6156). 
Changed from `/home/awx` to `/var/lib/awx`

Backport 2.2 603 - based on Updated EE storage location for controller #603 (AAP-6156)

---

downstream/modules/platform/ref-system-requirements.adoc
downstream/titles/aap-installation-guide/master.adoc

Cherry-picked update to note in the 2.3 version of the Installation Guide, Section 1.1.1 Automation Controller, to include the correct name of the directory for EE storage, per request in [AAP-6156](https://issues.redhat.com/browse/AAP-6156).
Changed from /home/awx to /var/lib/awx

Backport 2.3 603A - based on Updated EE storage location for controller (AAP-6156)

---

downstream/titles/aap-installation-guide/master.adoc

The AAP installation guide was failing to build locally and on Pantheon.
Build error message when building with ccutil: 
```
asciidoctor: WARNING: master.adoc: line 31: invalid style for paragraph: appendix
Unknown ID or title "appendix-inventory-files-vars", used as an internal cross reference
/Users/ariordan/repos/red-hat-ansible-automation-platform-documentation/downstream/titles/aap-installation-guide/build/en-US/master.xml fails to validate
```
That is, the internal cross reference was flagged as the error. But the cross reference had worked in a previously published version of the doc on the customer portal.
The build error actually originated from a missing newline at the end of master.adoc.

Add newline, brackets to fix install guide build failure

---

downstream/titles/aap-installation-guide/master.adoc

Backports #643 to 2.3
The AAP installation guide was failing to build locally and on Pantheon.
Build error message when building with ccutil:
```
asciidoctor: WARNING: master.adoc: line 31: invalid style for paragraph: appendix
Unknown ID or title "appendix-inventory-files-vars", used as an internal cross reference
/Users/ariordan/repos/red-hat-ansible-automation-platform-documentation/downstream/titles/aap-installation-guide/build/en-US/master.xml fails to validate
That is, the internal cross reference was flagged as the error. But the cross reference had worked in a previously published version of the doc on the customer portal.
```
The build error actually originated from a missing newline at the end of `master.adoc`.

2.3 Add newline, brackets to fix install guide build failure (#643)

---

downstream/titles/aap-installation-guide/master.adoc

Backports #643  to 2.2
The AAP installation guide was failing to build locally and on Pantheon.
Build error message when building with ccutil:
```
asciidoctor: WARNING: master.adoc: line 31: invalid style for paragraph: appendix
Unknown ID or title "appendix-inventory-files-vars", used as an internal cross reference
/Users/ariordan/repos/red-hat-ansible-automation-platform-documentation/downstream/titles/aap-installation-guide/build/en-US/master.xml fails to validate
That is, the internal cross reference was flagged as the error. But the cross reference had worked in a previously published version of the doc on the customer portal.
```
The build error actually originated from a missing newline at the end of `master.adoc`.

2.2 Add newline, brackets to fix install guide build failure (#643)

---

downstream/titles/aap-installation-guide/docinfo.xml
downstream/titles/aap-operator-backup/docinfo.xml
downstream/titles/aap-operator-installation/docinfo.xml
downstream/titles/analytics/automation-savings-planner/docinfo.xml
downstream/titles/analytics/automation-savings/docinfo.xml
downstream/titles/analytics/job-explorer/docinfo.xml
downstream/titles/analytics/reports/docinfo.xml
downstream/titles/automation-mesh/docinfo.xml
downstream/titles/builder/docinfo.xml
downstream/titles/catalog/getting-started/docinfo.xml
downstream/titles/catalog/itsm-integration/docinfo.xml
downstream/titles/catalog/support-matrix/docinfo.xml
downstream/titles/central-auth/docinfo.xml
downstream/titles/dev-guide/docinfo.xml
downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
downstream/titles/hub/getting-started/docinfo.xml
downstream/titles/hub/high-availability/docinfo.xml
downstream/titles/hub/install/docinfo.xml
downstream/titles/hub/lifecycle/docinfo.xml
downstream/titles/hub/manage-containers/docinfo.xml
downstream/titles/hub/managing-user-access/docinfo.xml
downstream/titles/hub/publishing-internal-content/docinfo.xml
downstream/titles/hub/uploading-collections/docinfo.xml
downstream/titles/hub/uploading-internal-collections/docinfo.xml
downstream/titles/navigator-guide/docinfo.xml
downstream/titles/security-guide/docinfo.xml
downstream/titles/upgrade/docinfo.xml
downstream/titles/worker-install/docinfo.xml

Backports #641 
Updates the release version for the docs published in the AAP 2.3 page of the customer portal.
The release number is not updated for docs that are not to be published for 2.3.

Update release in docinfo only for docs in 2.3 (#641)

---

downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
downstream/titles/hub/uploading-collections/master.adoc

Title mismatches were causing Pantheon builds to fail.
The titles in `master.adoc` and `docinfo.xml` must both match the title in Pantheon. 
Titles are case-sensitive.

Fix build issues for 2.3 docs

---

downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
downstream/titles/hub/uploading-collections/master.adoc

Title mismatches for 2 documents were causing Pantheon builds to fail.
The titles in `master.adoc` and `docinfo.xml` must both match the title in Pantheon. 
Titles are case-sensitive.

2.3 Fix build issues for 2.3 docs (#647)

---

downstream/assemblies/platform/assembly-disconnected-installation.adoc
downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc

Fix links in the inventory guide.
Issue arose because building with asciidoctor doesn't pick up some errors that break Pantheon builds.

AAP-1254a Modify links in installation guide

---

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/modules/platform/ref-system-requirements.adoc

Added an "Additional Resources" section with a link to the "Import a subscription" (Controller docs) to the section "1.1.1 Automation controller" topic in the Installation Guide, per development request.

AAP-6015 Add link to "Import a subscription" to Install Guide

---

downstream/modules/platform/ref-system-requirements.adoc

Based on original ticket [AAP-6015](https://issues.redhat.com/browse/AAP-6015) (PR https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/657 ) in which developers requested a link to the Import a subscription topic be added to the planning chapter of the Installation Guide.
Added the link right after the end of the section 1.1.1 Automation controller.

Backport-2.2-657 Add link to "Import a subscription" to 2.2 Installation Guide

---

downstream/modules/platform/ref-system-requirements.adoc

Based on original ticket [AAP-6015](https://issues.redhat.com/browse/AAP-6015) (PR https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/657 ) in which developers requested a link to the Import a subscription topic be added to the planning chapter of the Installation Guide.
Added the link right after the end of the section 1.1.1 Automation controller.

Backport-2.3-657 Add link to "Import a subscription" to 2.3 Installation Guide

---

downstream/modules/core/con-execution-environments.adoc
downstream/modules/dev-guide/con-content-workflows.adoc

1. modules/dev-guide/con-content-workflows.adoc:
**Under Additional resources**
Added links to [Ansible Navigator Creator Guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/%7BPlatformVers%7D/html/ansible_navigator_creator_guide) and [Creating and Consuming Execution Environments](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/%7BPlatformVers%7D/html/creating_and_consuming_execution_environments/index).
2. modules/core/execution-environments.adoc:
**Under Additional resources**
Added link to [Creating and Consuming Execution Environments](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/%7BPlatformVers%7D/html/creating_and_consuming_execution_environments/index).

AAP-357 added links to builder and navigator guides

---

downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
downstream/assemblies/platform/assembly-installing-aap-components.adoc
downstream/assemblies/platform/assembly-multi-machine-cluster-scenario.adoc
downstream/assemblies/platform/assembly-multi-machine-install.adoc
downstream/assemblies/platform/assembly-platform-ext-database-install.adoc
downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/assemblies/platform/assembly-single-machine-scenarios.adoc
downstream/modules/platform/ref-controller-configs.adoc
downstream/titles/aap-installation-guide/master.adoc

This PR handles the restructuring of the AAP Installation Guide based on meetings with Mike Silmser and Lydie-Mode Malivert and outlined in the Installation Guide Restructuring Plan (https://docs.google.com/document/d/1Su7oAjC7MwIREGpW8NpC71OJfHRSvAatCZFI1-LXXZM/edit#heading=h.gaobgjjc253x)
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/IG4941/master.html

AAP-4941 - Restructure of the AAP Install Guide

---

downstream/assemblies/platform/assembly-aap-migration.adoc

Affects `/titles/aap-operator-installation/`
AAP-7480 Fix release number for OpenShift Ansible Tower version

AAP-7480 Update OpenShift Ansible Tower version

---

downstream/assemblies/platform/assembly-aap-migration.adoc

Affects `/titles/aap-operator-installation/`
AAP-7480 Fix release number for OpenShift Ansible Tower version

2.3 AAP-7480 Update OpenShift Ansible Tower version (#670)

---

downstream/modules/builder/proc-customize-ee-image.adoc

Modified proc-customize-ee-image.adoc in the 2.1 builder doc as follows:
**Original Behavior**
Minimal - contains the latest Ansible 2.11 release along with Ansible Runner, but contains no collections or other additional content
**Modified Behavior**
Minimal - contains the latest Ansible 2.12 release along with Ansible Runner, but contains no collections or other additional content

AAP-1644 updated old builder doc

---

downstream/titles/aap-operations-guide/master.adoc

Part of docathon to refactor Installation guide 
AAP-7533: Affects section 1 of Operations guide (`/titles/aap-operations-guide/`)
- Replace attributes in master.adoc title
- Replace introductory text in master.adoc

AAP-7533 Docathon Section 1 of Operations Guide

---

downstream/assemblies/platform/assembly-controlling-data-collection.adoc
downstream/modules/platform/con-user-data-tracking.adoc
downstream/modules/platform/proc-control-data-collection.adoc

Part of docathon to refactor Installation guide
AAP-7538: Affects section 3 of Operations guide (`/titles/aap-operations-guide/`)
Close this PR if it's out of scope for the docathon: There were no structural/build issues to tackle in this section of the Operations Guide, so I just tidied up some asciidoc in the modules.

AAP-7538 docathon Modify Operations guide section 3 content

---

downstream/assemblies/platform/assembly-planning-installation.adoc

This PR addresses the changes required by https://issues.redhat.com/browse/AAP-7601.
Changes include fixing the broken xrefs in the new Planning Guide caused by the restructuring of the AAP Installation Guide.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP7601/master.html

AAP-7601 - Remediate broken xrefs due to restructuring

---

downstream/assemblies/platform/assembly-platform-install-scenario.adoc

This PR addresses the changes required by https://issues.redhat.com/browse/AAP-7618.
Change includes:
When user installs RH AAP, they can install controller with other automation platform components ...not just Hub. The AAP is modular - the user can choose which components they want to install.

AAP-7618 Include information regarding component options with AAP

---

downstream/modules/platform/proc-attaching-subscriptions.adoc
downstream/modules/platform/proc-running-setup-script.adoc

This PR addresses the changes required for https://issues.redhat.com/browse/AAP-7617.
Changes include the following:
In the new AAP planning guide (Introduction to Red Hat Ansible Automation Platform):
- Remove references to AAP version 2.2. This appears in the troubleshooting section.
- Red Hat Ansible Automation Platform Infrastructure Subscription (MCT4022) should not be used as pool ID. Create a note that says not to use.
In the new AAP Installation Guide:
-  In section 2.2 Running the Red Hat Ansible Automation Platform installer setup script - tell the user to use root (sudo).

AAP-7617 Minor edits to new AAP Guides

---

downstream/assemblies/platform/assembly-platform-install-overview.adoc
downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/assemblies/platform/assembly-platform-whats-next.adoc
downstream/modules/platform/con-aap-installation-prereqs.adoc
downstream/modules/platform/con-why-automation-mesh.adoc
downstream/modules/platform/con-why-migrate-ansible-29.adoc
downstream/modules/platform/con-why-migrate-ansible-core-212.adoc
downstream/modules/platform/con-why-migrate-ansible-core-213.adoc
downstream/modules/platform/con-why-migrate-venvs-ee.adoc
downstream/modules/platform/proc-verify-controller-installation.adoc
downstream/modules/platform/proc-verify-hub-installation.adoc
downstream/modules/platform/ref-controller-configs.adoc
downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
downstream/modules/platform/ref-hub-configs.adoc

This PR updates links to the doc set on the customer portal to always point to the latest version by using the PlatformVers attribute.
Change 2.3 in links to {PlatformVers}
Include the link: for all links.
Include alt text where missing.
Other minor formatting fixes.

IG-LINKFIX - changed hardcoded 2.3 in links to the PlatformVers

---

downstream/modules/builder/proc-installing-builder.adoc

Cherry-picked updates in original PR # https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/546 to 2.2 branch in the **Creating and Consuming Execution Environments Guide**  (formerly titled **Ansible Builder Guide**) in "Chapt 2.2 Installing Ansible Builder" to activate the AAP repo.

Backport AAP-2948 (#546) to 2.2

---

downstream/modules/platform/con-aap-installation-prereqs.adoc

Corrected link
Wrong link towards Red Hat Ansible Automation Platform system requirements
https://issues.redhat.com/browse/AAP-7804

2.3 Updated link in installation guide (#712)

---

downstream/assemblies/platform/assembly-aap-migration.adoc

This PR addresses the changes required by https://issues.redhat.com/browse/AAP-4995.
Change includes the following:
Added bullet to Chapter 6 to show that the procedures cover migration of AWX --> Openshift AAP Operator as well as Tower and VM deployments:
- An AWX instance

AAP-4995 - Add AWX deployment to list of migration options

---

downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/assemblies/platform/assembly-planning-installation.adoc
downstream/modules/platform/ref-system-requirements.adoc

This PR addresses the changes required for https://issues.redhat.com/browse/AAP-3514.
Changes include:
Added information regarding supported installations with a link to the Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform Guide in the fo514llowing locations:
Planning guide intro
AAP system requirements notes
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP3514/master.html

AAP-3514 added links for OCP install of AAP

---

downstream/assemblies/platform/assembly-aap-migration.adoc

This PR backports the changes from PR 703 to the 2.3 branch and includes the following:
* AAP-4995 - Add AWX deployment to list of migration options
* AAM-4995 - minor grammatical change
* AAP-4995 - Updated bullet based on SME feedback

AAP-4995 - Add AWX deployment to list of migration options (#703)

---

downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/assemblies/platform/assembly-planning-installation.adoc
downstream/modules/platform/ref-system-requirements.adoc

This PR backports the changes for PR693 to the 2.2 branch and includes the following: 
* AAP-3514 added links for OCP install of AAP
* AAP-3514 Removed version number for RHEL per SME comment

AAP-3514 Backport PR#693 to 2.2 branch

---

downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/assemblies/platform/assembly-planning-installation.adoc
downstream/modules/platform/ref-system-requirements.adoc

This PR backports the changes from PR693 to the 2.3 branch and includes the following: 
* AAP-3514 added links for OCP install of AAP
* AAP-3514 Removed version number for RHEL per SME comment

AAP-3514 Backport #693 to the 2.3 branch

---

downstream/modules/builder/proc-installing-builder.adoc

Updated command to use root (#) instead of normal user ($) within Ansible Builder Guide section 2.1 (https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html-single/ansible_builder_guide/index#proc-installing-builder)

AAP-6697 updated builder guide section 2.1

---

downstream/modules/platform/ref-system-requirements.adoc

This PR fixes a typo in the Planning Guide. Change includes:
Under Base system requirements, changed version from 2.2 to 2.12

AAP-PG - Fixed typo in Ansible version

---

downstream/modules/platform/ref-system-requirements.adoc

This PR backports the changes from #741 into the 2.3 branch.

Backport - AAP-PG - Fixed typo in Ansible version (#741)

---

downstream/modules/platform/proc-install-cli-aap-operator.adoc

Updated "[Chapter 5.2 Subscribing a namespace to an operator using the OpenShift Container Platform CLI](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_operator_installation_guide/installing-aap-operator-cli#proc-install-cli-aap-operatorinstalling-aap-operator-cli)", step 3 code section by replacing lines after the last `spec:` in the code with `replicas: 1` , per SME Shane McDonald (based on [AAP-1332](https://issues.redhat.com/browse/AAP-1332) and [AAP-7741](https://issues.redhat.com/browse/AAP-7741).

AAP-8064 Updated code in step 3 of chpt 5.2, per SME

---

downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/assemblies/platform/assembly-planning-installation.adoc
downstream/modules/platform/ref-system-requirements.adoc

PR#693 had conflict errors which broke the formatting of the Guide. This PR reverts the backport changes from PR  RedHatInsights/red-hat-ansible-automation-platform-documentation#724

Revert "AAP-3514 Backport PR#693 to 2.2 branch"

---

downstream/modules/platform/proc-install-cli-aap-operator.adoc

Updated "[Chapter 5.2 Subscribing a namespace to an operator using the OpenShift Container Platform CLI](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_operator_installation_guide/installing-aap-operator-cli#proc-install-cli-aap-operatorinstalling-aap-operator-cli)", step 3 code section by replacing lines after the last spec: in the code with replicas: 1 , per SME Shane McDonald (based on [AAP-1332](https://issues.redhat.com/browse/AAP-1332) and [AAP-7741](https://issues.redhat.com/browse/AAP-7741).

Backport 2.1 745 (AAP-8064 Updated code in step 3 of chpt 5.2)

---

downstream/modules/platform/proc-install-cli-aap-operator.adoc

Updated "[Chapter 5.2 Subscribing a namespace to an operator using the OpenShift Container Platform CLI](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_operator_installation_guide/installing-aap-operator-cli#proc-install-cli-aap-operatorinstalling-aap-operator-cli)", step 3 code section by replacing lines after the last spec: in the code with replicas: 1 , per SME Shane McDonald (based on [AAP-1332](https://issues.redhat.com/browse/AAP-1332) and [AAP-7741](https://issues.redhat.com/browse/AAP-7741).

Backport 2.2 745 (AAP-8064 Updated code in step 3 of chpt 5.2) 

---

downstream/modules/platform/proc-install-cli-aap-operator.adoc

Updated "[Chapter 5.2 Subscribing a namespace to an operator using the OpenShift Container Platform CLI](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.1/html/red_hat_ansible_automation_platform_operator_installation_guide/installing-aap-operator-cli#proc-install-cli-aap-operatorinstalling-aap-operator-cli)", step 3 code section by replacing lines after the last spec: in the code with replicas: 1 , per SME Shane McDonald (based on [AAP-1332](https://issues.redhat.com/browse/AAP-1332) and [AAP-7741](https://issues.redhat.com/browse/AAP-7741).

AAP-8064 Updated code in step 3 of chpt 5.2, per SME (#745)

---

downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc

Updated [1] [proc-installing-the-aap-setup-bundle.adoc](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/disconnected-installation#installing_the_setup_bundle) and [2] p[roc-synchronizing-rpm-repositories-by-using-reposync.adoc](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/disconnected-installation#proc-synchronizing-rpm-repositories-by-using-reposync_disconnected-installation) within the AAP Installation Guide
[1] Updated command to untar the bundle 
[2] Fixed git merge conflict

AAP-7870 updated installation guide

---

downstream/modules/platform/proc-editing-inventory-file.adoc

This PR addresses the changes required by https://issues.redhat.com/browse/AAP-7625. Changes include:
Adding information on RPM installed package to section 2.1 Editing the Red Hat Ansible Automation Platform installer inventory file.
Preview link [VPN required]: http://file.rdu.redhat.com/~ddacosta/AAP7625/master.html

AAP-7625 - added information for RPM installed package

---

downstream/assemblies/hub/assembly-pull-image.adoc
downstream/assemblies/hub/assembly-setup-container-repository.adoc
downstream/modules/automation-hub/proc-create-credential.adoc
downstream/modules/automation-hub/proc-pull-image.adoc
downstream/modules/builder/proc-pull-protected-registry.adoc

This PR addresses the changes for https://issues.redhat.com/browse/AAP-4482. Because this document went through a major restructuring, this is a rework of PR 550 {https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/550} to fit the information into the new structure.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP4482/master.html

AAP4482 - add missing steps for configuring a Container Registry

---

downstream/assemblies/hub/assembly-setup-container-repository.adoc
downstream/modules/automation-hub/proc-create-credential.adoc
downstream/modules/automation-hub/proc-pull-image.adoc
downstream/modules/builder/proc-pull-protected-registry.adoc

This PR backports the changes from PR710 to the 2.3 branch and includes the following:
* AAP4482 - added missing steps for configuring a Container Registry
* AAP4482 - relocated new topic

AAP4482 - add missing steps for configuring a Container Registry (#710)

---

downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/assemblies/platform/assembly-planning-installation.adoc
downstream/modules/platform/ref-system-requirements.adoc

This PR backports the changes from PR693 to the 2.2 branch. Changes include the following:
* AAP-3514 added links for OCP install of AAP
* AAP-3514 Removed version number for RHEL per SME comment

AAP-3514 added links for OCP install of AAP (#693)

---

downstream/assemblies/platform/assembly-aap-platform-components.adoc
downstream/assemblies/platform/assembly-attaching-subscriptions.adoc
downstream/assemblies/platform/assembly-choosing-obtaining-installer.adoc
downstream/assemblies/platform/assembly-inventory-introduction.adoc
downstream/assemblies/platform/assembly-network-ports-protocols.adoc
downstream/assemblies/platform/assembly-planning-installation.adoc
downstream/assemblies/platform/assembly-supported-installation-scenarios.adoc
downstream/assemblies/platform/assembly-system-requirements.adoc
downstream/modules/platform/con-about-automation-controller.adoc
downstream/modules/platform/con-about-automation-hub.adoc
downstream/modules/platform/con-about-execution-env.adoc
downstream/modules/platform/con-about-galaxy.adoc
downstream/modules/platform/con-about-navigator.adoc
downstream/modules/platform/con-about-pa-hub.adoc
downstream/modules/platform/con-about-services-catalog.adoc
downstream/modules/platform/con-overview-automation-mesh.adoc
downstream/modules/platform/proc-installing-with-internet.adoc
downstream/modules/platform/proc-installing-without-internet.adoc
downstream/modules/platform/ref-automation-hub-requirements.adoc
downstream/modules/platform/ref-controller-system-requirements.adoc
downstream/modules/platform/ref-platform-components.adoc
downstream/modules/platform/ref-postgresql-requirements.adoc
downstream/modules/platform/ref-system-requirements.adoc
downstream/titles/aap-planning-guide/master.adoc

This PR backports the changes from PR735 to the 2.3 branch and includes the following changes:
* Refining Planning Guide structure
* Refactored chapter topics into assemblies

Backport - AAP-8221 - Refining Planning Guide structure (#735)

---

downstream/assemblies/platform/assembly-aap-troubleshoot-backup-recovery.adoc
downstream/modules/platform/proc-aap-controller-restore.adoc
downstream/modules/platform/proc-troubleshoot-same-name.adoc
downstream/titles/aap-operator-backup/master.adoc

This PR addresses the changes required by https://issues.redhat.com/browse/AAP-7610.
Changes include:
- Added a Troubleshooting topic
- Added procedure to recover when the CR name matches an existing resource
- Added a link within the Backup section pointing to troubleshooting
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP7610/master.html
Affects `/titles/aap-operator-backup`

AAP-7610 Added troubleshooting topic and included procedure

---

downstream/snippets/external-site-disclaimer.adoc

Add a file to the `downstream/snippets/` directory. It contains approved text that disclaims responsibility for the content in external websites.

Add disclaimer for links to external sites

---

downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc

* AAP-7870 updated installation guide
* AAP-7870 updated version number
Changes made in [PR 717](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/717). Backporting to 2.3 as per [AAP-7870](https://issues.redhat.com/browse/AAP-7870).

AAP-7870 updated installation guide (#717)

---

downstream/modules/builder/proc-installing-builder.adoc

Changes made under https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/719 as per [AAP-6697](https://issues.redhat.com/browse/AAP-6697).
Backporting to 2.3.

AAP-6697 updated builder guide section 2.1 (#719)

---

downstream/modules/platform/con-aap-installation-prereqs.adoc

https://issues.redhat.com/browse/AAP-7897
Affects `/titles/aap-installation-guide/`
Update a link in the additional resources section of the Prerequisites section in the Installation Guide overview chapter.
The link should point to https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_planning_guide/platform-system-requirements

AAP-7897 Fix link in installation guide overview chapter

---

downstream/modules/platform/con-aap-installation-prereqs.adoc

Backports #771 to 2.3
https://issues.redhat.com/browse/AAP-7897
Affects `/titles/aap-installation-guide/`
Update a link in the additional resources section of the Prerequisites section in the Installation Guide overview chapter.
The link should point to https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_planning_guide/platform-system-requirements

2.3 AAP-7897 Fix link in installation guide overview chapter (#771)

---

downstream/titles/aap-operator-installation/master.adoc

This PR corrects an error in the AAP Operator Install Guide.

OP-FIX - correction to operator guide

---

downstream/titles/aap-operator-installation/master.adoc

This PR backports the change from PR780 to the 2.3 branch.

OP-FIX - correction to operator guide (#780)

---

downstream/modules/platform/ref-network-ports-protocols.adoc

Closes https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/issues/598
Modify the SSH connection variable from `pg_port` to `ansible_port` in the ports and protocols table for the database server.

Fix incorrect reference pg_port -> ansible_port

---

downstream/modules/platform/ref-network-ports-protocols.adoc

Backports #599 to 2.2
Modify the SSH connection variable from pg_port to ansible_port in the ports and protocols table for the database server.

2.2 Fix incorrect reference pg_port -> ansible_port (#599)

---

downstream/modules/platform/ref-network-ports-protocols.adoc

Backports #599  to 2.3.
Modify the SSH connection variable from pg_port to ansible_port in the ports and protocols table for the database server.

2.3 Fix incorrect reference pg_port -> ansible_port (#599)

---

downstream/assemblies/catalog/assembly-installing-receptor.adoc
downstream/modules/analytics/proc-add-roles-to-group.adoc
downstream/modules/analytics/proc-add-user-to-group.adoc
downstream/modules/analytics/proc-create-groups.adoc
downstream/modules/analytics/proc-edit-savings-plan.adoc
downstream/modules/analytics/proc-link-plan-job-template.adoc
downstream/modules/catalog/proc_Assigning_approval_workflow.adoc
downstream/modules/catalog/proc_Copy_portfolio.adoc
downstream/modules/catalog/proc_Copy_products.adoc
downstream/modules/catalog/proc_Delete_order_process.adoc
downstream/modules/catalog/proc_Edit_order_process.adoc
downstream/modules/catalog/proc_Editing_surveys.adoc
downstream/modules/catalog/proc_Generate-ansible-token.adoc
downstream/modules/catalog/proc_Set_order_process_portfolio.adoc
downstream/modules/catalog/proc_Set_order_process_product.adoc
downstream/modules/catalog/proc_Sharing_portfolios.adoc
downstream/titles/analytics/automation-savings-planner/master.adoc
downstream/titles/analytics/automation-savings/master.adoc
downstream/titles/analytics/job-explorer/master.adoc
downstream/titles/analytics/reports/master.adoc
downstream/titles/analytics/user-access/master.adoc
downstream/titles/catalog/getting-started/master.adoc
downstream/titles/catalog/itsm-integration/master.adoc
downstream/titles/catalog/lifecycle/master.adoc
downstream/titles/catalog/managing-products/master.adoc
downstream/titles/catalog/onboarding/master.adoc
downstream/titles/catalog/receptor/master.adoc
downstream/titles/catalog/support-matrix/master.adoc

Modify paths to images in catalog guides.
Part of AAP-2081
Affects
`titles/catalog/itsm-integration`

AAP-2081 Catalog Fix image syntax in catalog guides

---

downstream/modules/automation-hub/proc-delete-container.adoc
downstream/modules/automation-hub/proc-delete-user.adoc
downstream/modules/automation-hub/proc-edit-namespace.adoc
downstream/modules/automation-hub/proc-obtaining-org-collection-url.adoc
downstream/modules/automation-hub/proc-tag-image.adoc
downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
downstream/titles/hub/lifecycle/master.adoc
downstream/titles/hub/manage-containers/master.adoc
downstream/titles/hub/managing-user-access/master.adoc
downstream/titles/hub/uploading-collections/master.adoc
downstream/titles/hub/uploading-internal-collections/master.adoc

Backports #793 to 2.1
Modify paths to images in catalog guides.
Part of AAP-2081
Affects
titles/builder
/titles/hub/uploading-internal-collections
/titles/hub/configuring-private-hub-rh-certified
/titles/hub/uploading-collections
/titles/hub/managing-user-access
/titles/hub/manage-containers
/titles/hub/uploading-internal-collections

2.1 AAP-2081  Fix image syntax in hub and builder guides (#793)

---

downstream/assemblies/catalog/assembly-installing-receptor.adoc
downstream/modules/catalog/proc_Assigning_approval_workflow.adoc
downstream/modules/catalog/proc_Copy_portfolio.adoc
downstream/modules/catalog/proc_Copy_products.adoc
downstream/modules/catalog/proc_Delete_order_process.adoc
downstream/modules/catalog/proc_Edit_order_process.adoc
downstream/modules/catalog/proc_Editing_surveys.adoc
downstream/modules/catalog/proc_Generate-ansible-token.adoc
downstream/modules/catalog/proc_Set_order_process_portfolio.adoc
downstream/modules/catalog/proc_Set_order_process_product.adoc
downstream/modules/catalog/proc_Sharing_portfolios.adoc
downstream/titles/catalog/getting-started/master.adoc
downstream/titles/catalog/itsm-integration/master.adoc
downstream/titles/catalog/lifecycle/master.adoc
downstream/titles/catalog/managing-products/master.adoc
downstream/titles/catalog/onboarding/master.adoc
downstream/titles/catalog/receptor/master.adoc
downstream/titles/catalog/support-matrix/master.adoc

Backports #790  to 2.1
* AAP-2081 Add imagesdir declaration to analytics master.aoc files
* Modify path to images in analytics docs
Modify paths to images in catalog guides.
Part of AAP-2081
Affects
titles/catalog/itsm-integration

2.1 AAP-2081 Catalog Fix image syntax in catalog guides (#790)

---

downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc

Add imagesdir sttribute for images in titles/configuring-private-hub-rh-certified

Fix master.adoc attributes for configuring-private-hub-rh-certified

---

downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc

Per [AAP-8656](https://issues.redhat.com/browse/AAP-8656), updated the [Red Hat Ansible Automation Platform Installation Guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/index) to remove version number artefacts where appropriate.

AAP-8656 updated version numbers across document

---

downstream/modules/automation-hub/proc-set-community-remote.adoc

Replace with community.aws
This change is only made in 2.2. Changes in main and 2.3 are part of AAP-5046
ansible builder docs change/remove geerlingguy.java
https://issues.redhat.com/browse/AAP-421

Removed geerlingguy.php_role

---

downstream/assemblies/platform/assembly-operator-install-planning.adoc
downstream/modules/platform/ref-operator-ocp-version.adoc

For [AAP-2606](https://issues.redhat.com/browse/AAP-2606), added the module `ref-operator-ocp-version.adoc` to the 2.1 doc "Red Hat Ansible Automation Platform Operator Installation Guide" in the planning-installation assembly in the same place as in the renamed/refactored 2.2 (and later versions) "Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform." This new subsection provides customers with the version requirements for containers, per request from the field.

AAP-2606 Added section on OCP version compatibility for operator guide

---

downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc

In response to [AAP-4882](https://issues.redhat.com/browse/AAP-4882) - Added the following link to the Additional resources section after "Troubleshooting" topic: [Filesystem Layout](https://docs.pulpproject.org/pulpcore/installation/hardware-requirements.html#filesystem-layout).

AAP-4882 Added link to the Pulp file system layout to Ch 2.2 Add'l resources

---

downstream/modules/builder/con-optional-build-command-arguments.adoc
downstream/modules/builder/proc-customize-ee-image.adoc
downstream/modules/builder/ref-build-args-base-image.adoc

Added text to describe effect of not specifying EE_BASE_IMAGE and not using the -t switch when building.
ansible builder docs EE_BASE_IMAGE implications
https://issues.redhat.com/browse/AAP-419

Added information on builds

---

downstream/modules/builder/con-optional-build-command-arguments.adoc
downstream/modules/builder/proc-customize-ee-image.adoc
downstream/modules/builder/ref-build-args-base-image.adoc

Added text to describe effect of not specifying EE_BASE_IMAGE and not using the -t switch when building.
ansible builder docs EE_BASE_IMAGE implications
https://issues.redhat.com/browse/AAP-419

Added information on builds (#819)

---

downstream/modules/platform/ref-guidelines-hosts-groups.adoc

Change made for 2.2 when originally in Installation Guide
Note in documentation about database and automation controller location is incorrect
https://issues.redhat.com/browse/AAP-8783

Correct statement about database location

---

downstream/modules/automation-hub/proc-install-ha-hub-selinux.adoc

Backporting (cherry-picking) the following update in the original PR #812 : 
In response to [AAP-4882](https://issues.redhat.com/browse/AAP-4882) - In the [Deploying a high availability automation hub guide, chapt. 2.2](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html-single/deploying_a_high_availability_automation_hub/index#install_a_high_availability_ha_deployment_of_automation_hub_on_selinux), added the following link to the Additional resources section after the "Troubleshooting" topic: [Filesystem Layout](https://docs.pulpproject.org/pulpcore/installation/hardware-requirements.html#filesystem-layout).

Backport-2.2-818 AAP-4882 Added link to the Pulp file system layout info

---

release-notes/topics/hub-460.adoc

Added entry deprecating the  pulp_firewalld_zone parameter
[doc] Add a note in the AAP 2.3 release notes that says "pulp_firewalld_zone" has been deprecated
https://issues.redhat.com/browse/AAP-8892

Release notes: replace pulp_firewalld_zone with automationhub_firewalld_zone

---

downstream/modules/analytics/proc-add-roles-to-group.adoc
downstream/modules/analytics/proc-add-user-to-group.adoc
downstream/modules/analytics/proc-create-groups.adoc
downstream/modules/automation-hub/proc-delete-collection.adoc
downstream/modules/automation-hub/proc-delete-namespace.adoc
downstream/modules/navigator/con-navigator-collections.adoc
downstream/modules/navigator/con-navigator-modes.adoc
downstream/modules/navigator/proc-browse-collections-tui.adoc
downstream/modules/navigator/proc-execute-playbook-tui.adoc
downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
downstream/modules/navigator/proc-review-ansible-config-tui.adoc
downstream/modules/navigator/proc-review-artifact.adoc
downstream/modules/navigator/proc-review-docs-tui.adoc
downstream/modules/navigator/proc-review-ee-tui.adoc
downstream/modules/security/con-automate-idps-rules.adoc
downstream/modules/security/con-automating-firewall-rules.adoc
downstream/modules/security/proc-creating-firewall-rule.adoc
downstream/modules/security/proc-deleting-firewall-rule.adoc

Backporting requested changes in [AAP-4206](https://issues.redhat.com/browse/AAP-4206) to 2.3. These changes add alt-text to images in Analytics, the Navigator Guide, the Security Guide, and Automation Hub.
Backports #833

[2.3] AAP-4206: Add alt-text to images (#833)

---

downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
downstream/titles/hub/install/master.adoc

Title changed from 'Managing Red Hat Ansible Content Collections and Ansible Galaxy collections in automation hub' to 'Managing Red Hat Certified and Ansible Galaxy collections in automation hub'. Also links in the hub install doc updated to 2.3.
Change Document Title
https://issues.redhat.com/browse/AAP-9192

Document title changed

---

downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
downstream/titles/hub/install/master.adoc

Backports #850 to 2.3
Title changed from 'Managing Red Hat Ansible Content Collections and Ansible Galaxy collections in automation hub' to 'Managing Red Hat Certified and Ansible Galaxy collections in automation hub'. Also links in the hub install doc updated to 2.3.
Change Document Title
https://issues.redhat.com/browse/AAP-9192

Document title changed (#850)

---

downstream/modules/analytics/proc-add-roles-to-group.adoc
downstream/modules/analytics/proc-add-user-to-group.adoc
downstream/modules/analytics/proc-create-groups.adoc
downstream/modules/automation-hub/proc-delete-collection.adoc
downstream/modules/automation-hub/proc-delete-namespace.adoc
downstream/modules/navigator/con-navigator-collections.adoc
downstream/modules/navigator/con-navigator-modes.adoc
downstream/modules/navigator/proc-browse-collections-tui.adoc
downstream/modules/navigator/proc-execute-playbook-tui.adoc
downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
downstream/modules/navigator/proc-review-ansible-config-tui.adoc
downstream/modules/navigator/proc-review-artifact.adoc
downstream/modules/navigator/proc-review-docs-tui.adoc
downstream/modules/navigator/proc-review-ee-tui.adoc
downstream/modules/security/con-automate-idps-rules.adoc
downstream/modules/security/con-automating-firewall-rules.adoc
downstream/modules/security/proc-creating-firewall-rule.adoc
downstream/modules/security/proc-deleting-firewall-rule.adoc

This PR adds alt-text to images in release 2.2 as requested in [AAP-4206](https://issues.redhat.com/browse/AAP-4206).
Affected titles: Analytics, Navigator Guide, Security Guide.

[Backport] - AAP-4206: Add alt-text to images (#833)

---

downstream/modules/builder/ref-build-args-base-image.adoc

* Added default and rpm build values of image.
Updated table with default values (normal and with RH RPM build.
Correct default value for EE_XXXX_IMAGE
Affects `titles/builder/`
https://issues.redhat.com/browse/AAP-8980

2.3 Added default values of image. (#839)

---

downstream/modules/builder/ref-build-args-base-image.adoc

* Added default and rpm build values of image.
Updated table with default values (normal and with RH RPM build.
Correct default value for EE_XXXX_IMAGE
Affects `titles/builder/`
Backpors #839 to 2.2
https://issues.redhat.com/browse/AAP-8980

2.2 Added default values of image. (#839)

---

downstream/modules/platform/ref-postgresql-requirements.adoc

Removing incorrect PostgreSQL statement as AAP 2.x doesn't use SCL.
Remove incorrect PostgreSQL statement.
https://issues.redhat.com/browse/AAP-9320

Removing instance of PostgreSQL statement

---

downstream/modules/platform/ref-postgresql-requirements.adoc

Removing incorrect PostgreSQL statement as AAP 2.x doesn't use SCL.
Remove incorrect PostgreSQL statement.
https://issues.redhat.com/browse/AAP-9320

Removing instance of PostgreSQL statement (#862)

---

downstream/assemblies/central-auth/assembly-central-auth-hub.adoc

This PR fixes a broken attribute by removing the extra space between the brackets.

CA-FIX - removed extra space to fix broken attribute

---

downstream/assemblies/platform/assembly-system-requirements.adoc
downstream/modules/platform/proc-enable-hstore-extension.adoc

New procedure added to Planning Guide
Document 'hstore' extension requirement for customer provided database
https://issues.redhat.com/browse/AAP-8913

Section added on enabling the hstore extension

---

downstream/assemblies/central-auth/assembly-central-auth-hub.adoc

This PR backports the changes from PR866 to the 2.1 branch.

[Backport] - CA-FIX - removed extra space to fix broken attribute (#866)

---

downstream/assemblies/central-auth/assembly-central-auth-hub.adoc

This PR backports the changes from PR866 to the 2.2 branch.

[Backport] CA-FIX - removed extra space to fix broken attribute (#866)

---

downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc

Automation Hub requires port 443 access for syncing certified collections. Add prereq for syncing procedure.

AAP-2086 Add port 443 access prereq for syncing collections

---

downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc

Backports #857 to 2.2
Automation Hub requires port 443 access for syncing certified collections. Add prereq for syncing procedure.
Affects titles/hub/configuring-private-hub-rh-certified

2.2 AAP-2086 Add port 443 access prereq for syncing collections (#857)

---

downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc

Backports #857  to 2.3
Automation Hub requires port 443 access for syncing certified collections. Add prereq for syncing procedure.

2.3 AAP-2086 Add port 443 access prereq for syncing collections (#857)

---

downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc

Backports https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/857 to 2.2
Automation Hub requires port 443 access for syncing certified collections. Add prereq for syncing procedure.
Affects titles/hub/configuring-private-hub-rh-certified

2.1 AAP-2086 Add port 443 access prereq for syncing collections (#857)

---

downstream/modules/platform/ref-controller-variables.adoc

Added the new variable (`supervisor_start_retry_count`) to the table in [Appendix A.5. in the Installation Guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/appendix-inventory-files-vars#ref-controller-variables)

AAP-8485 Document new variable "supervisor_start_retry_count" for AAP installer

---

downstream/modules/automation-hub/proc-create-synclist.adoc

ansible-galaxy.s3.amazonaws.com added to the list
Add ansible-galaxy.s3.amazonaws.com to list of opening
https://issues.redhat.com/browse/AAP-9697
Affects `titles/hub/create-synclist`

Updating prerequisites for a synclist in hub

---

downstream/modules/automation-hub/proc-create-synclist.adoc

* Updating prerequisites for a synclist in hub
ansible-galaxy.s3.amazonaws.com added to the list
Add ansible-galaxy.s3.amazonaws.com to list of opening
https://issues.redhat.com/browse/AAP-9697
Affects `titles/hub/create-synclist`

Updating prerequisites for a synclist in hub (#884)

---

downstream/modules/automation-hub/proc-create-synclist.adoc

* Updating prerequisites for a synclist in hub
ansible-galaxy.s3.amazonaws.com added to the list
Add ansible-galaxy.s3.amazonaws.com to list of opening
https://issues.redhat.com/browse/AAP-9697
Affects `titles/hub/create-synclist`
* Updating prerequisites for a synclist in hub
ansible-galaxy.s3.amazonaws.com added to the list
Add ansible-galaxy.s3.amazonaws.com to list of opening
https://issues.redhat.com/browse/AAP-9697
Affects titles/hub/create-synclist

Updating prerequisites for a synclist in hub (#884) (#887)

---

downstream/modules/automation-hub/proc-create-synclist.adoc

* Updating prerequisites for a synclist in hub
ansible-galaxy.s3.amazonaws.com added to the list
Add ansible-galaxy.s3.amazonaws.com to list of opening
https://issues.redhat.com/browse/AAP-9697
Affects `titles/hub/create-synclist`
* Updating prerequisites for a synclist in hub
ansible-galaxy.s3.amazonaws.com added to the list
Add ansible-galaxy.s3.amazonaws.com to list of opening
https://issues.redhat.com/browse/AAP-9697
Affects titles/hub/create-synclist

Updating prerequisites for a synclist in hub (#884) (#887) (#889)

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

Removed nginx variables, corrected name for pg_port
Update automation hub table.
https://issues.redhat.com/browse/AAP-9634
Affects titles/aap-planning-guide/

Updated automation hub ports table.

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

* Updated automation hub ports table.
Removed nginx variables, corrected name for pg_port
Update automation hub table.
https://issues.redhat.com/browse/AAP-9634
* Updated automation hub ports table
Additional change is PostgreSQL table.
Update automation hub table.
https://issues.redhat.com/browse/AAP-9634

Updated automation hub ports table. (#886)

---

downstream/modules/automation-hub/proc-configuring-the-client-to-verify-signatures.adoc
downstream/modules/automation-hub/proc-pushing-container-images-from-your-local.adoc

Bad syntax in module IDs was causing a docs build to fail.
Affects `titles/hub/manage-containers`

Modify module IDs to fix docs build problems

---

downstream/modules/platform/con-websocket-setup.adoc

This request is to clarify language around configuring websockets in the Operations Guide. Link to JIRA: https://issues.redhat.com/browse/AAP-9652
Link to google doc with drafted language: https://docs.google.com/document/d/1zdfpXi6mQthql1O0-bcWbB6gJTIsKKjJk0UNXApc8oo/edit#
A technical SME has reviewed and approved the language.

AAP 9652: clarify websocket configuration in operations guide

---

downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
downstream/modules/platform/proc-upgrade-installer.adoc
downstream/modules/platform/ref-hub-variables.adoc
downstream/modules/platform/ref-system-requirements.adoc

Corrected references from 2.2 to 2.3 in the following modules and 1 assembly:
- ../modules/platform/ref-system-requirements.adoc
- ../modules/platform/ref-hub-variables.adoc
- ../modules/platform/proc-upgrade-installer.adoc
- ../modules/navigator/proc-installing-navigator-rhel-rpm.adoc
- platform/assembly-migrate-legacy-venv-to-ee.adoc

AAP-8553 Updated references to 2.2 to 2.3

---

downstream/modules/platform/con-websocket-setup.adoc

This PR backports changes requested to the Operations Guide in https://issues.redhat.com/browse/AAP-9652 to the 2.3 release. 
Related PR: https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/897

Backport AAP 9652: clarify websocket configuration in operations guide (#897)

---

downstream/assemblies/platform/assembly-upgrading-controller.adoc

2.2 Backport of [PR 900](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/900).
* AAP-9531 updated RHEL version notation

2.2 AAP-9531 updated RHEL version notation (#900)

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

Adding catalog.redhat.com to table 4.10 for indexing execution environments
Missing catalog.redhat.com in documentation
https://issues.redhat.com/browse/AAP-10061

Addition of catalog.redhat.com

---

downstream/assemblies/platform/assembly-network-ports-protocols.adoc

Adding catalog.redhat.com to table 4.10 for indexing execution environments
Missing catalog.redhat.com in documentation
https://issues.redhat.com/browse/AAP-10061

Addition of catalog.redhat.com (#906)

---

downstream/assemblies/hub/assembly-populate-container-registry.adoc
downstream/assemblies/hub/assembly-pull-image.adoc
downstream/assemblies/platform/assembly-network-ports-protocols.adoc

* Added information about pulling container images
Added admonition and tidied the content.
Update document to reflect new Red Hat registry network changes
https://issues.redhat.com/browse/AAP-9698
* Added information about pulling container images
Moved orignal information, added it to Planning Guide also
Update document to reflect new Red Hat registry network changes
https://issues.redhat.com/browse/AAP-9698
* Added information about pulling container images
Corrections to planning guide EE table
Update document to reflect new Red Hat registry network changes
https://issues.redhat.com/browse/AAP-9698
* Added information about pulling container images
Added port number
Update document to reflect new Red Hat registry network changes
https://issues.redhat.com/browse/AAP-9698
* Added …

Added information about pulling container images (#893)

---

downstream/aap-common/sunset-catalog-content-admonition.adoc
downstream/titles/catalog/getting-started/master.adoc
downstream/titles/catalog/itsm-integration/master.adoc
downstream/titles/catalog/onboarding/master.adoc
downstream/titles/catalog/support-matrix/master.adoc
downstream/titles/worker-install/master.adoc

Added IMPORTANT admonition for the sunset of Catalog docs
Add disclaimer or note about the sun-setting of Automation Services Catalog docs in the AAP 2.2 and 2.3 repos
https://issues.redhat.com/browse/AAP-9423
Affects `titles/catalog` and `titles/worker-install`

Added admonition for Catalog docs

---

downstream/aap-common/sunset-catalog-content-admonition.adoc
downstream/titles/catalog/getting-started/master.adoc
downstream/titles/catalog/itsm-integration/master.adoc
downstream/titles/catalog/onboarding/master.adoc
downstream/titles/catalog/support-matrix/master.adoc
downstream/titles/worker-install/master.adoc

* Added admonition for Catalog docs
Added IMPORTANT admonition for the sunset of Catalog docs
Add disclaimer or note about the sun-setting of Automation Services Catalog docs in the AAP 2.2 and 2.3 repos
https://issues.redhat.com/browse/AAP-9423
Affects `titles/catalog` and `titles/worker-install`
* Added admonition for Catalog docs
Added IMPORTANT admonition for the sunset of Catalog docs
Add disclaimer or note about the sun-setting of Automation Services Catalog docs in the AAP 2.2 and 2.3 repos
https://issues.redhat.com/browse/AAP-9423
Affects titles/catalog and titles/worker-install
* Added admonition for Catalog docs
Added IMPORTANT admonition for the sunset of Catalog docs
Add disclaimer or note about the sun-setting of Automation Services Catalog docs in the AAP 2.2 and 2.3 repos …

Added admonition for Catalog docs (#924)

---

downstream/titles/catalog/itsm-integration/master.adoc
downstream/titles/catalog/onboarding/master.adoc
downstream/titles/catalog/support-matrix/master.adoc

Added missing attribute sym links to catalog docs
Add disclaimer or note about the sun-setting of Automation Services Catalog docs in the AAP 2.2 and 2.3 repos
https://issues.redhat.com/browse/AAP-9423
Affects titles/catalog

Updating attribute sym links

---

downstream/titles/catalog/itsm-integration/master.adoc
downstream/titles/catalog/onboarding/master.adoc
downstream/titles/catalog/support-matrix/master.adoc

Added missing attribute sym links to catalog docs
Add disclaimer or note about the sun-setting of Automation Services Catalog docs in the AAP 2.2 and 2.3 repos
https://issues.redhat.com/browse/AAP-9423
Affects titles/catalog

Updating attribute sym links (#926)

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

Moved routable hostname from controller to general variables.
Variable routable_hostname should be moved to A1 general section rather than controller specific
https://issues.redhat.com/browse/AAP-10627

Moved 'routable_hostname' variable

---

downstream/modules/platform/ref-controller-variables.adoc
downstream/modules/platform/ref-general-inventory-variables.adoc

* Moved routable hostname from controller to general variables. https://issues.redhat.com/browse/AAP-10627

2.3 Moved 'routable_hostname' variable (#928)

---

downstream/attributes/attributes.adoc

`RH-SSO` is allowed in Red Hat documentation, even though it is not listed in the official Red Hat product names spreadsheet.
Create an attribute for `RH-SSO` in case the abbreviation is changed to something like RHSSO in future.

Add attribute for RH-SSO

---

downstream/modules/platform/ref-hub-variables.adoc

Part of AAP-4587 "connecting Automation Hub to an existing Red Hat SSO environment"
Adds SSO variables to the Hub inventory variables tables.
Affects `/titles/aap-installation-guide`

AAP-4587 Add SSO variables to hub inventory tables

---

downstream/modules/platform/proc-create-keycloak-client.adoc

Changed {HubName} to automation-hub
Docs for using RH-SSO Operator w/PAH Operator involve using a breaking change
https://issues.redhat.com/browse/AAP-10768

Corrected Keycloak client instructions

---

downstream/modules/platform/proc-create-keycloak-client.adoc

* Corrected Keycloak client instructions Changed {HubName} to automation-hub
Docs for using RH-SSO Operator w/PAH Operator involve using a breaking change https://issues.redhat.com/browse/AAP-10768

2.3 Corrected Keycloak client instructions (#947)

---

downstream/modules/analytics/proc-link-plan-job-template.adoc

Fix a typo in an image reference.
Affects `titles/analytics/automation-savings-planner`
Backport to 2.3, 2.2 and 2.1.

Fix image ref in analytics module

---

downstream/modules/analytics/proc-link-plan-job-template.adoc

Backports #957 to 2.3
Fix a typo in an image reference.
Affects `titles/analytics/automation-savings-planner`

2.3 Fix image ref in analytics module

---

downstream/modules/analytics/proc-link-plan-job-template.adoc

Backports #957 to 2.1
Fix a typo in an image reference.
Affects `titles/analytics/automation-savings-planner`

2.1 Fix image ref in analytics module

---

downstream/modules/analytics/proc-link-plan-job-template.adoc

Backports #957 to 2.2
Fix a typo in an image reference.
Affects `titles/analytics/automation-savings-planner`

2.2 Fix image ref in analytics module

---

downstream/modules/platform/ref-sso-variables.adoc

Part of AAP-4587 "connecting Automation Hub to an existing Red Hat SSO environment"
Backports changes introduced in #916 to 2.3, but it isn't a direct cherry-pick.
The affected table in PR916 is the Hub variables table (Hub and SSO tables are merged in AAP2.4++), while the hub and SSO tables are separate in 2.3
Adds SSO variables to the SSO inventory variables tables.
Affects /titles/aap-installation-guide

2.3 AAP-4587 Add variables to SSO table (#916)

---

downstream/modules/platform/ref-sso-variables.adoc

Part of AAP-4587 "connecting Automation Hub to an existing Red Hat SSO environment"
Backports changes introduced in #916 to 2.2, but it isn't a direct cherry-pick.
The affected table in PR916 is the Hub variables table (Hub and SSO tables are merged in AAP2.4++), while the hub and SSO tables are separate in 2.2.
Adds SSO variables to the SSO inventory variables tables.
Affects /titles/aap-installation-guide

2.2 AAP-4587 Add variables to SSO table (#916)

---

downstream/titles/hub/install/docinfo.xml

Fix the release number in `docinfo.xml`
Affects `/titles/hub/install`

2.2 Update doc metadata for Hub Install guide

---

downstream/assemblies/platform/assembly-aap-activate.adoc
downstream/assemblies/platform/assembly-aap-manifest-files.adoc
downstream/assemblies/platform/assembly-aap-post-installation.adoc
downstream/modules/platform/proc-aap-activate-with-credentials.adoc
downstream/modules/platform/proc-aap-activate-with-manifest.adoc
downstream/modules/platform/proc-aap-add-merge-subscriptions.adoc
downstream/modules/platform/proc-aap-create-subscription-allocation.adoc
downstream/modules/platform/proc-aap-generate-manifest-file.adoc
downstream/titles/aap-operations-guide/master.adoc

This PR backports the changes for PR822 to the 2.3 branch and includes the following changes: 
Add chapter titled "Activating AAP" to the Operations Guide.
Included procedures for activating aap with a subscription manifest in both the aap interface or via manual upload.
Included procedures for activating aap using customer or Satellite credentials.
Add chapter titled "Obtaining a manifest file"
Included procedures for obtaining and downloading a manifest file.

[Backport] AAP-6074 added subscription manifest procedures to activate aap (#822)

---

downstream/snippets/published-24.txt

Add a list of docs to be published in AAP 2.4 to the `snippets/` folder.
Any titles not in this list will be archived.

AAP-11399 Add list of published 2.4 docs to snippets folder

---

downstream/assemblies/platform/assembly-standalone-hub-ext-database.adoc
downstream/modules/platform/ref-ldap-config-on-pah.adoc

Bringing the changes for AAP-4381 into the version 2.2 branch. Original changes for the 2.3 branch were added through PR#980
Link to preview draft of 2.2 change (VPN required):  http://file.rdu.redhat.com/~ddacosta/AAP4381/master.html
See section 3.4.3. Example standalone automation hub inventory file

Adding changes for AAP4381 to the 2.2 branch

---

downstream/assemblies/platform/assembly-platform-install-scenario.adoc
downstream/modules/platform/ref-ldap-config-on-pah.adoc

Added new reference module w/ two sets of instructions (discrete headings) to the [Red Hat Ansible Automation Platform Installation Guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/index):
- LDAP configuration on private automation hub (`ref-ldap-config-on-pah.adoc`)
- Setting up your inventory file variables
- Configuring extra LDAP parameters
- Updated` assembly-platform-install-scenario.adoc` to include the xref for this new topic `ref-ldap-config-on-pah.adoc`.

Backport-2.3-980 New content on LDAP configuration for private automation hub

---

downstream/titles/hub/install/docinfo.xml
downstream/titles/hub/install/master.adoc

This PR corrects the doc title mistakenly removed in PR813.

Fixed missing doc title in master file and lower case title in docinfo

---

downstream/modules/platform/con-install-scenario-examples.adoc

Adding mention in the inventory examples that clearly states [database] cannot be used to point to another host in the AAP cluster.
Document internal vs external postgres supported installations
https://issues.redhat.com/browse/AAP-11781
Affects `titles/aap-installation-guide`

Add internal database host installation note (#1000)

---

downstream/modules/platform/con-install-scenario-examples.adoc

Adding mention in the inventory examples that clearly states [database] cannot be used to point to another host in the AAP cluster.
Document internal vs external postgres supported installations
https://issues.redhat.com/browse/AAP-11781
Affects `titles/aap-installation-guide`

Add internal database host installation note (#1000) (#1013)

---

downstream/modules/platform/ref-ldap-config-on-pah.adoc

Fixed asciidoc note syntax: it was generating a warning during the build process.
Affects `titles/aap-installation-guide/`

Fix note syntax

---

downstream/modules/platform/ref-ldap-config-on-pah.adoc

Fixed asciidoc note syntax: it was generating a warning during the build process.
Affects `titles/aap-installation-guide/`

2.3 Fix note syntax (#1023)

---

downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
downstream/assemblies/hub/assembly-validated-content.adoc
downstream/modules/automation-hub/con-rh-certified-synclist.adoc
downstream/modules/automation-hub/proc-set-rhcertified-remote.adoc
downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc

Instructions for content without bundle installer.
Create documentation for "Seed Validated Content into any deployments of Private Automation Hub when not using bundler installer"
Affects `hub/configuring-private-hub-rh-certified`
https://issues.redhat.com/browse/AAP-10670

Added instructions for adding content

---

downstream/modules/platform/ref-controller-variables.adoc

Fixes issue in [AAP-12313](https://issues.redhat.com/browse/AAP-12313). For more context, see this [Slack thread](https://redhat-internal.slack.com/archives/C035VBWU98D/p1684429969208019). 
This change will add an underscore to an automation controller variable.

AAP-12313: adds an underscore to an automation controller variable 

---

downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
downstream/assemblies/hub/assembly-validated-content.adoc
downstream/modules/automation-hub/con-rh-certified-synclist.adoc
downstream/titles/hub/configuring-private-hub-rh-certified/docinfo.xml
downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc

* Added instructions for adding content Instructions for content without bundle installer
Create documentation for "Seed Validated Content into any deployments of Private Automation Hub when not using bundler installer" https://issues.redhat.com/browse/AAP-10670
Removed text for AAP-9650.
"Seed Validated Content into any deployments of Private Automation Hub when not using bundler installer"

Added instructions for adding content (#966)

---

downstream/modules/platform/con-aap-installation-prereqs.adoc

Jira link: [AAP-8366](https://issues.redhat.com/browse/AAP-8366)
Added prerequisite and note stating that users should use fully updated nodes prior to installing AAP.

AAP-8366: Recommend using fully updated nodes to install AAP

---

downstream/modules/builder/proc-installing-builder.adoc

Updated command in file to single step to install builder and enable the repo. 
dnf install --enablerepo ansible-automation-platform-2.3-for-rhel-8-x86_64-rpms ansible-builder
**Note:** command will be changed to  `dnf install --enablerepo ansible-automation-platform-2.2-for-rhel-8-x86_64-rpms ansible-builder` during backport to the 2.2 branch.
Preview link (VPN required): http://file.rdu.redhat.com/~ddacosta/AAP12541/master.html

AAP-12541 - Update procedure for enabling the repo

---

downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc

Jira link: [AAP-4359](https://issues.redhat.com/browse/AAP-4359)
Following are the minor changes:
- Added the info. 'when migrating from AAP 2.0 or earlier to AAP 2.1 or later, users now have the option to add their existing automationhub api token or generate a new one.'
- Corrected the flag for 'generate_automationhub_token='

JIRA-AAP-4359: Added the scenario to import or generate API tokens in AAP installer

---

downstream/modules/platform/ref-system-requirements.adoc

Changed values in system requirements table.
Minimal version of Ansible is incorrect in docs
Affects `/titles/aap-planning-guide/`
https://issues.redhat.com/browse/AAP-11993

Corrected minimum and required ansible versions

---

downstream/modules/platform/ref-system-requirements.adoc

Changed Ansible version
Minimal version of Ansible is incorrect in docs
Affects `/titles/aap-installation-guide/`
https://issues.redhat.com/browse/AAP-11993

2.2 Updated Ansible version AAP-11993 for 2.2

---

downstream/modules/platform/ref-system-requirements.adoc

Changed ansible version
Minimal version of Ansible is incorrect in docs
Affects `/titles/aap-planning-guide/`
https://issues.redhat.com/browse/AAP-11993

Updated ansible version AAP-11993 for 2.3

---

downstream/modules/platform/ref-system-requirements.adoc

* Corrected minimum and required ansible versions
Changed values in system requirements table.
Affects planning guide
Backports #1055 
https://issues.redhat.com/browse/AAP-11993

2.4 Corrected minimum and required ansible versions (#1055)

---

downstream/titles/hub/repo-management/master.adoc

AAP-12684
Add direct documentation feedback module to the `titles/hub/repo-management/` title.
Backport to 2.4

AAP-12684 Add direct doc feedback module to repo management doc

---

downstream/modules/automation-hub/con-create-api-token.adoc
downstream/modules/automation-hub/proc-create-api-token-pah.adoc
downstream/modules/automation-hub/proc-create-api-token.adoc
downstream/titles/hub/getting-started/master.adoc

[AAP-11480](https://issues.redhat.com/browse/AAP-11480)
Updated [Chapter 1: Creating the Red Hat automation hub API Token](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/1.2/html/getting_started_with_red_hat_ansible_automation_hub/proc-create-api-token) to include a subsection 1.2 for creating the API token in PAH. Procedure differs slightly in PAH from procedure in automation hub.

AAP-11480 updated Getting Started to include instructions for PAH

---

downstream/titles/aap-hardening/master.adoc

Jira link [AAP-1636](https://issues.redhat.com/browse/AAP-1636)
Fixed the arrangement of the titles to:
1. Introduction
2. Hardening Ansible Automation Platform
3. Ansible Automation Platform Compliance
4. Ansible Automation Platform as a security enabling tool

AAP-1636-fix: Reorder of titles

---

downstream/titles/eda/eda-user-guide/docinfo.xml
downstream/titles/eda/eda-user-guide/master.adoc

This PR modifies the titles in docinfo and master.adoc to be an exact match to fix the failure in the Pantheon build.

Modified title fields to remove attribute and match to fix build

---

downstream/assemblies/platform/assembly-aap-platform-components.adoc
downstream/assemblies/platform/assembly-supported-installation-scenarios.adoc
downstream/modules/platform/con-about-eda-controller.adoc
downstream/modules/platform/con-single-eda-controller-with-internal-database.adoc
downstream/modules/platform/ref-system-requirements.adoc

Add content to the RH AAP Planning Guide in "[Chapter 2 RH AAP Platform components](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html-single/red_hat_ansible_automation_platform_planning_guide/index#ref-aap-components)" as section 2.7

AAP-10975A Add installation-related content to the AAP Planning Guide

---

downstream/modules/platform/ref-hub-variables.adoc

Updates automation hub variables to correct spelling in automationhub_enable_unauthenticated_collection_access and to add info about setting the parameter to "true."
See [AAP-13402](https://issues.redhat.com/browse/AAP-13402) for more info.

AAP-13402 update automation hub variables

---

downstream/modules/platform/ref-hub-variables.adoc

Updates automation hub variables to correct spelling in automationhub_enable_unauthenticated_collection_access and to add info about setting the parameter to "true." This change affects the Installation Guide. 
This PR backports the changes to the 2.4 release. 
See [AAP-13402](https://issues.redhat.com/browse/AAP-13402) for more info.

backport 2.4: AAP-13402 update automation hub variables (#1092)

---

downstream/modules/platform/ref-hub-variables.adoc

Updates automation hub variables to correct spelling in automationhub_enable_unauthenticated_collection_access and to add info about setting the parameter to "true." This change affects the Installation Guide.
This PR backports the changes to the 2.3 release.
See [AAP-13402](https://issues.redhat.com/browse/AAP-13402) for more info.

Backport 2.3: AAP-13402 update automation hub variables (#1092)

---

downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
downstream/titles/aap-operator-installation/master.adoc

Based on [PR #1050](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1050):
Created new assembly and module for instructions on installing EDA on AAP operator on OpenShift Container Platform. Also added new assembly to master. adoc.

Backport-2.4-1050 AAP-10975C New chapter on EDA installation w/ AAP operator on OCP

---

downstream/assemblies/platform/assembly-aap-manifest-files.adoc

This PR fixes issues found in the Operations Guide during the pre-release verification check, changes include:
Fix broken link to the customer portal.

opguide24 - fix broken link to the customer portal

---

downstream/assemblies/platform/assembly-aap-manifest-files.adoc

This PR backports the changes for #1108 to the 2.4 branch and fixes a broken link.

[Backport] opguide24 - fix broken link to the customer portal (#1108)

---

downstream/attributes/attributes.adoc

Update download URL to 
` https://access.redhat.com/downloads/content/480/ver=2.4/rhel---9/2.4/x86_64/product-software`

Update download URL attribute for 2.4

---

downstream/attributes/attributes.adoc

Update download URL to 
` https://access.redhat.com/downloads/content/480/ver=2.4/rhel---9/2.4/x86_64/product-software`

2.4 Update download URL attribute for 2.4 (#1111)

---

downstream/titles/navigator-guide/docinfo.xml

This PR fixes the docinfo.xml title to match the master.adoc and Pantheon titles.

ncg2.4 - fix mismatch between title in master and docinfo files

---

downstream/titles/navigator-guide/docinfo.xml

This PR backports the changes for #1124 to the 2.4 branch.

[Backport] ncg2.4 - fix mismatch between title in master and docinfo files (#1124)

---

downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
downstream/modules/eda/proc-eda-set-up-new-project.adoc
downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
downstream/modules/eda/proc-eda-set-up-token.adoc

Edits made to descriptions lists that didn't render in Pantheon
Correcting "Description" lists in EDA controller user guide
https://issues.redhat.com/browse/AAP-13542
Affects `titles/eda-user-guide

Making edits to the description lists of user guide

---

downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
downstream/modules/eda/proc-eda-set-up-new-project.adoc
downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
downstream/modules/eda/proc-eda-set-up-token.adoc

Edits made to descriptions lists that didn't render in Pantheon
Correcting "Description" lists in EDA controller user guide
https://issues.redhat.com/browse/AAP-13542
Affects `titles/eda-user-guide

Making edits to the description lists of user guide (#1140)

---

downstream/assemblies/hub/assembly-validated-content.adoc
downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
downstream/modules/dev-guide/con-content-workflows.adoc
downstream/modules/platform/con-aap-upgrade-prereq.adoc
downstream/modules/platform/proc-choosing-obtaining-installer.adoc
downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
downstream/modules/platform/proc-installing-with-internet.adoc
downstream/modules/platform/proc-installing-without-internet.adoc
downstream/modules/platform/proc-upgrade-installer.adoc
downstream/modules/platform/ref-hub-configs.adoc
downstream/titles/hub/install/master.adoc

Fix the links in 2.4 that use the `{PlayformVers}` attribute

Fix broken links that use PlatformVers attribute in 2.4 docs

---

downstream/modules/eda/ref-installing-eda-controller-on-aap.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc

Last link to EDA variables appendix in Chap 3 of the "Getting Started with EDA Guide" was landing at the top of the Appendix section of the Installation Guide. Updated to land in Appendix 5 in the Installation Guide where the EDA variables are.

AAP-13585 Correction to EDA variables appendix link in GS w/ EDA guide 

---

downstream/modules/eda/ref-installing-eda-controller-on-aap.adoc
downstream/modules/platform/ref-eda-controller-variables.adoc

Last link to EDA variables appendix in Chap 3 of the "Getting Started with EDA Guide" was landing at the top of the Appendix section of the Installation Guide. Updated to land in Appendix 5 in the Installation Guide where the EDA variables are.

Backport -2.4 -1150 AAP-13585 Correction to EDA variables appendix link in GS w/ EDA guide

---

downstream/archive/archived-modules/platform/ref-copyright.adoc
downstream/modules/builder/con-about-ee.adoc
downstream/modules/builder/con-why-ee.adoc
downstream/modules/dev-guide/proc-create-role.adoc
downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/proc-install-cli-aap-operator.adoc

To locate hidden characters in the repo, run the following command from the `downstream` directory:
```
find  . -name "*.adoc" -exec pcregrep --color='auto' -n '[\xa0]'  {} + ;
```
The above command works on a Mac.
The hidden character is an NBSP character. It's usually introduced when you copy text from a Google doc into an editor.

Delete hidden characters

---

downstream/archive/archived-modules/platform/ref-copyright.adoc
downstream/modules/builder/con-about-ee.adoc
downstream/modules/builder/con-why-ee.adoc
downstream/modules/dev-guide/proc-create-role.adoc
downstream/modules/platform/con-about-operator.adoc
downstream/modules/platform/proc-install-cli-aap-operator.adoc

Backports #1156 to 2.4: Delete hidden characters.
To locate hidden characters in the repo, run the following command from the `downstream` directory:
```
find  . -name "*.adoc" -exec pcregrep --color='auto' -n '[\xa0]'  {} + ;
```
The above command works on a Mac.
The hidden character is an NBSP character. It's usually introduced when you copy text from a Google doc into an editor.

Delete hidden characters (#1156)

---

downstream/titles/release-notes/topics/aap-24.adoc
downstream/titles/release-notes/topics/controller-440.adoc
downstream/titles/release-notes/topics/docs-24.adoc
downstream/titles/release-notes/topics/platform-intro.adoc

This PR backports the broken link fixes in AAP 2.4 release notes.
See PR [#1163](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1163)

Backport pull request #1163 from main to 2.4

---

downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc

Backports #1175 to 2.4
Affects `/titles/upgrade/`
Fix a formatting issue in Chapter 4. Migrating isolated nodes to execution nodes on the customer portal.
The chapter is surrounded by a box:

2.4 AAP-13660 Fix formatting issues in 2.4 Upgrade guide (#1175)

---

downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
downstream/modules/platform/ref-single-controller-ext-customer-managed-db.adoc
downstream/modules/platform/ref-single-controller-ext-installer-managed-db.adoc
downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
downstream/modules/platform/ref-standalone-hub-ext-database-customer-provided.adoc
downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc
downstream/modules/platform/ref-standalone-hub-inventory.adoc

Mainly in inventory file examples
[DDF] acme.org is not owned by Red Hat, please use example.com or similar, explicitly reserved for documentation, domains
https://issues.redhat.com/browse/AAP-13632

Replace acme.org with example.com

---

downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
downstream/modules/platform/ref-single-controller-ext-customer-managed-db.adoc
downstream/modules/platform/ref-single-controller-ext-installer-managed-db.adoc
downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc
downstream/modules/platform/ref-standalone-hub-ext-database-customer-provided.adoc
downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc
downstream/modules/platform/ref-standalone-hub-inventory.adoc

* Replace acme.org with example.com
Mainly in inventory file examples
[DDF] acme.org is not owned by Red Hat, please use example.com or similar, explicitly reserved for documentation, domains
https://issues.redhat.com/browse/AAP-13632
* Replace acme.org with example.com
Caught missing instance
[DDF] acme.org is not owned by Red Hat, please use example.com or similar, explicitly reserved for documentation, domains
https://issues.redhat.com/browse/AAP-13632

Replace acme.org with example.com (#1179)

---

downstream/modules/platform/ref-system-requirements.adoc

Updated table entries
[DDF] If Ansible version 2.15 is *required*, I would expect the setup playbook to install that, and not 2.14?
https://issues.redhat.com/browse/AAP-13633

Corrected ansible version

---

downstream/modules/platform/ref-system-requirements.adoc

Updated table entries
[DDF] If Ansible version 2.15 is *required*, I would expect the setup playbook to install that, and not 2.14?
https://issues.redhat.com/browse/AAP-13633

Corrected ansible version (#1184)

---

downstream/modules/platform/ref-system-requirements.adoc

Updated information
[DDF] If Ansible version 2.15 is *required*, I would expect the setup playbook to install that, and not 2.14?
https://issues.redhat.com/browse/AAP-13633

Corrected ansible version for 2.3

---

downstream/modules/platform/ref-system-requirements.adoc

Corrrected wording
[DDF] If Ansible version 2.15 is *required*, I would expect the setup playbook to install that, and not 2.14?
https://issues.redhat.com/browse/AAP-13633

Corrected Ansible version for 2.2

---

downstream/assemblies/platform/assembly-platform-install-scenario.adoc

[AAP-12941](https://issues.redhat.com/browse/AAP-12941)
Change made in [Ch. 2 Installing Red Hat Automation Platform](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#doc-wrapper)
**Original Behavior**
Duplicate link:
[Ansible Automation Platform with an external (installer managed) database](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-example-platform-ext-database-customer-provided_platform-install-scenario)
**New Behavior**
One of the links now labelled as:
[Ansible Automation Platform with an external (customer …

AAP-12941 updated link title

---

downstream/assemblies/platform/assembly-platform-install-scenario.adoc

[AAP-12941](https://issues.redhat.com/browse/AAP-12941)
Change made in [Ch. 2 Installing Red Hat Automation Platform](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#doc-wrapper)
Original Behavior
Incorrect link title:
[Ansible Automation Platform with an external (customer **managed**) database](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-example-platform-ext-database-customer-provided_platform-install-scenario)
New Behavior
Link now titled as:
[Ansible Automation Platform with an external (customer **provided**) …

AAP-12941A updated wording within link title

---

downstream/assemblies/platform/assembly-platform-install-scenario.adoc

2.4 Backport of [PR 1110](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1110)
[AAP-12941](https://issues.redhat.com/browse/AAP-12941)
Change made in [Ch. 2 Installing Red Hat Automation Platform](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#doc-wrapper)
Original Behavior
Incorrect link title:
[Ansible Automation Platform with an external (customer managed) database](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-example-platform-ext-database-customer-provided_platform-install-sc …

AAP-12941A updated wording within link title (#1110)

---

downstream/modules/security/con-requirements.adoc

Delete empty additional resources section.
It was causing the module following it to be enclosed in a box.

Delete empty additional resources section

---

downstream/modules/security/con-requirements.adoc

Backports #1198 to 2.2
Delete empty additional resources section.
It was causing the module following it to be enclosed in a box.

2.2 Delete empty additional resources section (#1198)

---

downstream/modules/platform/proc-aap-controller-backup.adoc
downstream/modules/platform/proc-aap-hub-backup.adoc

Corrected wording
[DDF] vague wording. Should be "Enter the Deployment name of the deployed AAP instance being backed up. For example if your
https://issues.redhat.com/browse/AAP-13691

Updated vague wording

---

downstream/modules/platform/proc-aap-controller-backup.adoc
downstream/modules/platform/proc-aap-hub-backup.adoc

* Updated vague wording [DDF] vague wording. Should be "Enter the Deployment name of the deployed AAP instance being backed up. For example if your
https://issues.redhat.com/browse/AAP-13691

2.4 Updated vague wording (#1180)

---

downstream/modules/dev-guide/proc-downloading-base-ees.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-483.
Change made:
Corrected the login instructions read podman login registry.redhat**.com** to registry.redhat**.io**.

AAP-483: Corrected the podman login registry address

---

downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc
downstream/modules/platform/ref-standalone-hub-inventory.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-433.
Changes made:
- Replaced loopback address (127.0.0.1) to placeholder <FQDN> in automation hub inventory example (See examples in sections 2.3.4 and section 2.4.4)
Affects `titles/aap-installation-guide/`

2.1 AAP-433: Removed loopback address in automation hub inventory example

---

downstream/archive/archived-assemblies/aap-on-azure/assembly-aap-azure-install.adoc
downstream/archive/archived-modules/platform/proc-configuring-proxy-support-controller.adoc
downstream/assemblies/builder/assembly-intro-to-builder.adoc
downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
downstream/modules/platform/ref-controller-system-requirements.adoc
downstream/modules/security/con-about-firewall-policy-management.adoc
downstream/modules/security/con-automate-idps-rules.adoc
downstream/modules/security/proc-creating-idps-rule.adoc

Empty additional resources sections are causing the assemblies or modules that follow them to be enclosed in a box.
Delete empty sections.

Remove empty Additional Resources sections

---

downstream/assemblies/aap-on-azure/assembly-aap-azure-install.adoc
downstream/assemblies/builder/assembly-intro-to-builder.adoc
downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
downstream/modules/platform/proc-configuring-proxy-support-controller.adoc
downstream/modules/platform/ref-controller-system-requirements.adoc
downstream/modules/security/con-about-firewall-policy-management.adoc
downstream/modules/security/con-automate-idps-rules.adoc
downstream/modules/security/proc-creating-idps-rule.adoc

Empty additional resources sections are causing the assemblies or modules that follow them to be enclosed in a box.
Delete empty sections.

2.3 Remove empty Additional Resources sections (#1203)

---

downstream/archive/archived-assemblies/aap-on-azure/assembly-aap-azure-install.adoc
downstream/archive/archived-modules/platform/proc-configuring-proxy-support-controller.adoc
downstream/assemblies/builder/assembly-intro-to-builder.adoc
downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
downstream/modules/platform/ref-controller-system-requirements.adoc
downstream/modules/security/con-about-firewall-policy-management.adoc
downstream/modules/security/con-automate-idps-rules.adoc
downstream/modules/security/proc-creating-idps-rule.adoc

Empty additional resources sections are causing the assemblies or modules that follow them to be enclosed in a box.
Delete empty sections.

2.4 Remove empty Additional Resources sections (#1203)

---

downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

Also amended automationhub_pg_host
Event driven ansible inventory variables are missing automationedacontroller_pg_*
https://issues.redhat.com/browse/AAP-14193

Added automationedacontoller_pg_* variables

---

downstream/modules/platform/ref-eda-controller-variables.adoc
downstream/modules/platform/ref-hub-variables.adoc

* Added automationedacontoller_pg_* variables Also amended automationhub_pg_host
Event driven ansible inventory variables are missing automationedacontroller_pg_* https://issues.redhat.com/browse/AAP-14193

Added automationedacontoller_pg_* variables (#1224)

---

downstream/modules/dev-guide/proc-downloading-base-ees.adoc

This PR backports PR https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1218 from main to AAP v2.2.

Backport PR #1218 to AAP v2.2

---

downstream/modules/dev-guide/proc-downloading-base-ees.adoc

This PR backports PR https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1218 from main to AAP v2.4.

Backport PR #1218 to AAP v2.4

---

downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc

This PR addresses JIRA https://issues.redhat.com/browse/AAP-537.
Following are the changes:
- Updated ansible-builder version no. from 'sudo yum install ansible-builder-1.0.1-2.el8ap.noarch.rpm' to 'ansible-builder-1.2.0-1.el9ap.noarch.rpm'
- Updated Python version no. from 'python38-requirements-parser-0.2.0-3.el8ap.noarch.rpm' to 'python38-requirements-parser-0.2.0-4.el9ap.noarch.rpm'

AAP-537-v23: Corrected the Ansible Builder and Python38 version number

---

downstream/assemblies/platform/assembly-aap-migration.adoc

[AAP-14132](https://issues.redhat.com/browse/AAP-14132)
**Actual Behavior**
+ A VM-based installation of automation controller or automation hub,
+ An Openshift instance of Ansible Tower 3.8.6 (Ansible Automation Platform 1.2), or
+ An AWX instance
**Expected Behavior**
+ A VM-based installation of Ansible Tower 3.8.6, automation controller or automation hub,
+ An Openshift instance of Ansible Tower 3.8.6 (Ansible Automation Platform 1.2)

AAP-14132 updated Chapter 8. Migrating RH AAP to AAP Operator

---

downstream/assemblies/platform/assembly-aap-migration.adoc

2.4 Backport for [AAP-14132](https://issues.redhat.com/browse/AAP-14132)
**Original behavior**
A VM-based installation of automation controller or automation hub,
An Openshift instance of Ansible Tower 3.8.6 (Ansible Automation Platform 1.2), or
An AWX instance
**Amended behavior**
A VM-based installation of Ansible Tower 3.8.6, automation controller or automation hub,
An Openshift instance of Ansible Tower 3.8.6 (Ansible Automation Platform 1.2)

AAP-14132 updated Chapter 8. Migrating RH AAP to AAP Operator (#1219)

---

release-notes/master.adoc
release-notes/topics/aap-126.adoc
release-notes/topics/hub-421.adoc
release-notes/topics/hub-422.adoc
release-notes/topics/hub-423.adoc
release-notes/topics/hub-424.adoc
release-notes/topics/hub-426.adoc
release-notes/topics/insights-062021.adoc
release-notes/topics/insights-102021.adoc
release-notes/topics/platform-intro.adoc
release-notes/topics/tower-intro-381.adoc
release-notes/topics/tower-intro-382.adoc
release-notes/topics/tower-intro-383.adoc
release-notes/topics/tower-intro-384.adoc

This PR is to make similar release notes restructuring changes (done in AAP 2.4) in AAP 1.2 release notes.
JIRA: https://issues.redhat.com/browse/AAP-14410.
Changes:
As per the release notes restructuring efforts, following changes are made:
- Restructured AAP 1.2 release notes based on AAP versions instead of release date.
- Removed release numbers of components like controller, hub, and so on.
- Retained only 1.2 specific updates

AAP-14410: Restructured the AAP 1.2 release notes

---

release-notes/master.adoc
release-notes/topics/aap-22.adoc
release-notes/topics/aap-221.adoc
release-notes/topics/controller-420.adoc
release-notes/topics/hub-450.adoc
release-notes/topics/operator-220.adoc
release-notes/topics/platform-intro.adoc

This PR is to make similar release notes restructuring changes (done in AAP 2.4) in AAP 2.2 release notes.
JIRA: https://issues.redhat.com/browse/AAP-14004
Changes:
As per the release notes restructuring efforts, following changes are made:
- Restructured AAP 2.2 release notes based on AAP versions instead of release date.
- Added section for Technology Preview and combined the Tech. Preview features into a list under that section.
- Removed release numbers of components like controller, hub, and so on.
- Added source file for AAP 2.2.1 release notes (z-stream release).
- Retained only 2.2 specific updates, and removed updates for 2.1 and all earlier versions.

AAP-14004: Restructured the AAP 2.2 release notes

---

downstream/modules/platform/ref-controller-system-requirements.adoc

This PR addresses doc update for JIRA: https://issues.redhat.com/browse/AAP-960.
Changes made:
- Updated the minimum requirements for execution nodes to remove 'at least 20GB available under /var/lib/awx' req. for execution nodes.
Once this PR is merged, I'll create backport PRs to reflect the changes in v2.4 and v2.3.

AAP-960: Updated the minimum requirements for execution nodes

---

downstream/modules/platform/ref-system-requirements.adoc

This PR addresses doc update for JIRA: https://issues.redhat.com/browse/AAP-960.
Changes made:
- Updated the minimum requirements for execution nodes to remove 'at least 20GB available under /var/lib/awx' req. for execution nodes.
- Added storage volume recommendation for execution nodes. 
Once this PR is merged, I'll create a backport PR to reflect the changes in v2.1.

AAP-960-v22: Updated the minimum requirements for execution nodes

---

release-notes/master.adoc
release-notes/topics/aap-21.adoc
release-notes/topics/aap-211.adoc
release-notes/topics/aap-212.adoc
release-notes/topics/aap-213.adoc
release-notes/topics/aap-214.adoc
release-notes/topics/controller-41.adoc
release-notes/topics/controller-411.adoc
release-notes/topics/controller-414.adoc
release-notes/topics/hub-441.adoc
release-notes/topics/hub-443.adoc
release-notes/topics/platform-intro.adoc

This PR is to make similar release notes restructuring changes (done in AAP 2.4) in AAP 2.1 release notes.
JIRA: https://issues.redhat.com/browse/AAP-14005
Changes:
As per the release notes restructuring efforts, following changes are made:
- Restructured AAP 2.1 release notes based on AAP versions instead of release date.
- Removed release numbers of components like controller, hub, and so on.
- Retained only 2.1 specific updates, and removed updates for 2.2 and other versions.

AAP-14005: Restructured the AAP 2.1 release notes

---

downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc

Updates to code samples in the Red Hat Ansible Automation Platform Installation Guide, specifically adding the following lines 
[automationedacontroller]
eda.example.com
to the following sections:
- [2.1.1.4](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-standlone-platform-ext-database-inventory_platform-install-scenario) - Lines 46-47
- [2.1.1.5](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-example-platform-ext-database-customer-provided_platform-install-scenario) - Lines 43-44
Also, removed the SSL-related …

AAP-13734 Updates to code samples for sections 2.1.1.4 - 2.1.1.6 in the Installation Guide

---

downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
downstream/modules/platform/ref-single-eda-controller-with-internal-db.adoc

Updates to code samples in the Red Hat Ansible Automation Platform Installation Guide, specifically adding the following lines
[automationedacontroller]
eda.example.com
to the following sections:
[2.1.1.4](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-standlone-platform-ext-database-inventory_platform-install-scenario) - Lines 46-47
[2.1.1.5](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_installation_guide/assembly-platform-install-scenario#ref-example-platform-ext-database-customer-provided_platform-install-scenario) - Lines 43-44
Also, removed the SSL-related variables …

Backport 2.4 1192 AAP-13734 Updates to code samples in Chapter 2

---

downstream/assemblies/navigator/assembly-executing-content.adoc
downstream/modules/dev-guide/con-content-workflows.adoc
downstream/modules/navigator/ref-navigator-command-comparison.adoc
downstream/titles/navigator-guide/docinfo.xml
downstream/titles/navigator-guide/master.adoc

This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-1320 and includes the following change:
- Changed "Ansible navigator" to "Automation content navigator"

AAP-1320 Changed Ansible navigator to Automation content navigator

---

downstream/assemblies/navigator/assembly-executing-content.adoc
downstream/modules/dev-guide/con-content-workflows.adoc
downstream/modules/navigator/ref-navigator-command-comparison.adoc
downstream/titles/navigator-guide/docinfo.xml
downstream/titles/navigator-guide/master.adoc

This PR backports the changes from #1241 to the 2.4 branch and includes the following:
* AAP-1320 Changed Ansible navigator to Automation content navigator
* AAP-1320 - Changed title of document to Automation Content Navigator Creator Guide

[Backport] - AAP-1320 Changed Ansible navigator to Automation content navigator

---

downstream/assemblies/platform/assembly-system-requirements.adoc

This PR changes the hardcoded text for EDA, in the prerequisites section of System Requirements, to use the attribute instead.

rmeda - changed EDA to use the attribute in sys req prereqs

---

downstream/assemblies/platform/assembly-system-requirements.adoc

This backports the changes from PR #1288 but removes the reference to EDA from the 2.3 version.

[Backport] - rmeda - changed EDA to use the attribute in sys req prereqs (#1288)

---

downstream/assemblies/platform/assembly-system-requirements.adoc

This PR backports the changes from #1288 to the 2.4 branch.

[Backport] rmeda - changed EDA to use the attribute in sys req prereqs (#1288)

---

downstream/modules/platform/ref-converting-playbook-examples.adoc

This PR fixes a missing link in the AAP Migration and Upgrade Guide version 2.4. This change was requested in [AAP-14883](https://issues.redhat.com/browse/AAP-14883)

AAP-14883 add URL to link reference

---

downstream/modules/automation-hub/proc-configure-automation-hub-server-cli.adoc

This PR addresses the changes requested in https://issues.redhat.com/browse/AAP-14279 and includes the following:
Added statement about the default location of the ansible.cfg file.
Added a step to the procedure to clarify that it is the ansible.cfg file being modified.

AAP-14279 - Updated the information for clarity

---

downstream/modules/automation-hub/proc-configure-automation-hub-server-cli.adoc

This PR addresses the changes for https://issues.redhat.com/browse/AAP-14282 and includes the following changes:
Changed URL to https://console.redhat.com/api/automation-hub/content/published/
Removed statement:  You must include the api/galaxy/ subdirectory in the server URL:

AAP-14282 - Updated the galaxy URL and removed requirement for subdirectory

---

downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc

Fixes broken link in [section 4.1.3 of the AAP Installation Guide](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_installation_guide/disconnected-installation#rpm_source).

Fixes broken Satellite link in Installation Guide

---

downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc

This PR backports changes from [PR 1305](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1305) to the 2.3 branch. The original PR fixes a link in the Installation Guide.

Backport to 2.3: Fixes broken Satellite link in Installation Guide

---

downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc

This PR backports changes from [PR 1305](https://github.com/RedHatInsights/red-hat-ansible-automation-platform-documentation/pull/1305) to the 2.4 branch. The original PR fixes a link in the Installation Guide.

Backport to 2.4: Fixes broken Satellite link in Installation Guide

---

downstream/titles/release-notes/topics/new-features-oct-2020.adoc
downstream/titles/release-notes/topics/tower-intro-382.adoc

This PR fixes broken links in release notes from Oct 2020. See [AAP-15176](https://issues.redhat.com/browse/AAP-15176) for more info.

AAP-15176: fixes broken links in release notes

---

downstream/assemblies/central-auth/assembly-central-auth-add-user-storage.adoc

- Added a note to "Chapter 2 Adding a User Storage Provider (LDAP/Kerberos) to Ansible Automation Platform Central Authentication" in the [Installing and Configuring Central Authentication for the Ansible Automation Platform](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/installing_and_configuring_central_authentication_for_the_ansible_automation_platform/index). 
- Also, updated links in the table so that they contain the right format (link:https:...)
- Lastly, updated all the instances of "this section" to the actual titles of the sections referred to.

AAP-3481 Added new note and link to Chapt 8.4 in the Server Admin Guide

---

downstream/assemblies/central-auth/assembly-central-auth-add-user-storage.adoc

- Added a note to "Chapter 2 Adding a User Storage Provider (LDAP/Kerberos) to Ansible Automation Platform Central Authentication" in the [Installing and Configuring Central Authentication for the Ansible Automation Platform](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/installing_and_configuring_central_authentication_for_the_ansible_automation_platform/index). Links to Chapter 8 of the [Server Administration Guide](https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4/html/server_administration_guide/clients#protocol-mappers).
- Also, updated links in the table so that they contain the right format (link:https:...)
- Lastly, updated all the instances of "this section" to the actual titles of the sections referred to.

Backport-2.2-1234 Added new note and link to Chapt 8.4 in the Server Admin Guide

---

downstream/assemblies/central-auth/assembly-central-auth-add-user-storage.adoc

- Added a note to "Chapter 2 Adding a User Storage Provider (LDAP/Kerberos) to Ansible Automation Platform Central Authentication" in the [Installing and Configuring Central Authentication for the Ansible Automation Platform](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/installing_and_configuring_central_authentication_for_the_ansible_automation_platform/index). Links to Chapter 8 of the [Server Administration Guide](https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4/html/server_administration_guide/clients#protocol-mappers).
- Also, updated links in the table so that they contain the right format (link:https:...)
- Lastly, updated all the instances of "this section" to the actual titles of the sections referred to.

Backport-2.3-1234 Added new note and link to Chapt 8.4 in the Server Admin Guide

---

downstream/assemblies/central-auth/assembly-central-auth-add-user-storage.adoc

- Added a note to "Chapter 2 Adding a User Storage Provider (LDAP/Kerberos) to Ansible Automation Platform Central Authentication" in the [Installing and Configuring Central Authentication for the Ansible Automation Platform](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/installing_and_configuring_central_authentication_for_the_ansible_automation_platform/index). Links to Chapter 8 of the [Server Administration Guide](https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4/html/server_administration_guide/clients#protocol-mappers).
- Also, updated links in the table so that they contain the right format (link:https:...)
- Lastly, updated all the instances of "this section" to the actual titles of the sections referred to.

Backport-2.4-1234 Added new note and link to Chapt 8.4 in the Server Admin Guide
